### ISSUE TITLE
Add to FAQ: need access to 'unrestangularized' element

### ISSUE THREAD

**Issue by johneke** [mgonto/restangular#100]
First of all let me start by saying you have done some great work here. I simply love this library.

However I've run into a small problem where I am running the code below:

```
Restangular.one('element').get().then(function(element) {
    $scope.element = element;
});
```

However $scope.element now contains my element from the server plus a lot of restangular functions and properties.

This is problematic for me because I need to process the element received from my server recursively. Meaning that I need the element to be pure.

Does this functionality already exist? Is there any current way to access the 'unrestangularized' version of an object? I would expect something like:

```
Restangular.one('element').get().then(function(element) {
    $scope.element = element.preRestangularizedElem;
});
```

Thanks

**Comment by j-walker23** [comment]
I have this code in the `Restangular.setResponseInterceptor`. Should it still work? I am getting a collection that will never do any rest methods. Just displays data. I should be able to do what @FoxxMD did to get a clean collection right?

**Comment by j-walker23** [comment]
Is there anything wrong with this? Thanks for any help!

        RestangularProvider.setResponseExtractor(function(element) {
            var newResponse = element;
            if (angular.isArray(element)) {
                newResponse.originalElement = []; //add this so you don't get an error!
                angular.forEach(newResponse, function(value, key) {
                    newResponse.originalElement[key] = angular.copy(value);
                });
            }
            return newResponse;
        });

**Comment by fenos** [comment]
@j-walker23 I have the same issue, using the code as documentation seem not work , hope we are missing somenthing

**Comment by j-walker23** [comment]
@mgonto could you pretty please help us with your expertise when you get a chance?

**Comment by qbunia** [comment]
Iam also waiting for a fix to this issue.

**Comment by piyushchauhan2011** [comment]
Restangular 1.4.0 above versions have method `plain()` for working with plain response data.

![screen shot 2015-07-18 at 11 28 18 am](https://cloud.githubusercontent.com/assets/693487/8759777/889855bc-2d40-11e5-946c-639091683bfc.png)
