### ISSUE TITLE
ng-options with restangular collections

### ISSUE THREAD

**Issue by matperez** [mgonto/restangular#1003]
Hello!

I'm trying to display collection of an elements with ng-options. 

Here is my markup:

```html
<select name="terminalId" 
  ng-model="vm.order.terminal" 
  ng-options="terminal.id as terminal.name for terminal in vm.terminalList">
    <option value="">Not selected</option>
</select>
```
and that's how I get an elements:

```javascript
vm.terminalList = Restangular.all('terminals').getList().$object
```

It's work well with ng-repeat, but with ng-options i've got those "restangulized" methods displayed in my select. Am i doing something wrong or it's just incompatible with ng-options?

I've tried to use this https://github.com/mgonto/restangular#how-can-i-access-the-unrestangularized-element-as-well-as-the-restangularized-one solution but collection is still remains "restangulized".

angular 1.3.9
restangular 1.4.0|1.3.1

**Comment by dmackerman** [comment]
You can get the "plain" objects by using the `$plain()` method. That will strip out the restangular metadata.

**Comment by matperez** [comment]
Could you provide an example? How can i use it with $object?

**Comment by dmackerman** [comment]
I've never used `$object` - just because I don't like directly binding values to my view. 

Maybe:

`Restangular.stripRestangular(Restangular.all('items').getList().$object))`

**Comment by matperez** [comment]
Thanks!
