### ISSUE TITLE
customPUT 'Content-Type': undefined does not override Content-Type Header

### ISSUE THREAD

**Issue by alexleone** [mgonto/restangular#1006]
When using restangular to upload a file I need to use the header Content-Type= undefined to that the correct multipart/form and boundary types get set properly. 
It seems the inherit problem is that when passing in 'Content-Type': undefined it has no effect on the headers.

This is my restangular call: 
Restangular.all('applications/' + id).withHttpConfig({ transformRequest: angular.identity }).
          customPUT(formData, null, null, {'Content-Type': undefined, 'Accept':'*/*'}).then(
          function(response){
              return response;
          }, function(error){
              return error;
          }
        );

The function that data that is being passed in formData.
var formData = new FormData();
      formData.append('data[name]',  'someName');

The important headers:
Accept:*/*
Cache-Control:no-cache
Connection:keep-alive
Content-Length:146
Content-Type:application/json

The Request Payload:
------WebKitFormBoundaryQGOVo6A0Fp71Dwnq
Content-Disposition: form-data; name="data[name]"

whats
------WebKitFormBoundaryQGOVo6A0Fp71Dwnq--

So because the restangular does not  respect the Content-Type:undefined it gets the default application/json and doesnt add the correct multipart/form or boundary=

Using $http this does work:
$http.put('applications/' + id, formData, {
          withCredentials: true,
          headers: {'Content-Type': undefined },
          transformRequest: angular.identity
        }).success(function(response){
          return response;
        } ).error(function(error){
          return error;
        });

Sam data as before ----The function that data that is being passed in formData.
var formData = new FormData();
      formData.append('data[name]',  'someName');

Request Headers:
Accept:application/json, text/plain, */*
Cache-Control:no-cache
Connection:keep-alive
Content-Length:153
Content-Type:multipart/form-data; boundary=----WebKitFormBoundary6tnxO2dU0ORAyAyu

Request Payload:
------WebKitFormBoundary6tnxO2dU0ORAyAyu
Content-Disposition: form-data; name="data[name]"

dasadsadsasd
------WebKitFormBoundary6tnxO2dU0ORAyAyu--

If you have any ideas on this one it would be appreciated.

**Comment by grabbou** [comment]
https://github.com/mgonto/restangular#addfullrequestinterceptor

Please use `addFullRequestInterceptor` to manipulate `headers` that are about to be send :)
