### ISSUE TITLE
.one(undefined) returns the same result as .getList()

### ISSUE THREAD

**Issue by Quagh** [mgonto/restangular#1010]
Take the following example (from the readme):

```js
module.factory('Users', function(Restangular) {
  return Restangular.service('users');
});

// undefined instead of an integer
Users.one(undefined).get();

// The above returns the same result as
Users.getList();
```

I'm not sure if this is supposed to happen? If I pass `undefined`, I would suppose it would throw an exception of some sort, not return an array of all my objects.

**Comment by grabbou** [comment]
Well, as per docs and REST spec, if you pass "undefined" route generated is still /users/<undefined>, so if you have /users to return the entire collection, that's desired approach. 

But generally yes, I do agree that an exception should be thrown if there's undefined passed as in 99% it's going to be implementation error that can get quite confusing.

**Comment by Quagh** [comment]
If I do `.one()`, I expect the route to be generated to be `/users/:id`. If I want `/users`, I'd of course use `.all()`. So yes, throwing an error would be a good idea :)

**Comment by grabbou** [comment]
Also similar to #779. As users tend to use this method for creating resources, error should be thrown only when one tries to call get(), delete() or put() (as put expects an id which is undefined anyway). post() is allowed in case resource might be created.

Why?

```js
$scope.newThing = Restangular.one('things');
// some modifications
$scope.newThing.save();
```
This should do POST request to /things.

```js
$scope.newThing = Restangular.one('things').get() or Restangular.one('things, undefinedProperty).get();
```
This throws an error.

**Comment by grabbou** [comment]
@Quagh please see #892 with my comment for explanation how to create new elements properly. Undefined in one() is not going to be handled by replacing with empty string as this is not the correct usage of this method.

**Comment by grabbou** [comment]
Actually, we need to allow .one('user').get() to do GET /user/ (where we expect single element to be returned). .all('user').getList() will invoke the same URL but expect an array to be returned.
