### ISSUE TITLE
Restangular working example with requirejs

### ISSUE THREAD

**Issue by subramn** [mgonto/restangular#1012]
I keep getting the following error - Unknown provider: Restangular

(function () {
	'use strict';
	var dependencies = ['angular', 'restangular', 'app/employee/employee.module'];
	var appName = 'app';
	define(dependencies, function (angular, Restangular, employee) {
		var app = angular.module('app', ['restangular','employee']);
		app.config(config);

		config.$inject = ['Restangular'];

		function config(Restangular)
		{
			Restangular.setBaseUrl('http://localhost/Northwind.Web.Api/api/');
		}
		angular.bootstrap(document.getElementsByTagName("body")[0], [appName]);
		return app;
	});

})();

Requirejs config

require.config({

	paths: {
		'lodash':'lib/lodash/dist/lodash',
		'underscore':'lib/underscore/underscore',
		'angular': 'lib/angular/angular',
		'angularMocks': 'lib/angular-mocks/angular-mocks',
		'restangular':'lib/restangular/dist/restangular'
	},
	shim: {
		'angular': {exports: 'angular'},
		'angularMocks': {
			deps:['angular'],
			exports:'angular.mock'
		},
		'restangular': {
			deps: ['angular','underscore'],
			exports:'restangular'
		}
	},

**Comment by grabbou** [comment]
Require.js is not yet supported officially although planned for upcoming release. Please refer to #749 for further updates.

**Comment by nolazybits** [comment]
Would there be a workaround for the time being?
It seems that the other issue (#749) is more CommonJS focussed, so it might be worth having this one reopen maybe?
