### ISSUE TITLE
add resolve  parameter 

### ISSUE THREAD

**Issue by wanglong167** [mgonto/restangular#1017]
![1](https://cloud.githubusercontent.com/assets/456516/5935772/84940004-a719-11e4-8645-22c05bc31490.png)

```
  Restangular.one("article", $stateParams.articleId).get().then(function(data,headers) {
                  console.log(headers)  // =>null
             
            })
```

**Comment by grabbou** [comment]
I think that we can pass raw response object there so users can access all the properties and even raw response objects which was requested somewhere. What you think?
