### ISSUE TITLE
getting forbidden error while updating record.  My code is show in bellow

### ISSUE THREAD

**Issue by satyanani40** [mgonto/restangular#1018]
function
========================

Restangular.one("people",JSON.parse(CurrentUser.userId)).patch({
		'password_test':'hellowdddddddd'
}).then(function(data){
	console.log(data);
});

my header configure is
===========================
app.factory("TokenRestangular", function (Restangular, StorageService) {
    return Restangular.withConfig(function (RestangularConfigurer) {
   // Set access token in header.
    RestangularConfigurer.setDefaultHeaders({Authorization:'Bearer '+ StorageService.get("access_token")});
		});
	});
error information is
===================
Remote Address:127.0.0.1:8000
Request URL:http://127.0.0.1:8000/api/people/54b0bc37bed069248fb20ea8
Request Method:PATCH
Status Code:403 FORBIDDEN
Request Headersview source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0MjI1NzA5MzgsInN1YiI6IjU0YjBiYzM3YmVkMDY5MjQ4ZmIyMGVhOCIsImV4cCI6MTQyMzc4MDUzOH0.6BZZEdEDE9BMj1fasff38rq0QQUje7P3okVTViSkme4
Connection:keep-alive
Content-Length:34
Content-Type:application/json;charset=UTF-8
Cookie:_ga=GA1.4.2023418923.1422418418; _gat=1
Host:127.0.0.1:8000
Origin:http://127.0.0.1:8000
Referer:http://127.0.0.1:8000/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36
Request Payloadview source
{password_test: "hellowdddddddd"}
password_test: "hellowdddddddd"
Response Headersview source
Content-Length:101
Content-Type:application/json
Date:Thu, 29 Jan 2015 17:44:50 GMT
Server:Eve/0.4 Werkzeug/0.9.6 Python/2.7.6

**Comment by grabbou** [comment]
To be closed.
