### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by felipegs** [mgonto/restangular#1019]
Hi people,
I would like to know if the project still active.
That's a long time the no commits are maden.

**Comment by sahina** [comment]
I am curious as well.

**Comment by grabbou** [comment]
Yep, it is. @mgonto is working on v2 version which is going to be awesome and in which I am trying to participate. I am maintaining the current v1 build. There are plenty of QA issues here, so don't be worried by that. If you have any further questions, feel free to ask.
