### ISSUE TITLE
Update to lodash 3.0

### ISSUE THREAD

**Issue by niemyjski** [mgonto/restangular#1023]
I looked over the changes and I don't think that anything broke on this but an extra pair of eyes would be good: https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings

**Comment by dima-f1** [comment]
By the way, for now I can't use both bower restangular and lodash 3.x in my projects due to the "Warning: ECONFLICT Unable to find suitable version for lodash"

**Comment by tinusn** [comment]
I have had no problems upgrading to 3.1.0 so far.

**Comment by epzee** [comment]
No issues on 3.1.0 so far, any plans for upgrading?

**Comment by bmatto** [comment]
:+1:

**Comment by melnikaite** [comment]
:+1:

**Comment by grabbou** [comment]
Thanks guys for the PR. We will double check it does not break anything and update the build once completed.

**Comment by skosno** [comment]
Any update on that? We already have lodash 0.3.5.

**Comment by dima-f1** [comment]
:+1:

**Comment by zorzysty** [comment]
+1

**Comment by bmatto** [comment]
+1

**Comment by SeppItv** [comment]
+1

**Comment by aochagavia** [comment]
+1

**Comment by nforysinski** [comment]
+1

**Comment by yzhiJun** [comment]
+1

**Comment by rriemann** [comment]
:+1:

**Comment by alxscms** [comment]
👍🏻

**Comment by brandonjp** [comment]
+1

**Comment by trombom** [comment]
+1

**Comment by grabbou** [comment]
It's there guys :bomb:
