### ISSUE TITLE
getting error _error: {message: "An exception occurred: find_one() keywords must be strings", code 400

### ISSUE THREAD

**Issue by satyanani40** [mgonto/restangular#1024]
my code is show in bellow

angular.module('weberApp')
	.controller('UserprofileCtrl', function($scope, $routeParams, Restangular, InfinitePosts, CurrentUser, UserService) {
		
		$scope.UserService = UserService;
		var user_obj = Restangular.one('people', $routeParams.username);
		user_obj.get().then(function(user) {
			$scope.user = user;
            /*{
					'notifications': {
						'friend-requests': ['54ca57e95f4de41fedbc2755']
					}
				},*/
			$scope.addFriend = function() {
                $scope.user.patch(
				    {
				        "notifications":{
				            "friend-requests":[JSON.parse(CurrentUser.userId)]
				            }
				    }
				).then(function(data){
					console.log(data)

				});
			};

			$scope.infinitePosts = new InfinitePosts(user_obj);
			//get all friends
			if (user.friends.length !== 0) {
				Restangular.all('people').getList({
					where: {
						"_id": {
							"$in": $scope.user.friends
						}
					}
				}).then(function(friends) {
					$scope.friends = friends;
				});
			}
		});
	});

after requesting url getting following information in inspect element ->network->headers

Remote Address:127.0.0.1:8000
Request URL:http://127.0.0.1:8000/api/people/54ca57ea5f4de41fedbc2757
Request Method:PATCH
Status Code:400 BAD REQUEST
Request Headersview source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0MjI1NjY3ODksInN1YiI6IjU0Y2E1N2VhNWY0ZGU0MWZlZGJjMjc1ZSIsImV4cCI6MTQyMzc3NjM4OX0.WidPAJ-XKD97ERUpUoB2nB51QhSV49arIDOwtzkbcy0
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:66
Content-Type:application/json;charset=UTF-8
Cookie:_ga=GA1.4.1656087021.1422629878
Host:127.0.0.1:8000
If-Match:8aea4b34e9e4bc9c6898d4ea2947ecdaeeb56907
Origin:http://127.0.0.1:8000
Referer:http://127.0.0.1:8000/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/39.0.2171.65 Chrome/39.0.2171.65 Safari/537.36
Request Payloadview source
{notifications: {friend-requests: ["54ca57ea5f4de41fedbc275e"]}}
notifications: {friend-requests: ["54ca57ea5f4de41fedbc275e"]}
Response Headersview source
Content-Length:116
Content-Type:application/json
Date:Fri, 30 Jan 2015 16:46:52 GMT
Server:Eve/0.5.1 Werkzeug/0.9.6 Python/2.7.6

**Comment by grabbou** [comment]
MongoDB exception from you server. to be closed.
