### ISSUE TITLE
How to use restangular with underscore instead of loadash?

### ISSUE THREAD

**Issue by ajayak731** [mgonto/restangular#1026]
I installed restangular using bower. I already had underscore installed in my project. When I installed restangular, it added loadash as dependency. Can I use underscore instead of loadash as dependency for restangular  as it is mentioned in docs?

**Comment by sethkrasnianski** [comment]
Since lodash contains all methods that underscore does, plus more, I don't see why you couldn't drop in lodash instead.

**Comment by ajayak731** [comment]
I have a project already running using underscore and ng-resource. I wanted to migrate from ng-resource to restangular but it would be much better if I do not have to change underscore library

**Comment by sethkrasnianski** [comment]
lodash is a drop in replacement for underscore on the bright side.

**Comment by grabbou** [comment]
It just uses _ that should be defined in global namespace. Simply load underscore and that should do the trick (although it may not work with newer releases as we might accidentally use a method of Lodash that's not available in Underscore).
