### ISSUE TITLE
How to push values into collection. My collection show in bellow?

### ISSUE THREAD

**Issue by satyanani40** [mgonto/restangular#1027]
'notifications': {
            'type': 'dict',
            'schema': {
                'friend_requests': {
                    'type': 'list',
                    'schema': {
                        'type': 'objectid',
                        #'unique': True,
                        'data_relation': {
                            'resource': 'people',
                            'embeddable': True
                        }
                    }
                },
                
            },
        },

here friend requests is list field i want to push userid into this field on each request getting.
please tell me how to write restangular query. I done following way.

    angular.module('weberApp')
	.controller('UserprofileCtrl', function($scope, $routeParams, Restangular,
											InfinitePosts, CurrentUser,       UserService,FriendsNotific) {

		$scope.UserService = UserService;
		var user_obj = Restangular.one('people', $routeParams.username);

			user_obj.get().then(function(user) {
			$scope.user = user;

			$scope.addFriend = function() {
                $scope.user.patch(
				    {

				      "$push":  {"notifications":
				      		{
				            "friend_requests":JSON.parse(CurrentUser.userId)
				            }
						}
				    }
				).then(function(data){
					console.log(data)
				});
			};
                 });
	     });

the above query wirtten status: ok but did not updating anytthing
But doenot working above query. please help me if anybody know?

**Comment by grabbou** [comment]
To be closed.
