### ISSUE TITLE
Restangular promise not resolved in $routeProvider's resolve property?

### ISSUE THREAD

**Issue by hanfeisun** [mgonto/restangular#1029]
I'm using angularjs 1.3.11.

My entry.coffee looks like this

    $routeProvider
    .when '/',
      templateUrl: 'homePage/tripList.html'
      controller: 'TripListController'
      resolve:
        trips: (Trip) ->
          tripParam = {limit: -1, offset: 0, userId: '0000_abc235'}
          Trip.all('list_by_user').getList(tripParam).$object

service.coffee:

    .factory('Trip',
      (Restangular) ->
        Restangular.all 'trips'
    )

controller.coffee:

      .controller('TripListController',
        ($scope, uiGmapGoogleMapApi, trips, $timeout, GmapService, mapView) ->
          $scope.tripList = trips
          $scope.mapView = {center: {latitude: 51.219053, longitude: 4.404418 }, zoom: 14 };
          uiGmapGoogleMapApi.then (maps) ->
            $timeout ->
              console.log (trips)

As I understood, if I set `resolve` in a `$routeProvider`, the $routeProvider will ensure the promise object in `resolve` property is resolved before injecting them into controller. Is that right? If that's true, the `console.log(trips)` in last line should always print the final result from AJAX.. However, I found `console.log(trips)` sometimes prints an empty array, while the array in AJAX result is not empty..

Does that mean I should always wrap the result like `restangular.then(function(result){})`.. Could I avoid writing like this by putting `restangular` object in `resolve` property?

**Comment by hanfeisun** [comment]
Solved when I remove `.$object` in the resolve property... Could be closed, thanks..

**Comment by grabbou** [comment]
Glad you sorted that out :)
