### ISSUE TITLE
 I am using Restangular in the frontend. I want to push values into list field into mongodb collection.  My collection schema is shown below.

### ISSUE THREAD

**Issue by satyanani40** [mgonto/restangular#1031]
schema': {
        'friends': {
            'type': 'list',
            'schema': {
                'type': 'objectid',
                'data_relation': {
                        'resource': 'people',
                      'embeddable': True

               }
           }
        }
    }

How to push new friend id into friends list.

**Comment by grabbou** [comment]
Please refer to StackOverflow #restangular with general usage questions.
