### ISSUE TITLE
Restangular.remove() Method DELETE is not allowed by Access-Control-Allow-Methods

### ISSUE THREAD

**Issue by jy0ti** [mgonto/restangular#1033]
I'm trying to achieve DELETE Method using Restangular but it keeps giving the error Method DELETE is not allowed by Access-Control-Allow-Methods.

Have goggled a lot but havent found a solution. Request works seamlessly with a POST MAN tho

var users = Restangular.all("users", userId);
                   return users.remove()
                .then(function (response) {
                    return response;
                });
By doing above Request Method is sent as OPTIONS , I think it should be DELETE

**Comment by grabbou** [comment]
Please fix your server stack by enabling cross origin requests in your headers. Further information can be found at StackOverflow. If you provide your tech stack, then we can try to help you, but I am pretty sure there are already plenty of solutions available online.
