### ISSUE TITLE
Restangular.service returns object with only .one, .post, .getList

### ISSUE THREAD

**Issue by rich-glow** [mgonto/restangular#1037]
I would like to do the equivalent of 

```js
Restangular.all('endpoint').customGET()
```

but `customGET` method does not appear to be available for standalone `Restangular.service` object.

Am I doing something wrong?

**Comment by grabbou** [comment]
Hey @rich-glow, please see my explanation in #1051. Generally customGET, get, save and stuff are "elem/collection" methods and service is just a factory to create them so you can't use them there.
