### ISSUE TITLE
Save and retry after refresh

### ISSUE THREAD

**Issue by subarroca** [mgonto/restangular#1038]
I'm working on an SPA that is usually online but can go offline and I have to keep a log of all requests to an API. When certain requests fail I should retry them later.

I've got a local DB to save all requests. When my app starts I retrieve them all and retry the ones marked to.

What I need is a way to config a Restangular object based on what I already sent. I have a response interceptor and I'm saving the restangular response object.

{
  config: {
    headers: Object,
    method: "GET",
    params: Object,
    transformRequest: Array[1],
    transformResponse: Array[1],
    url: "..."
  },
  data: {...},
  headers: {...},
  status: 200,
  statusText: "OK"
}

Is there a function to create a Restangular with the given config object?

**Comment by grabbou** [comment]
No, not actually.

I would suggest using regular $http request. As probably your attempts to retry will be happening in the background - you do not need response transformations and nice query syntax.

**Comment by fernandomoraes** [comment]
You could use a http queue. In the moment thats you stay offline, you add to queue, and after, when you are online, you remake all requests in the queue.

See https://github.com/fernandomoraes/angular-implicit-oauth2/blob/master/src/httpqueue.js

**Comment by subarroca** [comment]
Thanks, obrigado. I'll try it

**Comment by grabbou** [comment]
Please paste yours solution here and I'll be more than happy to put it into our Readme section :)
