### ISSUE TITLE
Unable to get full headers

### ISSUE THREAD

**Issue by npearson72** [mgonto/restangular#1039]
I'm trying to get the etag to be included in the response headers, along with a few other bits I'm sending from the server, but am only getting:

`Object {content-type: "application/json; charset=utf-8", cache-control: "max-age=0, private, must-revalidate"}`

Using curl I can see all the headers. How come they don't appear in the response I get with Restangular?

**Comment by grabbou** [comment]
To be checked against #860

**Comment by grabbou** [comment]
Have you tried (setFullResponse)[https://github.com/mgonto/restangular#setfullresponse] ?
