### ISSUE TITLE
Getting status code 0 regardless with ErrorInterceptor

### ISSUE THREAD

**Issue by jrgleason** [mgonto/restangular#1042]
I am using error interceptor to capture any error. I have set it up in my module, it didn't work when I had an $http interceptor so I got rid of that but when I add the following...

    Restangular.setErrorInterceptor(function (response, deferred, responseHandler) {
        console.log("Service error occured");
        if(errorCount > 5){
            $interval.cancel(ticker2);
        }
        errorCount++;
    });

The error code is always 0 so I can't determine if it is a 404 or 401.

**Comment by jrgleason** [comment]
Looks like I just had an $http somewhere that was throwing things off try a search for $http in your code.

**Comment by jrgleason** [comment]
This still appears to be an issue when I am getting a 404 but not 401. Error message is...

    net::ERR_CONNECTION_REFUSED

**Comment by grabbou** [comment]
Is regular $http provider returning you the same error? I don't think it's Restangular related issue.

**Comment by grabbou** [comment]
Typically error 0 occurs when there's a CORS issue although browser might provide a more descriptive error message and status code. Please check if your REST is CORS-enabled. Additionally, try to debug "net::ERR_CONNECTION_REFUSED" as this is not related to Restangular at all. If you want to get faster and more descriptive answer of your issue, I suggest asking folks at StackOverflow so they can help you troubleshoot your /.NET/Java/Node.js/ server set up.
