### ISSUE TITLE
Restangular append slash

### ISSUE THREAD

**Issue by carlware** [mgonto/restangular#1045]
Hi, I do not know how to configure Restangular to not add an extra slash when I make a patch o remove request.

```javascript
var Res = Restangular.withConfig(function(r){r.setRequestSuffix(' ');});
var res = Res.all('geofences/polygons/').getList().$object  // I need send the slash at the end

var  p0 = res[0];
p0.name = "new name";
p0.patch()  // the route of the patch is geofences/polygons//90
            // is adding a slash I need a route like "geofences/polygons/90" 
            // otherwise the server returns an 404
```

how can I make patch or remove request without adding a slash ?

I was doing something hacky like this, but i believe is not the best solution
```javascript
p0 = p0.route.substr(0, p0.route.length-1);
```

**Comment by grabbou** [comment]
True, RestAngular should use kind of `node path` library when merging paths to ensure that if user had passed slash at the end of Res.all/getList, collection item method should still work. 

To be fixed within few days with appropriate test cases. Stay tuned :)

**Comment by grabbou** [comment]
There's a nice small library called `url-join` which acts like `path` from node. Quite useful to depend on to be 100% sure those errors do not occur in production.

**Comment by carlware** [comment]
Hi, I was checking the code, of some url libraries that normalize the url but i think that requirements of restangular are simpler. Because in the function ```Path.prototype.base``` the only part of the url involve is the path. The scheme part, domain and port are not involve. But the reason I think the normalization only needs to check against multiple backslashes only. Let me know if I am wrong.

I initialized a function to normalize the url path, I did some basic test cases. What do you think ?
https://github.com/carlware/restangular/compare/me

**Comment by grabbou** [comment]
Yeah, that can work. I quite like the tests cases you've created. What you think about adding some additional ones, like 
```js
Restangular.one('accounts/', 123).getList('/buildings/')
```
so we can test how it deals with chained calls?

**Comment by grabbou** [comment]
Also, you do not need to define a new $http backend, please use the one provided. That's all. When it's done, please submit PR and I will merge it straight away.

**Comment by grabbou** [comment]
Above code to be tested as well:

```js
myApp.config(function(RestangularProvider) {
  RestangularProvider.setBaseUrl("http://localhost:8080")
})
...
Restangular.all("/api/foo/items").getList()
// Above results in GET to http://localhost:8080//api/foo/items.
```
Another PR provided here https://github.com/jleskovar/restangular/commit/2d103b14e4af5590799324161bfc7942b9ef6d98 that uses different solution, the best one to be chosen.

**Comment by carlware** [comment]
good test cases, those throw an issue in in the url normalize. I fixed by split the url in the scheme and the rest. What do you think now?

https://github.com/carlware/restangular/compare/me

**Comment by grabbou** [comment]
Cool. I've created a PR from your branch to merge those changes into wip/cleanup-improvements just to test it a bit more before it's in master. Will review & merge later today. Thanks! I quite like the way you've created that by making a separate method.

**Comment by carlware** [comment]
No thanks to all of you, this is a great api.

**Comment by galuszkak** [comment]
Isn't that merge in #1055 ? This ticket I think should be closed... @grabbou ?

**Comment by grabbou** [comment]
yep, good catch @galuszkak
