### ISSUE TITLE
Accessing the laravel routes using restangular.

### ISSUE THREAD

**Issue by ricker07** [mgonto/restangular#1046]
I'm using laravel for back-end and restangular for front-end.

my restangular service:
  
  _this.getResignationType = function (id) {
     return Restangular.one('laravel_route/'+id).get();                    
  };

my laravel route:

   'laravel_route/{id}' => [
        'before'    => 'auth',
        'as'        => 'api.laravel_route.initSomeFunction', 
        'uses'      => 'LaravelController@initSomeFunction'
    ],

Question:
i can't access the routes of laravel, i mean error says, i'm unauthorized to access it. i think restangular can authorized it. i try CORS and restangular.withConfig() but it doesn't work. any suggestion in my case? sorry if it's too far for a issue in restangular, i just need some help. thanks.

**Comment by grabbou** [comment]
Hi,
Did you remember to set appropriate auth headers? Maybe you are using kind of token-based auth or header/cookie based stuff?

**Comment by ricker07** [comment]
hmmm.. i try to remove token-based auth, and it worked. but i need to set
the token-based auth for security. can u help me to access routes with auth
using restangular, i dont know how to set the appropriate headers. like for
example "RestagularConfig.setDefaultHeaders({Authorization : here i don't
know what token to be insert.});"

**Comment by grabbou** [comment]
What token based auth you are using? Basically if your auth flow requires "Authorization" header to be present, just do
```js
{Authorization: '<<token_string>>'}
```
If you are using JSON WEB Token, then put "Bearer <<token_string>>" as a Authorisation header. Obviously remember to replace <<token_string>> with the real token you have :)
