### ISSUE TITLE
Is Restangular dead?

### ISSUE THREAD

**Issue by spheregenomics** [mgonto/restangular#1048]
There are a lot of open pull requests but the build is failing and no updates for months...

**Comment by grabbou** [comment]
No, it's not dead. @mgonto is working on the V2 version and I am helping him maintain v1. Please stay tuned as we are trying to close all of the remaining PR's and issues in ~2 weeks.

**Comment by spheregenomics** [comment]
Happy to hear it!

**Comment by patbaker82** [comment]
@grabbou Hi Mike, thanks for that answer.  I'm starting an angular 1.3 / 1.4 project and looking to select a library for interacting with a REST API.  Are you planning a maintenance release for the 1.X.X branch?  I'm just curious because I know you are working through the PR's, etc.  However, there hasn't been a release since April.  I'm asking this from a curiosity perspective and want to emphasize that I appreciate the effort.

**Comment by GeoffreyEmery** [comment]
is there a roadmap or timeline for 2.0?

**Comment by grabbou** [comment]
Hey @patbaker82 , I am waiting for @mgonto  to merge all the PRs and do the release as he has the whole access. 1.x will be maintained along the new 2.0 release for some time so you can safely start using it now.

@GeoffreyEmery not yet, but will be published pretty soon.

**Comment by skosno** [comment]
:+1: @grabbou & @mgonto Do you guys have some plans you could share about Restangular? It seems it stagnated on github and probably a lot of people are wondering if this is something to use or it is no longer a valid approach? Are there any plans to continue developing current version/new version? Or Angular 2 / other approaches are making Restangular something that is best replaced with something else?

**Comment by spheregenomics** [comment]
+1

**Comment by portus84** [comment]
+1

**Comment by chaoranxie** [comment]
+1

**Comment by grabbou** [comment]
Hey guys, thanks for your patience! Best if you ask @mgonto as I am just trying to get this codebase running w/o any errors (I know, wasn't too productive in last month). I am not sure if this version will support Angular 2, but the new one we had in plans with @mgonto will, indeed.

**Comment by philippeluickx** [comment]
+1

**Comment by amatiasq** [comment]
Any news in this topic?

**Comment by Jonjoe** [comment]
2.0 is in beta, should we be keeping our eye on this or do we need to start looking elsewhere? No stress, just have three angular projects in the pipeline that could do with your restful magic <3

**Comment by jpragit** [comment]
Any updates on this?  It doesn't look like there have been any code changes since July of last year.

**Comment by Meekohi** [comment]
If the angular 1.x version isn't going to be supported anymore it'd be good to give a heads up at the top of the README. The prospect of a 2.x version doesn't help everyone with bugs on 1.x

**Comment by AmrN** [comment]
+1

**Comment by sikorsky555** [comment]
mgonto moved onto another role so he won't be working on version 2. The branch for 2.0 was last touched in October 2014. Is anybody else planning on taking on the role of making Restangular 2.0?

**Comment by matiaslarsson** [comment]
+1

**Comment by rinogo** [comment]
@sikorsky555: I guess you have your answer :(

**Comment by jetsgit** [comment]
I think it's dead, Jim.

**Comment by daviesgeek** [comment]
It's not exactly dead, but the original author is no longer maintaining the project and has passed it on to a couple of us. It's been hard trying to keep up with the issues, but there should be a 1.5.3 release shortly!

**Comment by jetsgit** [comment]
Good to hear it is still on-going / evolving.  Has anyone worked on the 2.0 branch?  It looks like there are a couple of projects to provide an Angular 2.0 resource:  

https://github.com/sagarrabadiya/ng2-resource
https://github.com/troyanskiy/ng2-resource-rest
https://github.com/darekf77/ng2-rest

Not sure any of them have the depth that Restangular does.
Does not appear to be anything like ngResource in Angular 2

**Comment by daviesgeek** [comment]
I don't know whether anyone has worked on the 2.0 branch. 

I haven't but, I actually wrote my own Restangular like library: https://github.com/daviesgeek/restjs I haven't used it in production yet, since we have a lot of Restangular code at work, but that was the idea when i wrote it. It's basically my take on Restangular 2.0, rewriting it to change some of the stuff I didn't like about 1.X and updating it to use some more modern JS conventions.
