### ISSUE TITLE
Restangular.extendModel: Making some of the data model properties private

### ISSUE THREAD

**Issue by catchshyam** [mgonto/restangular#1053]
I am using Restangular and the ability to extend the data model through extendModel function of Restangular is very cool. However, as a side effect of extendModel, all the properties of my data model gets exposed. For example, following is the raw object I get from backend,

```js
user: {
    name: xxx,
    email: xxx,
    address: xxx,
    age: xxx,
    basicSalary: xxx,
    perks: xxx
}
```

I extend my data model like below,
```js
Restangular.extendModel('user', function(userModel){

      //I am exposing a fullSalary function. But basicSalary and perks 
      //still stays exposed
      userMModel.fullSalary = function(){
           return this.basicSalary+this.perks;
      }

      return userModel;
})
```
Now, I would not want to expose basicSalary and perks but keep it with in user object to compute the full salary. Is there a way I can selectively expose the variables when I do Restangular.extendModel on my user resource?

Thanks,

**Comment by daviesgeek** [comment]
No there's currently no way. JavaScript doesn't have private methods or properties, so this would be hard to implement in a way that would make sense. I'm sure there's a way to implement this for your specific use case.

I'm going to close this issue for now, feel free to comment with further info or if you can find a way to implement.
