### ISSUE TITLE
Rails API object type wrap

### ISSUE THREAD

**Issue by aug-riedinger** [mgonto/restangular#1061]
Rails likes to receive data as such, in POST/PUT operation:

```
{
  user: {
    id: "fj438ljf",
    name: "My Name"
  }
}
```
To be able to call `User.create(params[:user])` as `params` contains more request data (that are not sent by the client, eg. controller and action name among other).

But when I do:
```
Restangular.oneUrl('user', '/api/v1/user.json').get().then(function(user {
  $scope.user = user;
});

// later
$scope.user.put()
```
I happen to send:

```
 {
    id: "fj438ljf",
    name: "My Name"
  }
```

I have tried my way with `customPut` as mentionned in this issue: https://github.com/mgonto/restangular/issues/819
but without any chance. I don't understand how it is supposed to work.
Neither with `addRequestInterceptor`, don't understand how it works. 

How can I send a prefixed `{user: data}` ?

Thanks a lot

**Comment by grabbou** [comment]
Hey,

First of all:

1. https://github.com/mgonto/restangular#setbaseurl
2. https://github.com/mgonto/restangular#setrequestsuffix

So your actually calls are without /api/v1 and .json.

Instead of 
```js
Restangular.oneUrl('user', '/api/v1/user.json').get().then(function(user {
  $scope.user = user;
});
```
do
```js
Restangular.one('user').get();
```
and that will work flawlessly.

In terms of putting/posting, this will solve your issue https://github.com/mgonto/restangular#addrequestinterceptor;

```js
Restangular.addRequestInterceptor(function(elem, operation, what, url) {
   if(operation === 'POST' && what === 'user') { 
      return {
         user: elem
      };
   }
   return elem;
});
```

Hint: Try console.logging what & operation in request interceptor to make sure you use correct values in if statement.

**Comment by aug-riedinger** [comment]
Thanks a lot for such quick help!

I'm not really in a RESTful resource case, only `get /user` that sends current user data and `put /user` that updates its value.
Your solution looks great!

Thanks again

**Comment by aug-riedinger** [comment]
The interceptor you suggest is actually called, the `operation` and `what` have the expected value, but the data sent is still:

```
 {
    id: "fj438ljf",
    name: "My Name"
  }
```

Any idea why?

Thanks

**Comment by aug-riedinger** [comment]
Found it, `PUT` should be lowercased:

```
            if(operation.toLowerCase() === 'put' && what === 'user') { 
              return {
                 user: elem
              };
            }
```

All set!

**Comment by grabbou** [comment]
That's why I suggested console.log there to find the valid parameters :)
