### ISSUE TITLE
Lodash/Underscore should be injected, and not presumed to be there

### ISSUE THREAD

**Issue by XVincentX** [mgonto/restangular#1065]
Hello!
Actually restangular assumes that lodash/underscore is already loaded and available as a global object.
This behaviour will make this code fail

```javascript
import angular from 'angular';
import "lodash"
import "restangular";

var polls = angular.module("pollsClient", ["restangular"]);
```

While this one will work

```javascript
import angular from 'angular';
import _ from "lodash"
import "restangular";

window._ = _;

var polls = angular.module("pollsClient", ["restangular"]);
````

**Comment by BrianSipple** [comment]
I encountered the same problem (and was able to use the same fix!).

+1 if there's no reason not to implement the injection approach.

**Comment by XVincentX** [comment]
Just to update my part,I ended up removing restangular for my project and using a different library

**Comment by crissdev** [comment]
![rq28o](https://cloud.githubusercontent.com/assets/822571/10137831/3024e89e-6604-11e5-9313-968f08419caa.jpg)


@XVincentX What did you use instead?

**Comment by XVincentX** [comment]
`angular-hy-res`: https://github.com/petejohanson/angular-hy-res

**Comment by daviesgeek** [comment]
This was fixed here: https://github.com/mgonto/restangular/pull/1284
