### ISSUE TITLE
how do i get a single resource from api? 

### ISSUE THREAD

**Issue by em0xi0nx** [mgonto/restangular#1067]
it keeps on telling me "Response for getList SHOULD be an array and not an object or something else"

the api only have one object but i cant get the data from it. 

![blabla](https://cloud.githubusercontent.com/assets/7353702/6430100/fd456354-c036-11e4-9ea7-e928b81d189f.jpg)

![basd](https://cloud.githubusercontent.com/assets/7353702/6430105/2ee63f3c-c037-11e4-8ed8-9f6c154e73e3.jpg)

**Comment by JeroenVanOort** [comment]
The `getList` function is used to access a list of items and therefore expects an array. Since you're trying to get one item, the `one` and `get` functions are probably what you're looking for.

**Comment by daviesgeek** [comment]
Since it seems like this issue is resolved, I'm going to close this for now. Feel free to re-open if there's still an issue.
