### ISSUE TITLE
Cache request in a certain configuration context not working

### ISSUE THREAD

**Issue by fabarea** [mgonto/restangular#107]
I am trying to cache requests according to the [documentation](https://github.com/mgonto/restangular/#can-i-cache-requests) but only for a certain configuration as described [here](https://github.com/mgonto/restangular/#how-to-create-a-restangular-service-with-a-different-configuration-from-the-global-one). The example given with the `setBaseUrl()` is working (path are affected as expected) but it looks the `setDefaultHttpFields({cache: true});` is completely ignored although it would work when put globally. Do you have a clue? My code look like:

<pre>
angular.module('myApp.services').factory('CachedRestangular', function (Restangular) {
    return Restangular.withConfig(function (RestangularConfigurer) {
        RestangularConfigurer.setDefaultHttpFields({cache: true});
    });
});
</pre>

**Comment by riyazbhanvadia** [comment]
Hi,

I want to cache particular request but it should get call once its parameter gets update.

I am using restangular cache is working for me but once my parameter change request does not get call.
