### ISSUE TITLE
customPATCH

### ISSUE THREAD

**Issue by ridiculous** [mgonto/restangular#1076]
Why is there no `customPATCH` method?

**Comment by stevermeister** [comment]
+1

**Comment by hermanlit** [comment]
+1

**Comment by bigjoevtrj** [comment]
+1

**Comment by daviesgeek** [comment]
+1

**Comment by igorissen** [comment]
You can use this

```
customOperation(operation, path, [params, headers, elem])
```

> This does a custom operation to the path that we specify. This method is actually used from all the others in this subsection. Operation can be one of: get, post, put, remove, head, options, patch, trace

**Comment by daviesgeek** [comment]
@igorissen yes you can, but there are aliases to all the other methods (customGET, customPOST, etc…), but not PATCH.

**Comment by ridiculous** [comment]
Yeah, that's what i learned from the author. I need to open a PR to add that

**Comment by cagodoy** [comment]
+1

**Comment by cagodoy** [comment]
@ridiculous any plans of making the PR ?

**Comment by ridiculous** [comment]
@cagodoy Thanks for reminding me! https://github.com/mgonto/restangular/pull/1230 should work

**Comment by cagodoy** [comment]
good! :D

**Comment by hyungouk** [comment]
+ 1 @ridiculous :+1:

**Comment by iberodev** [comment]
it says it's merged but I keep getting `.customPATCH is not a function` with version `"restangular": "1.5.2"`
