### ISSUE TITLE
invalidating cached data

### ISSUE THREAD

**Issue by c0debreaker** [mgonto/restangular#1085]
hi @mgonto ,

I found some notes which I think will help me. I found it from here - https://github.com/mgonto/restangular/issues/594

I have a question regarding your code below. In my own code, I have cache set to true which will cache always. Looking at your code below, you are using $cacheFactory. Am I right that the code below will also cache my GET requests?

```
 var cache = $cacheFactory('http');
    Restangular.setDefaultHttpFields({cache: cache});
    Restangular.setResponseInterceptor(function(response, operation) {
      if (operation === 'put' || operation === 'post' || operation === 'delete') {
        cache.removeAll();
      }
      return response;
    });
  };
```

**Comment by c0debreaker** [comment]
I got it working :)

**Comment by abhinandankothari** [comment]
@c0debreaker I am try to do exactly same thing, Can you help me out how did you get it working ?
