### ISSUE TITLE
Purpose of save() function

### ISSUE THREAD

**Issue by rvillars** [mgonto/restangular#1095]
I really can't see the purpose of the save() function on an element. Documentation says: "determine whether to do PUT or POST accordingly".

Calling save on a server element of course calls PUT. But what is the POST for? I only found a few examples of how new elements could be created:

1. Create a new element as suggested in the docu by $scope.myElement = {}; :
Calling save() is not possible because the object is not restangularized.

2. Restangularize the element as suggested e.g. in #964 by Restangular.all('elements').post(myElement);: 
Element already posted, no need for the POST part in save() anymore.

3. Restangularize the element by Restangular.restangularizeElement:
This is actually the only case where the POST part of the save() method makes sense but it is terribly complicated. The function can't be called on a service created by Restangular.service() so Restangular itself needs to be injected into the controller. It needs al least 3 parameters, one of it would be the route i already defined by creating a service. Redundancy. 

Wouldn't it be just easier to add the save function to a collection and give it the element as parameter?
```javascript
var Elements = Restangular.service('elements')
$scope.myElement = {};
$scope.elements = Elements.getList().$object;
$scope.elements.save($scope.myElement);
```
The collections save() function could then even handle the addition of the element to the collection if the element got posted so no manual push is needed. This would us save a lot of code.

**Comment by mgonto** [comment]
Hey there,

You can use save if you create your element with one.

The idea of save being used with post is as follows:

```js
var user = Restangular.one('users');
user.name = 'gonto';
user.save() // Does POST
```

Does this make sense?

Cheers!

**Comment by rhys-vdw** [comment]
Hi, I've been totally stuck on this as well. Since this is the closest issue I have, I'll comment here.

I want to do something like this:

```JavaScript
function create(myCollection) {
  var instance = myCollection.push(myCollection.one())
  return instance
}
```

This just doesn't work, as it tries to append an additional nested route. (ie. `/the/correct/route/undefined`).

My next best guess was `myCollection.parentResource.one(myCollection.route)`, but the parent resource does not have the `one` method.

Is there any way to create a new model with the collection object?

**Comment by rhys-vdw** [comment]
Ah, cool. I've worked out one viable workaround:

```JavaScript
restangular.restangularizeElement(collection.parentResource, {}, collection.route)
```

It would be *so much easier* if you could do the same thing via:

```JavaScript
collection.one()
```

**Comment by philippeluickx** [comment]
Still confusing. If I have an object that I pass in from my frontend, how do I then elegantly populate this to the Restangular element? Going through all properties and save them one by one is hopelessly redundant.
