### ISSUE TITLE
Add additional param to request

### ISSUE THREAD

**Issue by mpaul31** [mgonto/restangular#1097]
all my remove function calls need to pass in an additional query string param. i tried using both request interceptors to set this globally but not luck. is this possible? if so, can i see a code example pls?

thanks!

**Comment by daviesgeek** [comment]
[In the docs](https://github.com/mgonto/restangular#collection-methods):

> **remove([queryParams, headers]):** Does a DELETE. By default, remove sends a request with an empty object, which may cause problems with some servers or browsers. This shows how to configure RESTangular to have no payload.

I'm going to close this issue. Feel free to re-open if there's still an issue
