### ISSUE TITLE
Cant figure out how to get restangularized collection or object with custom GET

### ISSUE THREAD

**Issue by porebrique** [mgonto/restangular#1103]
Let's say I have Restangular.service('users'), pointing to 'api/users/' and sometimes need GET to 'api/users/foo', to perform some complex filtering that cannot be done using GET params (or maybe I dont want to expose filtering logic to frontend, it doesnt matter).

Object, returned by Restangular service, doesnt have .customGET method. I can use .customGET method of restangular itself, but returning object, or collection, isnt restangularized, so I cannot work with it. I get even more confused because of quantity of seemingly related parts of restangular (.customGET, .allUrl,  .getList(subElement)), but cant find their combination that probably fits my case.

How is this possible? Can I do Restangular.service('users').getList('some-additional-url') somehow? 
I suppose this might be not really restful way to do things, but can't figure out how to do this other way.

**Comment by LunarDevelopment** [comment]
This is also an issue I'm struggling with. 
The gist of my issue: 
factory: { profit: Restangular.service('profit') }
controller:  factory.profit.customGET().then... $scope.profit = results

I get the error:  API.profit.customGET is not a function
    at new <anonymous>

**Comment by LunarDevelopment** [comment]
Found this issue: https://github.com/mgonto/restangular/issues/1051 

Long story short: We've been using a "multiple" query against a "single" response. 

We need to use a query which expects a single object reply... I think.

**Comment by porebrique** [comment]
Thank you. But I decided to switch to Restmod. Can't say it's perfect, but many things are more intuitive and, well, it just works without making me frustrated.

**Comment by daviesgeek** [comment]
The correct solution to this problem would actually be to use `all`:

```js
Restangular.all('users') // customGET is available here
```

Since it seems like you're not using Restangular, I'll go ahead and close this issue.
