### ISSUE TITLE
Minifications

### ISSUE THREAD

**Issue by iloverails** [mgonto/restangular#1106]
I'm getting error "data is not defined" when trying to uglify restangularjs with my app

**Comment by grabbou** [comment]
Minifying works for us. Please make sure the error does not come from another file in your app.

**Comment by iloverails** [comment]
when I minify all scripts without restangular - it works fine, but when I include this file to grunt uglify assets array I'm getting this error:
data is not defined (for this block: (data=s(i[b.restangularFields.parentResource],g,i[b.restangularFields.route],!0,null,f))

**Comment by grabbou** [comment]
We use uglify while building and releasing new versions (even today that didn't occur). As a workaround - try putting already minified Restangular version to uglify instead of the normal one. That shouldn't throw an error. If it works - then it's a really interesting case.

**Comment by iloverails** [comment]
Unfortunately it does not work as well :(
