### ISSUE TITLE
Response JSON cannot contain `options` key

### ISSUE THREAD

**Issue by aramalipoor** [mgonto/restangular#1107]
I don't why but when I debugged through my `Restangular` usage code I found that if my response json contains a `options` key in the data `Restangular` will override it with its `options()` method.

I cannot even access the original object with `plain()` method.

Is this a bug, or it's just me missing a point?

**Comment by tuhoojabotti** [comment]
I think it's a bug also. I would find it nicer to have all the Restangular methods in the prototype instead and have some way of using them if they're overridden like `model.restangular('options', params...)`

**Comment by Stalinko** [comment]
Any progress on this?
It forces me to get rid of "options" name because it's reserved. As well as "get, put" and many other names which are added to all json models automatically.

**Comment by anggiaj** [comment]
Here's how i get around with this issue:

```javascript
RestangularProvider
  .addResponseInterceptor(function(data) {
      data._options = data.options;
      return data;
    })
    .addElementTransformer('posts', false, function(element) {
       element.options = element._options;
       delete(element._options);
       return element;
    });
```

**Comment by allan-simon** [comment]
I got bite by this bug too, the API was returning "all" which is already used by the restangular object

**Comment by Michiel-s** [comment]
Same for me. Got the problem with 'trace'. Took me some time to diagnose the bug. It's a problem with all functions that are added by restangular. @mgonto do you have a solution?

**Comment by daviesgeek** [comment]
[`setRestangularFields`](https://github.com/mgonto/restangular#setrestangularfields):

```js
RestangularProvider.setRestangularFields({
  options: 'newOptionsMethod'
})
```

I'm going to close this issue for now, but feel free to re-open if there's still an issue!

**Comment by tomciklukas** [comment]
May I suggest reopening this issue? I understand that some response fields become restangular methods and therefore the issue of losing their values is called feature and "workaround" is to use `setRestangularFields` method of `RestangularProvider`. BUT, author has presented another issue, more pressing, I believe ... that is: `plain` method doesn't really returns the real object from response, but rather returns objects itself, stripped of restangular methods, and that is hardly satisfactory.

**Comment by bostrom** [comment]
Check the discussion in https://github.com/mgonto/restangular/issues/374. 

Restangular creates its own properties on the Restangularized objects. These property names may be changed with `setRestangularFields` if they are clashing with properties on the object being restangularized. This is how Restangular works for now and is nothing we're going to change. 

About the `plain` method, it's an alias for `Restangular.stripRestangular` which removes all properties set on the object by Restangular and returns the object as it was before the Restangular properties were added. So I'm not sure what you mean with 

> plain method doesn't really returns the real object from response, but rather returns objects itself

Do you mean that `plain()` should return the raw response data, as it looked before all responseInterceptors and other treatments? Can you provide some sample code that shows how you think it should work? 

I'm not reopening this yet as there's nothing here that indicates a bug in Restangular. This is just how it's designed at the moment.
