### ISSUE TITLE
Restangular with IE8

### ISSUE THREAD

**Issue by restavinash** [mgonto/restangular#1110]
Hello

I am using restangular (version 1.4.0) in angularjs which does not work with IE 8. Can anyone help me to resolve this issue? 

The actual issue is web method is not get called when I run the application in IE 8. IE 9 and all the latest versions work fine with that restangular version.

Please let me know if there is any workaround to resolve this issue.

Thanks in advance.

**Comment by daviesgeek** [comment]
[Angular dropped IE8 support years ago](https://blog.angularjs.org/2013/12/angularjs-13-new-release-approaches.html). According to [the IE guide](https://docs.angularjs.org/guide/ie), IE 9 should work as expected. 

Restangular uses Angular components under the hood, so this really isn't something that could be fixed. If you find a solution to make it work on IE 8, feel free to respond or open a PR, but I'm going to close this issue for now.
