### ISSUE TITLE
Update for Angular 1.3.x

### ISSUE THREAD

**Issue by nforysinski** [mgonto/restangular#1112]
The README states support for Angular 1.2.x, but Angular stable is up to 1.3.x - that may just be a README update. I've done some limited development against 1.3.x and have had good results but I am sure my tests are not as good as yours.

**Comment by tinusn** [comment]
The readme was just updated, and restangular has worked flawlessly with 1.3 for a long time.

**Comment by nforysinski** [comment]
Per the README:

>Restangular supports all angular versions including 1.0.X, 1.1.X and 1.2.X (1.2.4 being the current at the time)

If it supports 1.3.x, shouldn't we give it a quick update to specify that?

**Comment by tinusn** [comment]
My bad, I did not see that section - so yes, it should be updated.

**Comment by daviesgeek** [comment]
I submitted a PR (#1393) to update this
