### ISSUE TITLE
angular.toJson() contaminated with Restangular properties

### ISSUE THREAD

**Issue by janbaykara** [mgonto/restangular#1124]
Properties like the below contaminate `object`s rendered as JSON strings by `angular.toJson()`.

```
{
      "route": "modules",
      "reqParams": null,
      "$fromServer": true,
      "parentResource": null,
      "restangularCollection": false,
}
```

It would be useful if (a) `angular.toJson()` removed these properties, or (b) there was a Restangular-specific method to remove these properties.

**Comment by mmichaelbiz** [comment]
Have you tried:

```
Restangular.stripRestangular(elem)
```

**Comment by plong0** [comment]
or `elem.plain();`

**Comment by brunowego** [comment]
Thanks @mmichaelbiz and @mmichaelbiz!
