### ISSUE TITLE
Cancelling async request when make a new one

### ISSUE THREAD

**Issue by yeripratama** [mgonto/restangular#1145]
Hi,
I'm kind of new to this asynchronous thing, and I have a problem here. I'm making an api-call to my web-service when I submit a form.
Before the previous request completed, is it possible to cancel / overwrite the previous request with a new one when I submit the form again ?
Can anyone give me a clue?

Thanks for the help.

**Comment by daviesgeek** [comment]
Yup: https://github.com/mgonto/restangular/issues/1377#issuecomment-226625799
