### ISSUE TITLE
Creating empty Restangular elements?

### ISSUE THREAD

**Issue by galuszkak** [mgonto/restangular#1152]
Hi,

I love Restangular very much. Last time I hit an edge case using it and this is maybe my misconception about how it works. Please close this if I don't get this right.

I'm using Restangular.extendModel to add methods for changing values acording to system for handling units. The problem is that this works fine if I get objects from server. If I want to create object in browser then until I send object and get back restangularized object then I'm without that methods from model.

Can I create restangular element that won't be send? 

So imagine something like this (this code could have some errors, I just write it to show use case):

    Restangular.extendModel('building', function (model) {
        model._getLength = function (value) {
            if (service.isImperial()) {
                return value * 23.5
            } else {
                return value;
            }
        };
    }
 
    var building = Restangular.one('building', 1).get();   
    building._getLength(2); // works
    
    var building_2 = {}; // How to create object without sending it to server??
    building_2._getLength(2) // doesn't work
    Restangular.all('building').post(building_2).then(function(obj){
        building_2 = obj;
        building_2._getLength(2) // work again
    });  // Until POST I don't have method from models

**Comment by rhys-vdw** [comment]
This is a big hole in the Restangular API, as far as I can tell. The most confusing thing about Restangular is that it presents a `save` method which is meant to automatically determine whether to use PUT or POST, but has no way of creating models that don't already exist...

This is my patch, but it's imperfect:

```js
Configurer.setOnElemRestangularized(function(elem, isCollection, what, Restangular) {
  var collection;
  if (isCollection) {
    collection = elem;
    collection.create = function(properties) {
      var addMethod, instance;
      instance = Restangular.restangularizeElement(
        collection.parentResource,
        properties || {},
        collection.route
      );
      return instance;
    };
  }
  return elem;
});
```

However it generates incorrect routes in some cases, so it obviously needs some work. If you can get this approach working I'd love to hear what I'm doing wrong.

**Comment by rhys-vdw** [comment]
Oh, and the use case is meant to be this:

```js
var newComment = restangular.one('users', 5).all('posts').create({ title: 'Hello!' });
newComment.content = 'Hi there, this is a post';
newComment.save().then(/* ... */);
```

**Comment by rhys-vdw** [comment]
So just to be clear, the problem here is this (and maybe this deserves its own issue)...

```js
var newB = Restangular.one('people', 5).all('limbs').create({ type: 'arm' });
newB.save()  // correctly POSTs to `baseUrl/people/5/limbs`
.then(function (result) {
  console.log('id', result.id) // prints `id 42`.
  result.type = 'leg';
  return result.save(); // incorrectly PUTs to `baseUrl/people/5/limbs/undefined/5
});

**Comment by rhys-vdw** [comment]
According to [this](https://github.com/mgonto/restangular/issues/1095#issuecomment-89348185) you can do this: 

```
var building_2 = Restangular.one('building');
building_2._getLength(2);
```

**Comment by fatbrain** [comment]
+1 is there any progress on this?

**Comment by daviesgeek** [comment]
From reading the original example, it looks like you should be able to do this:

```js

var building_2 = {}
Restangular.restangularizeElement(null, building_2, 'building')
building_2._getLength(2)

```

http://plnkr.co/edit/FNwFGjTnAfC4lHasGiB5?p=preview

**Comment by galuszkak** [comment]
Awesome! Never thought about that. Thanks @daviesgeek

**Comment by daviesgeek** [comment]
No problem! Since that seems to solve your issue, I'm going to go ahead and close this. Feel free to re-open if necessary!
