### ISSUE TITLE
AngularJS 1.3.x

### ISSUE THREAD

**Issue by Roycohen** [mgonto/restangular#1154]
Hi Guys,

Does Restangular is supported in AngularJS 1.3.x?
Is there a plan to support it?

**Comment by diego-vieira** [comment]
Working fine for me with 1.3.15.

**Comment by piotrd** [comment]
We're using Restangular with Angular 1.3.15 as well and all seems to work just fine. We'll see how it goes with 1.4 soon...

**Comment by Roycohen** [comment]
Thanks Guys.
I checked it and it worked.
Bit occurred that something works Out Of The Box.
