### ISSUE TITLE
Question: How to add query params in right way in .getList()?

### ISSUE THREAD

**Issue by daruwanov** [mgonto/restangular#1158]
Hi. I am trying to make get request using .getList();
and want send query params in next way `/?filter['limit']=20&filter['since']=2015-05-12` etc.

I try different ways to make it work... Just for now next example work for me.
```
var qParams = [];
        qParams['filter[limit]'] = 20;
        qParams['filter[since]'] = '2015-05-12';

.getList(
          qParams
        ).then(....);
```
Are there any other way to build data object? 

P.S Sorry for my bad English.

**Comment by bostrom** [comment]
How about
```
.getList({
  filter: {
    limit: 20,
    since: '2015-05-12'
  }
}).then(...);
```
or
```
.getList({
  'filter[]': [
    {limit: 20},
    {since: '2015-05-12'}
  ]
}).then(...);
```
depending on how your endpoint parses the parameters.

**Comment by daruwanov** [comment]
@bostrom Thanks, I will try this ASAP. First case i tried myself, but it comes to server as one string. I mean all params as one string. I will try second case.

**Comment by mintuhouse** [comment]
@daruwanov can you help me with how you finally solved the problem? Even the second option isn't working for me.
