### ISSUE TITLE
Example in docs could be improved

### ISSUE THREAD

**Issue by piotrd** [mgonto/restangular#1160]
Maybe it only my case, but the example shown here https://github.com/mgonto/restangular#removing-an-element-from-a-collection-keeping-the-collection-restangularized seems to be invalid. Specifically the line

``` js
var index = $scope.users.indexOf(userWithId);
```

would always return `-1`, because collection of object cannot be searched (using regular `indexOf`) by object property. I ended up with using lodash for this purpose:

``` js
var index = _.findIndex($rootScope.currentUser.photos, 'id', $scope.photo.id)
```

It would be worth to update the docs with this, unless I'm missing something?

**Comment by bostrom** [comment]
The example provided should work properly. If it doesn't, please provide some code (Plunker) to reproduce the problem, thanks!
