### ISSUE TITLE
Restangular dist files still identify as @version 1.4.0 ?!?

### ISSUE THREAD

**Issue by danielyona** [mgonto/restangular#1185]
Hello,

I am testing Restangular 1.5.1 on my apps, (and comparing performance etc to 1.4.0) and I notice that the @version is 1.4.0 (even though there is a more modern date)... This is very confusing... can it be fixed?

**Comment by Fost** [comment]
Yes, its very good qs. When it will be fix?

**Comment by enapupe** [comment]
I did open an issue 2 months ago about this (https://github.com/mgonto/restangular/issues/1109) and just lost another 10 minutes trying to understand what was going on with bower... until I figured (again!!) that the dist file is wrong :-1:

**Comment by wry791** [comment]
+1

**Comment by Fost** [comment]
anyone ? when plans distrib patch with this fix ?

**Comment by enapupe** [comment]
There's not much to do. Bower only updates when a release is performed. I
don't think they will perform a release just because the version number.
Next release should fix this.

**Comment by ConcurrentHashMap** [comment]
This is now fixed. Thanks for your contribution!
