### ISSUE TITLE
What is the roadmap for Restangular2 with Angular2?

### ISSUE THREAD

**Issue by tapas4java** [mgonto/restangular#1202]
Hi @mgonto ,

We all love Restangular. It looks like Restangular2 branch is idle since long time. What is the road map and tentative ETA for Restangular2 release?

**Comment by huei90** [comment]
Looks like if Restangular2 exist, it will be totally different with the Restangular....

**Comment by tapas4java** [comment]
There is a `2.0-wip` branch for Restangular2. But last update was on Oct 16, 2014.

**Comment by oesah** [comment]
Would be amazing, if restangular2 follows the angular2 release quickly! I am waiting for it.

**Comment by Jacke** [comment]
Not sure that dev for 2.0 will be fast, so for now we can use https://github.com/humana-fragilitas/ES6-Rest-Client as standalone thin rest client.

**Comment by KKrisu** [comment]
There is new project on the horizon for A2
https://github.com/2muchcoffeecom/ng2-restangular

**Comment by 2muchcoffeecom** [comment]
Thanks for posting it @KKrisu We couldn't do that earlier because we were preparing to use observables instead of promises. Now it's in beta. Has all needed tests, and we're using it on 2 our projects in production. You can install it though npm too.

**Comment by bostrom** [comment]
Also see #1318
