### ISSUE TITLE
Remove underscore/lodash dependency

### ISSUE THREAD

**Issue by pstoica** [mgonto/restangular#121]
This might just be a personal preference, but I don't feel like it makes sense to require underscore/lodash for this library, especially when a lot of the functions already have Angular or jQuery alternatives. The fewer external libraries needed to get up and running, the better, and I just don't have a pressing need for those libraries in my apps.

I'd be glad to help rewrite the necessary bits if you're okay with moving away from this dependency.

**Comment by niemyjski** [comment]
+1

**Comment by niemyjski** [comment]
Will you be using lodash for 2.0?

**Comment by bernardolm** [comment]
I do not like the idea of having an implicit dependence on Loadsh in Restagnular too.

This brings me problems when I want to use other libraries as Lazy.js, which for some functionality have better performance. And if in my project I just need these features that has better performance, I need to be required to have the problems of conflicts? Why that? Why force the use of extra library is the objective of the main library is not the same dependency library? Open source is not freedom? Restangular is not open source?

PS: I use Restangular in almost all my projects with angularjs and HTTP requests and I love to do this to be easy with Restangular! Thanks @jdalton.

**Comment by jdalton** [comment]
lodash v3 supports lazy evaluation btw.

**Comment by evanjmg** [comment]
+1
