### ISSUE TITLE
Time before pull request accepted ?

### ISSUE THREAD

**Issue by Nihaux** [mgonto/restangular#1218]
There seems to be a lot of PR waiting, how can we help speed up the process ?
(https://github.com/mgonto/restangular/pull/1184 -- made mid june)

**Comment by kevinrenskers** [comment]
Pretty sure @mgonto gave up on Restangular :(

**Comment by daviesgeek** [comment]
@pedromarce @ConcurrentHashMap @hartz89 and myself have been trying to maintain the repo since #1319
