### ISSUE TITLE
Can't access another web project by using restangular

### ISSUE THREAD

**Issue by amethyst82** [mgonto/restangular#1219]
When I try to access a restful API in another web project, occurred this problem:
XMLHttpRequest cannot load http://127.0.0.1:8080/PricingCenter/app/#/v2/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.

**Comment by ericcumbee** [comment]
This is not a Restangular Issue. I assume you are using Ionic, I ran into the same issue. You either need to properly configure CORS on your web service, or use the ionic proxy.

http://blog.ionic.io/handling-cors-issues-in-ionic/

**Comment by amethyst82** [comment]
actually, I use chrome without security model, this problem was then resolved :)
