### ISSUE TITLE
Breaks Angular Material

### ISSUE THREAD

**Issue by zwhitchcox** [mgonto/restangular#1222]
Right now, including restangular is breaking angular material, as you can see by this plnkr

http://plnkr.co/edit/UWZRHucppXLmz8nMaF5H?p=preview

It appears that Restangular is removing the classes from the input elements, although I don't know why.

**Comment by marcoriesco** [comment]
wrong, wrong code.
i update u code, test it:
http://plnkr.co/edit/pBgLi2ynpIGFbC6Dr8X0?p=preview

**Comment by dmackerman** [comment]
We're using the 2 libraries just fine.

**Comment by zwhitchcox** [comment]
That was my mistake.
