### ISSUE TITLE
Lodash no longer works as a dependency, Underscore is required.

### ISSUE THREAD

**Issue by Routhinator** [mgonto/restangular#1225]
TypeError: _.contains is not a function

Lodash does not have a .contains() function. I've searched through the code. Underscore does, however Lodash, if it had one, has removed it. As of right now, installing Restangular today will only work with Underscore.js

Docs should be updated, unless you want to go the route of adding support for the new functions in lodash.js

**Comment by mgonto** [comment]
Hey,

It does exist: https://lodash.com/docs#includes

It's an alias, see alias section.

Cheers!

**Comment by Routhinator** [comment]
TypeError: _.contains is not a function
    at Object.Configurer.init.config.isSafe (https://dev.amateurwriting.net/static/libraries/angular/restangular.js:21:16)

Restangular does not work with lodash. Check the error. Lodash is loaded and accessible, Restangular can see that, however restangular is unable to find the contains function. It's only working with Underscore.js.

**Comment by Routhinator** [comment]
In the newest release of lodash, there is no contains:

https://raw.githubusercontent.com/lodash/lodash/master/lodash.js

**Comment by jaydiablo** [comment]
@Routhinator The last tagged version of lodash (3.10.1) does have the "contains" alias:

https://github.com/lodash/lodash/blob/3.10.1/lodash.js#L12065

master branch right now is 4.0.0-pre.  The "contains" alias is still listed in the docs: https://github.com/lodash/lodash/tree/master/doc#collection but yes, the alias doesn't exist in lodash.js (or dist). It looks like they have removal of aliases on the roadmap:  https://github.com/lodash/lodash/wiki/Roadmap

Some discussion about alias removal: https://github.com/lodash/lodash/pull/1407#issuecomment-134213932

I think with 4.0.0 lodash is drifting away from underscore compatibility, so it may be difficult for projects to support both, unless a compatibility library is put in-between.  Possible to pin your lodash dependency to latest 3.x release?

**Comment by Vixxd** [comment]
Literally just installed Restangular and on my very first 'get()' call I get:
TypeError: _.contains is not a function

Lodash in my bower_components folder is listed as lodash v4.0.0 so I guess I will have to roll that back to an earlier version? However whenever I run 'bower update' now I'll have to exclude this somehow.

**Comment by jaydiablo** [comment]
@Vixxd you should be able to pin your lodash version to 3.x in your bower.json file like so:

>"lodash": "~3.0",

`bower update` should obey that and won't install > 3.x

**Comment by preston** [comment]
I switched over to underscore just for Restangular. Not what I want to do, but avoids indefinitely pinning to an old lodash version. :-/

**Comment by bourgeois247** [comment]
as @mgonto [the creator of Restangular] said, it exists under the alias "_.includes" https://lodash.com/docs#includes.

So what I did was, immediately after including the Lodash library, I set _.contains = _.includes just before I included the Restangular library. If you are using Browserify for your bundling needs, you still need to set Lodash globally on the window object for Restangular to have access, after which you can set _.contains = _.includes.

Hope that helps someone save a minute or 2,
cheers.

**Comment by fecosnippets** [comment]
Yes i also solved it with a one liner in my (few but useful) global functions file.

_.contains = _.includes;

Thanks @bourgeois247

**Comment by zanettin** [comment]
@mgonto
would be great, if you could add the online liner from @bourgeois247 to you scripts. just added it on dist/restangular.js on line 8 and everything looks great so far. thanks a lot for all your great work on this project!

**Comment by ackimwilliams** [comment]
I second @zanettin's suggestion.  Restangular is broken and unusable at this point.  Time to fork :(

**Comment by preston** [comment]
@mgonto Just curious if you're still interested in maintaining Restangular? Sounds like you might have some volunteers on this thread if not! Awesome work man.. :smile:

**Comment by mgonto** [comment]
Hey @preston, unfortunately, I'm not mantaining this anymore, I'm actively looking for people that want to mantain this so whoever wants to do it, I'm 100% years :D

**Comment by preston** [comment]
I wouldn't be a good choice, but there are a ton of existing forks. @elnygren / @R-Kurbatovvakoms / @nfntynl any takers?

**Comment by YassineFadhlaoui** [comment]
you can solve this issue by adding this script after including lodash : 
```
<script>
	 _.contains = _.includes;
	</script>
```
or you can browse the restangular.js file and change _.contains by _.includes
