### ISSUE TITLE
Restangular.all().post() Sending a OPTIONS request

### ISSUE THREAD

**Issue by kauegimenes** [mgonto/restangular#1226]
Hello, after implementing the restangular.all().post() and checking the Network tab from web developer tools there is only one `OPTIONS` call. 

I am doing something wrong?

Response Headers from my API:
````
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Accept, X-Requested-With
Access-Control-Allow-Methods:GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin:*
Allow:POST,GET,OPTIONS,PUT
````

**Comment by sutkovoy** [comment]
Maybe CORS ?

**Comment by kauegimenes** [comment]
Yeah, i just included the cors npm module and everything worked:)

**Comment by loverzpark** [comment]
@kauegimenes  How did u mentioned it ??
