### ISSUE TITLE
Adding restangular as a dependency to AngularJS 1.4.5 app $injector:modulerr error

### ISSUE THREAD

**Issue by maangulo12** [mgonto/restangular#1229]
I am trying to add restangular as a dependency to my AngularJS app. I am using AngularJS version 1.4.5. I have included the restangular script on my html page.

<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/restangular/1.3.1/restangular.min.js"></script>

This is basically what I am trying to do:

angular.module('app', ['restangular']);

This is the error I get:

Error: $injector:modulerr
Module Error

Failed to instantiate module app due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=r...)
    at Error (native)
    at http://localhost:5555/vendor/angular-1.4.5/angular.min.js:6:416
    at http://localhost:5555/vendor/angular-1.4.5/angular.min.js:38:98
    at n (http://localhost:5555/vendor/angular-1.4.5/angular.min.js:7:322)
    at g (http://localhost:5555/vendor/angular-1.4.5/angular.min.js:37:180)
    at http://localhost:5555/vendor/angular-1.4.5/angular.min.js:37:349
    at n (http://localhost:5555/vendor/angular-1.4.5/angular.min.js:7:322)
    at g (http://localhost:5555/vendor/angular-1.4.5/angular.min.js:37:180)
    at eb (http://localhost:5555/vendor/angular-1.4.5/angular.min.js:40:435)
    at d (http://localhost:5555/vendor/angular-1.4.5/angular.min.js:19:381

**Comment by JFSolorzano** [comment]
Why did you close the error? i'm having same problem, did u resolved it?

**Comment by maangulo12** [comment]
I resolved it. Make sure to add underscore.js to your project. Lodash.js did not work for me.

**Comment by vinhboy** [comment]
:+1:

**Comment by wahengchang** [comment]
it spent me like an hour to fix the problem:
add lodash.js before restangular.js in the header of index.html

<script src="bower_components/angular/angular.min.js"></script>
<script src="bower_components/lodash/dist/lodash.js"></script>
<script src="bower_components/restangular/dist/restangular.js"></script>
