### ISSUE TITLE
Restangular doesn't load to my app module

### ISSUE THREAD

**Issue by JFSolorzano** [mgonto/restangular#1237]
I'm unable to load restangular to my app module, i'm working with the latest version of restangular (1.5.1) but actually it says 1.4.0 in the doc of the file:

```
/**
 * Restful Resources service for AngularJS apps
 * @version v1.4.0 - 2015-04-03 * @link https://github.com/mgonto/restangular
 * @author Martin Gontovnikas <martin@gon.to>
 * @license MIT License, http://www.opensource.org/licenses/MIT
 */
```

I'm using Angular 1.4.5, and ui-router, lodash 3.10.1.
Here's the error:

```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=app&p1=Error%3A%20%…ol%2Fsrc%2Fclient%2Fcomponents%2Fangular%2Fangular-1.4.5.min.js%3A19%3A381)
```

I'm sure the .js file is loaded, and here's where i call restangular:

``` javascript
(function () {

    'use strict';

    angular.module('app.core', [
        'restangular', 'ui.router', 'ui.bootstrap'
      ]);

})();
```

**UPDATE 1**:
I discovered that restangular doesn't work with lodash, but it works with underscore... now my question is why?

I was using latest lodash version (3.10.1).

**Comment by pihomeserver** [comment]
@JFSolorzano for my project, works with lodash. Maybe the order of the modules ?

**Comment by piotrd** [comment]
@pihomeserver can you confirm that it works with the latest version of lodash (3.10.1)?

**Comment by pihomeserver** [comment]
@piotrd Yes, that's the version installed
