### ISSUE TITLE
Version 1.5.1 broke .post() method

### ISSUE THREAD

**Issue by jaesung2061** [mgonto/restangular#1244]
Including .customPOST(). It seems everything works fine except anything that involves posts.

**Comment by cleechtech** [comment]
Is this repo maintained?

**Comment by daviesgeek** [comment]
@jaesung2061 Not sure why you closed this. Did you resolve the issue?

@connor11528 It's in the process of being switched over from the main author. See #1319

**Comment by jaesung2061** [comment]
I closed it because I forgot the reason I opened it for. I guess that shows how little information I provided when I opened the issue. Would you like for me to reopen it?

**Comment by daviesgeek** [comment]
LOL. Well, if you don't know why you opened it, let's keep it closed, unless you can remember why you opened it :)
