### ISSUE TITLE
Restangular doesn't accept JSON response containing empty string or number 0

### ISSUE THREAD

**Issue by cm0s** [mgonto/restangular#1257]
If you have a Rest API (ex. http://server.com/api/data) returning the following value : 

``` json
""
```

or 

``` json
0
```

when calling :

``` javascript
Restangular.one('data').get().then(function(data){
   // data = undefined instead of "" or 0
   console.log(data)
});
```

If we try to get the same JSON using angularJS `$http`, the results are not undefined, but `""` and `0`. Restangular should do the same.

Here is a plunker showing the bug : http://plnkr.co/edit/yE9o3iPL0ZVa87gNuzGG
   Open your console and run the plunker.

Apparently the problem is due to a if condition in the `okCallback` function located in the `elemFunction` function.

Here is the excerpt of the code : 

``` javascript
var okCallback = function(response) {
          var resData = response.data;
          var fullParams = response.config.params;
          var elem = parseResponse(resData, operation, route, fetchUrl, response, deferred);
          if (elem) {  // <-- this test is causing the bug
             ...
```

To solve the problem the `if(elem)` test should be replaced by : 

``` javascript
if (elem || elem === 0 || elem === '') {
```

or

``` javascript
if (elem !== undefined && elem !== null) {
```

**Comment by dmackerman** [comment]
I'm just curious about the use case as to why a server would return `""` or `0`, versus those 2 other values. Your fix makes sense, just curious about the why. :smile:

**Comment by cm0s** [comment]
I probably didn't phrase it well, the API returned value is not switching between number and string :smile:. To rephrase it, it will be better to say : If you have a REST API returning 0 or another REST API returning "". The following problem will occur [...]
