### ISSUE TITLE
POST, missing parameters

### ISSUE THREAD

**Issue by hervethouzard** [mgonto/restangular#1276]
Hello,

First thanks for this library, it's a real time saver and a pleasure to work with.

Secondly, I have a route to modify an existing user comment defined like this:
POST /user/{user_id}/comment/{comment_id}

And I use it like this:

1) Get the user's comment:
$scope.comment = Restangular.one('user', $scope.user_id).one('comment', $scope.comment_id).get().then()....

2) Modify comment:
$scope.comment.post($scope.comment_id).then()...

When $scope.user_id equals 0, the used route is:
POST /user/{user_id}/comment

And it finishes with a 404 error as the {comment_id} is missing.

By modifying the code like this, I just added .toString(), it runs as expected:
$scope.comment.post($scope.comment_id.toString()).then()...

POST /user/{user_id}/comment/0

In the database, we have records starting at 0...
Is this a normal behaviour, a bug or me not using the library as required?

Bye,
Hervé

**Comment by hervethouzard** [comment]
There is a mistake in my report, instead of:
When $scope.user_id equals 0, the used route is:

You should read:
When $scope.comment_id equals 0, the used route is:

**Comment by daviesgeek** [comment]
Can you provide a working example on Plunker please?

**Comment by hervethouzard** [comment]
Hello,

Sorry I can't. I'm not working on this project since several monthes.

**Comment by daviesgeek** [comment]
Okay I'm going to close this for now. Feel free to re-open if there's still an issue.
