### ISSUE TITLE
propose mock API for restangular

### ISSUE THREAD

**Issue by loganfreeman** [mgonto/restangular#1278]
It would be convenient if restangular supports creating mock easily.

mock just $httpBackend

$httpBackend has methods: whenPost, whenGet etc. and they returns an object with respond method.

If we can create rest client easily, we should be able to create mock easily also.

for example:

restangularBackend.getList().respond(function(method, url, data, headers, params){

})

**Comment by daviesgeek** [comment]
This really doesn't fall within the scope of Restangular. From the description of the repository:

> service to handle Rest API Restful Resources properly and easily

Mocking backends really doesn't fall under that description.
