### ISSUE TITLE
Getting header response

### ISSUE THREAD

**Issue by baptadn** [mgonto/restangular#128]
There is a way to get header response from `then()` method like $http angularjs method ? I create an item with Restangular.post() and my API return the url of the created resource in `Location header`, and I would like to get this new item. Thanks.

**Comment by Ouadie** [comment]
Same issue with `Restangular.setFullResponse(true);` I can't get all the **headers** from the response.

Here is my config:
```javascript
angular.module('MyWebsite')
 .factory('MyWebsiteApiRestangular', function (Restangular, transformersFactory, store) {
 	return Restangular.withConfig(function(RestangularConfigurer) {
		RestangularConfigurer.setBaseUrl('http://127.0.0.1/MyWebsite'); 
 		RestangularConfigurer.setDefaultHeaders({Authorization: 'Bearer ' + store.get('token')});
		
		RestangularConfigurer.setFullResponse(true);

		RestangularConfigurer.addResponseInterceptor(function(data, operation, what, url, response, deferred) {
			var token = response.headers("authorization");
			// ...
		});

		// ...
```


And here is the response of my web server:
**OPTIONS http://127.0.0.1/MyWebsite/item/1**
>access-control-allow-methods: GET, POST, PUT, DELETE
>access-control-allow-headers: ACCEPT, AUTHORIZATION
>access-control-allow-origin: http://127.0.0.1/MyWebsite


**GET http://127.0.0.1/MyWebsite/item/1**
>Authorization: Bearer ThisIsMyToken
>Access-Control-Allow-Origin: http://localhost:9000
