### ISSUE TITLE
Unable to get id after save()

### ISSUE THREAD

**Issue by ov3rhear** [mgonto/restangular#1281]
Hello,

I'm using Restangular to connect to a default mongodb server.
I have this set up:

RestangularProvider.setRestangularFields({
		id: "_id.$oid"
	});

RestangularProvider.addResponseInterceptor(function (data, operation, what, url, response, deferred) {
		var extractedData;
        // look for getList operations
        if (operation === "getList") {
            // the actual entities are in the _embedded section
            extractedData = data._embedded['rh:doc'];
        } else {
            extractedData = data;
        }
        return extractedData;
	});
And I'm doing this:

var myObj = Restangular.one("myObj");
myObj.save();

And my object is saved to mongodb, with _id and _etag fields generated. But I see no way of obtaining his new id in my code. 
I have tried with:

var result = myObject.save().then(function(res){
});

And I get a Promise as "result" return value, and an undefined object in "res".
I have tried searching for this in several places, it seems not many people are using the .save() method. 

Am I doing something wrong, or is there no way to retreive the id automatically?
I see I can retrieve the id by manually parsing the response.headers().location value inside the interceptor, but is this really my job to do? Isn't restangular supposed to fetch it for me when I do save()?

**Comment by daviesgeek** [comment]
Does the server return anything? If not, that would be why `res` is undefined. The response from the `save()` method doesn't change anything on your original object (`myObject` in this case). If you need the id, you'll have to make sure the server is actually returning it, so that you can use it in your Restangularized object.

```js
var myObject = Restangular.one("myObj")
// Change stuff on the object
myObject.data = {name: "daviesgeek", enabled: false}
myObject.save().then(function(response) { 

  // Set the new id
  myObject._id.$oid = response._id.$oid
})
```

**Comment by daviesgeek** [comment]
I'm going to close this for now. Feel free to re-open if there's still an issue.
