### ISSUE TITLE
Restangular.service does not have .get() method.

### ISSUE THREAD

**Issue by iqbal-admedo** [mgonto/restangular#1290]
There is an issue:
```
var test1 = Restangular.all('user').get(1).then(function(res) {
    console.log('test1', res);
}); // Does not work says .get() is not defined

var test2 = Restangular.service('user').get(1).then(function(res2) {
    console.log('test2', res);
}); // works fine
```

Am I doing anything wrong?

**Comment by aikrez** [comment]
In test1 Restangular.all('user') is a promise and this doesnt have a get method

**Comment by ivogallego** [comment]
With 1.5.2 version it also fails with the service

**Comment by daviesgeek** [comment]
Seems to work fine for me. Can you provide a Plunker if this is still an issue?

**Comment by WolfieZero** [comment]
I found the exact same thing so I resorted to using `all()` rather than `service()`. Seems to be working as expected at the moment.

My original code is as follows.

    app.factory('Todo', [
        'Restangular', (Restangular) => {
            var service = Restangular.all('todo');
            return service;
        }
    ]);
    
    // In the controller
    Todo.get('all');

**Comment by deddu** [comment]
see https://github.com/mgonto/restangular/pull/1341/files
Apparently the readme is wrong, correct syntax should be `YourService.one('XYZ').get()`.

**Comment by daviesgeek** [comment]
@deddu You're right. The docs are wrong here. That PR has just been merged. I'm not sure what code I was testing when I originally commented (shame on me for not providing a code example!). This should work now as the (updated) docs say.
