### ISSUE TITLE
How to post multiple parameters in REST post api

### ISSUE THREAD

**Issue by sanketwankhade01** [mgonto/restangular#1293]
we trying to post multiple parameters using rest call
var data1=[1, 3];
var data2=[4, 2];

var params = {'param1':data1, 'param2':data2};
var url="..."; //api url
	Restangular.all(url).post(params).then(function (saved_id) {
			alert("done");
	},function(response) {
			alert("failed");
	});

This api call get fails, while same api having url appended with query parameter succeed. 

url with  query param 
    url?param1=data1&param2=data2

Also this api works fine for single parameter. How we can post multiple parameters without using query param.

**Comment by pedromarce** [comment]
When you are posting with parameters they are send as part of the body request, as it where they are expected (opposite of a get where they would go as query string parameters). 
The api should be parsing the body to retrieve post values, I can't see a reason why a post should add query string parameters at all.

**Comment by ConcurrentHashMap** [comment]
@sanketwankhade01 Please have a look at the correct [function signature](https://github.com/mgonto/restangular#collection-methods) for the post function. Parameters that should be send as parameters are optional and should be passed as second parameter. The first parameter should be the object that should be posted.

**Comment by pedromarce** [comment]
@ConcurrentHashMap you are absolutely right, I missed it, it is indeed possible, not sure is a good practice though:)
