### ISSUE TITLE
Configuring the id property on restangular nested resource

### ISSUE THREAD

**Issue by dandezmirean** [mgonto/restangular#1297]
Is it possible to configure the id on a nested resource?

Configuring this property on a resource is easy, either by having a custom Restangular object for each resource and using the 'withConfig' function, or by using the 'extendModel' function to set the value on the id property of the model. 

I've tried to do this for a nested resource, but can't get a hold of it. 
Both the parent and the nested resource have custom id properties. 

I can't use the 'getIdFromElem' function from the global configuration object because I use Restangular to map many resources and the resource names do not comply the same naming convention. It's important I mention that I cannot change the naming of the resources, because the backend is a third-party.

For example, I have a resource called 'users' with an id property called 'userId'. It's nested resource is called 'user-notifications' with an id property called 'userNotificationId'.

If i create a custom resource with configuration I do something like:

        var restangular = Restangular.withConfig(function (Configurer) {
            Configurer.setRestangularFields({ id: 'userId' });
        });

        restangular.one('users', userId).all('user-notifications').getList().then(function (userNotifications) {
            userNotifications[0].message = 'New Value';

            //I expect this call to be something like /api/v1/users/'userId'/user-messages/'userMessageId'
            userNotifications[0].put();
            //But instead it's /api/v1/users/'userId'/user-messages/'userId'
        });

How could I configure the id properties of both resources?

**Comment by ortegaguillermo** [comment]
Same situation, @dandezmirean have you solved how to do it?

**Comment by raphox** [comment]
Maybe this help you https://github.com/mgonto/restangular#setrestangularfields

**Comment by daviesgeek** [comment]
See [the docs](https://github.com/mgonto/restangular#setrestangularfields):


```js
app.config(function(RestangularProvider) {
  RestangularProvider.setRestangularFields({id: 'id'})
})
```

If this is an issue, please, feel free to re-open, but I'll close this for now, since it's been _so_ hard managing issues for this project as of late.
