### ISSUE TITLE
restangular - discontinued ?

### ISSUE THREAD

**Issue by bz123** [mgonto/restangular#1305]
hey,

seems like last commit was by grabbou committed on Jun 5, 2015 

Is restangular discontinued? 

If yes at least let us know.

Thanks

**Comment by amatiasq** [comment]
Same question here, it's dependencies (angular, lodash) are getting upgrades and restangular is getting us stuck behind :\

**Comment by migajek** [comment]
+1 
We all would like to know if Restangular is a good choice for new projects?

**Comment by WnP** [comment]
+1

**Comment by luukholleman** [comment]
I think this reply time says enough :/

**Comment by sikorsky555** [comment]
I emailed mgonto to to get a feel for what was happening. He is not actively maintaining it and it would appear nobody else is as well. He asked if I would like to, but I don't know about that.

**Comment by sarunast** [comment]
You are better using something like this: https://github.com/Swimlane/angular-model-factory

**Comment by ConcurrentHashMap** [comment]
Hey @sikorsky555 - thanks for your input to contact @mgonto. Please have a look onto issue #1319, where @mgonto writes about the future of the project.
