### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by daviesgeek** [mgonto/restangular#1306]
I was trying to do some work on fixing a bug I'd found, but couldn't run the tests locally.

Here's the error I get:

```
Fatal error: Unable to find local grunt.                                                            
If you're seeing this message, either a Gruntfile wasn't found or grunt                             
hasn't been installed locally to your project. For more information about                           
installing and configuring grunt, please see the Getting Started guide: 
http://gruntjs.com/getting-started 
```

I'm not sure why this is happening, as there *is* a Gruntfile in the folder. Any ideas? It seems like some of the npm dependencies are out of date and this might be the cause of some of the issues…

**Comment by ConcurrentHashMap** [comment]
This should also be resolved by merging #1314.

**Comment by ConcurrentHashMap** [comment]
Hey @daviesgeek - this should be fixed by now. grunt was added as a dependency inside the package.json

**Comment by daviesgeek** [comment]
Great thank you!

**Comment by daviesgeek** [comment]
And #1315 completely fixed the reason why I wanted to run tests…
