### ISSUE TITLE
Format error response

### ISSUE THREAD

**Issue by SamanthaAdrichem** [mgonto/restangular#1310]
Is there a way to format the error response using for example the errorInterceptor, just like a responseInterseptor allows you to format the normal Response?

**Comment by daviesgeek** [comment]
[setErrorInterceptor](https://github.com/mgonto/restangular#seterrorinterceptor) will work:

```js
RestangularProvider.setErrorInterceptor(function (response, deferred, responseHandler) {
  response.data = {error: "Modified the response"} // Change the response

  return false // Continue on or return true if you don't want it to continue

})
```
