### ISSUE TITLE
Option to not encode special characters

### ISSUE THREAD

**Issue by codespaced** [mgonto/restangular#1312]
The API I want to interact with uses ^, ], and [ to modify searches. I can't seem to find a way to not encode those to %5E etc.

**Comment by pedromarce** [comment]
Hi @codespaced, they are not valid [URL characters](http://stackoverflow.com/questions/40568/are-square-brackets-permitted-in-urls), so I think it should the API who should decode them, not sure there is a case to add this option. I will close the issue, but if you can make a case, feel free to reopen it.

**Comment by davidstellini** [comment]
Angular itself provides the option of overriding `QueryEncoder` in the URLSearchParams with one of your own. I think this functionality should be provided - rephrasing the original question - it would be better if the library allowed us some way of providing our own query encoder like angular does.
