### ISSUE TITLE
_.contains is not there anymore

### ISSUE THREAD

**Issue by AmrAbdulrahman** [mgonto/restangular#1314]
Restangular depends on lodash >= 1.3.0
But lodash#4.3.0 has _.contains removed,
this raises TypeError exceptions.

**Comment by bsonntag** [comment]
Please fix this.

**Comment by aloker** [comment]
+1, I just ran into this issue.

**Comment by AmrAbdulrahman** [comment]
there's already an open PR for this: https://github.com/mgonto/restangular/pull/1315

**Comment by DioNNiS** [comment]
+1

**Comment by merqlove** [comment]
same here

**Comment by ConcurrentHashMap** [comment]
Hi @AmrAbdulrahman, thanks for opening up an issue on this. Good news - the issue is finally fixed with the recently released v1.5.2 that addressed this issue. I will close this issue thread now.

Thanks for all of your contributions!
