### ISSUE TITLE
no more plans for Restangular2?

### ISSUE THREAD

**Issue by stevermeister** [mgonto/restangular#1318]
@mgonto ,
Thank you very much  for such a beautiful library that we are using for a lot of our projects!

As far as I understand there is no chance to see Restangular2 version and HAL implementation nearest future?

**Comment by besuhoff** [comment]
:+1:

**Comment by daviesgeek** [comment]
+1

**Comment by DioNNiS** [comment]
+1

**Comment by essivision** [comment]
+1

**Comment by Abdelaziz-Khabthani** [comment]
+1

**Comment by kelvinwang139** [comment]
Thanks for this great lib while I have a question that I see: 
"Restangular supports all angular versions including 1.0.X, 1.1.X and 1.2.X (1.2.4 being the current at the time)"
Does Restangular 1.x support latest angular 1.5.x?

**Comment by tairezzzz** [comment]
Hey @mgonto, have you any plans on restangular 2? I really needed good solution for interaction with RESTful services and I have performed some on the projects where I've been using Angular 2. Are you interested on cooperation on such a matter?

**Comment by 2muchcoffeecom** [comment]
Hey guys, check out our implementation of restangular logic there https://github.com/2muchcoffeecom/ng2-restangular You can use observables or promises.

**Comment by bostrom** [comment]
@2muchcoffeecom Great stuff. As @mgonto abandoned Restangular a couple of years back, there aren't any resources at the moment to develop this project into an angular 2+ compatible library. With your contributions in ng2-restangular, I think this project will stay focused on compatibility with Angular 1 only. 

Is ng2-restangular mature enough so I could add a link to it from this project's README?

**Comment by 2muchcoffeecom** [comment]
@bostrom Sure, it's mature enough. We're focusing on Angular 2+ projects right now, and we'll be maintaining this one for long time. Actually, @mgonto already has promised to add it via email 8-) but maybe forgot to do that.

**Comment by bostrom** [comment]
@2muchcoffeecom Hah, okay I'll add it then. Super!

**Comment by 2muchcoffeecom** [comment]
@bostrom Great, thanks :)

**Comment by RodolfoSilva** [comment]
Hello guys, I'm rewriting the Restangular to work with Angular 2...

https://github.com/RodolfoSilva/rs-restangular
