### ISSUE TITLE
Feature request:  Make compatible with Lo-Dash 4.5.0 (and up)

### ISSUE THREAD

**Issue by rbatllet** [mgonto/restangular#1324]
Is there a short-term upgrade to the latest version of Lo-Dash 4.5.0 (or remove that dependency)? 

We can't upgrade because it seems Restangular is not fully compatible with Lo-Dash 4.5.0, only with 3.10.1

**Comment by nforysinski** [comment]
This was resolved in Restangular 1.5.2 - please update to that version for lo-dash 4.0+ support.

**Comment by daviesgeek** [comment]
Seems like this got resolved, so I'm going to close this for now. Feel free to re-open if there's still an issue.
