### ISSUE TITLE
Update bower.json on version 1.5.2 so lodash dependency be >=3.0.0

### ISSUE THREAD

**Issue by leosvelperez** [mgonto/restangular#1327]
When I updated to the 1.5.2 version the lodash dependency still was >=1.3.0 while it's no longer compatible with that.

**Comment by DioNNiS** [comment]
+1

**Comment by bingomanatee** [comment]
Lodash is now up to version 4

**Comment by bostrom** [comment]
Updated lodash version to ~4.17.0 in bower.json and package.json in e0b68a021ad9e4f7fc34d66cad4c24af1864ba18

@bingomanatee which methods do you consider deprecated in lodash version 4? I can't find any deprecation information.

**Comment by bingomanatee** [comment]
https://github.com/lodash/lodash/wiki/Deprecations

**Comment by bostrom** [comment]
These are the lodash methods used in the current version of Restangular:

```
_.bind
_.defaults
_.each
_.every
_.extend
_.find
_.has
_.includes
_.initial
_.isArray
_.isBoolean
_.isEmpty
_.isFunction
_.isNull
_.isNumber
_.isObject
_.isRegExp
_.isUndefined
_.keys
_.last
_.map
_.omit
_.pick
_.reduce
_.union
_.values
```
none of which are listed in the deprecation list:

```
_#run
_.all
_.any
_.backflow
_.callback
_.collect
_.compose
_.contains
_.detect
_.findWhere
_.first
_.foldl
_.foldr
_.include
_.indexBy
_.inject
_.invoke
_.methods
_.modArgs
_.object
_.padLeft
_.padRight
_.pairs
_.pluck
_.rest
_.restParam
_.select
_.sortByOrder
_.support
_.trimLeft
_.trimRight
_.trunc
_.unique
_.where
```

So everything should be ok.
