### ISSUE TITLE
Restangular stopped working?

### ISSUE THREAD

**Issue by cskiwi** [mgonto/restangular#1328]
Hi,

I'm reopening my project that I worked on last week, every thing worked great then, now I can't get anything working, so I have the following service:

    function userService($log, userModel, Restangular) {
        var service = Restangular.all("user");

        Restangular.extendModel("user", function (data) {
            $log.debug('extend', data);
            return userModel.create(data);
        });
        return service;
    }
    angular.module("app.services").service("userService", userService);

and in another service i have the following method:

    var isLoggedIn = function(){
        var def = $q.defer();
        userService.one('me').get().then(function(data) {
            if (!data || data === ""){
                def.reject();
            } else{
                $rootScope.user = data;
                def.resolve(data);
            }
        }, def.reject);
        return def.promise;
    };

so you would think that the the `$log.debug()` get's called upon running the `isLoggedIn()` function, but nope, and the data is empty that get's returned to the `one('me').get()...` function

When I look at the network tab in chorme, I see a correct api call being made to the user/me route

so Any Idea what might be going wrong?

**Comment by ConcurrentHashMap** [comment]
Did you do bower update? If so, did you also update lodash to a version >= 3.0?
Maybe it's a problem due to our update to make restangular compatible with the newest lodash that dropped compatibility with the older lodash 1.x versions.

**Comment by cskiwi** [comment]
Hi,

yea it was totally my fault, in the httpintercepter I returned  `data.data` instead of just normal `data`
