### ISSUE TITLE
Invalidating cache

### ISSUE THREAD

**Issue by calvinl** [mgonto/restangular#133]
I've got caching turned on, and it works great, but I want to have a refresh button to reload data retrieved from the server. I understand Restangular is using $http's caching abilities. How would I go about invalidating the cache with, for example, a refresh button on a particular page?

**Comment by kodermax** [comment]
This is working variant.
```javascript
(function(){
    "use strict";
        angular.module('restangular.cache',[]);
        angular.module('restangular.cache')
            .factory('HTTPCache', HTTPCache);
        HTTPCache.$inject = ['Restangular', '$cacheFactory'];
        function HTTPCache(Restangular, $cacheFactory) {
            var cache;
            cache = $cacheFactory('http');
            return Restangular.withConfig(function (RestangularConfigurer) {
                RestangularConfigurer.setDefaultHttpFields({cache: cache});
                Restangular.setResponseInterceptor(function(response, operation) {
                    if (operation === 'put' || operation === 'post' || operation === 'delete') {
                        cache.removeAll();
                    }
                    return response;
                });
            });
        }
})();
```

**Comment by c0debreaker** [comment]
I'm looking at the code given above. POST is normally not cached right? What I'd like to implement is remove cache for GET after a period of time like 15 mins. How can that be done?

**Comment by Clan-Utility** [comment]
I have used 'HTTPCache' to enable caching for Restangular

    var UserService = HTTPCache.service('user')

Everything is fine with UserService.getList().
But I have some problem with the following code

    var userList = UserService.getList().$object;
    userList[0].name = 'John';
    userList[0].put();

The last line will not invoke responseInterceptor defined in HTTPCache. Instead, it only invokes the default Restangular response interceptor if I put it in app.run()

    Restangular.setResponseInterceptor(...

Anyway to solve that?

**Comment by isometriq** [comment]
I got a cache expiring after 5 mins OR when specific operations happen
```
(function() {

angular
	.module('app.services')
	.factory('API', API);

function API(Restangular, $cacheFactory, $window) {

	var cache = $cacheFactory('http');
	var cacheTime = (new Date()).getTime();
	var cacheExpiration = 1000 * 60 * 5; // 5 min

	return Restangular.withConfig(function(RestangularConfigurer) {
		RestangularConfigurer
			.setDefaultHttpFields({cache:cache})
			
			.setResponseInterceptor(function(response, operation) {

				var currentTime = (new Date()).getTime();
				var cacheExpired = (currentTime - cacheTime) > cacheExpiration;

				if (cacheExpired || operation === 'put' || operation === 'post' || operation === 'delete') {
					cache.removeAll();
					cacheTime = (new Date()).getTime();
				}

				return response;
			});
	});
}

})();
```

**Comment by helloanoop** [comment]
Thanks @isometriq , Your solution works for me.
A couple of points for anybody referring this in the future.
1. Declare "cacheTime" inside the "Restangular.withConfig" call,
    This will ensure that the cacheTime is different for different factories that you might create out
    of the base API factory
2. Add operation === 'remove' to the if() check
