### ISSUE TITLE
404 On android but not on IOS and Browser 

### ISSUE THREAD

**Issue by qz2rg4** [mgonto/restangular#1331]
Hi 

404 on a get request but when I click on the link it resolves 
Restangular.one("/teams?nocache=true&descendants=TeamMember&where=teamMemberEmail.Contains('" + username + "')").get()

When I click on the 404 url it does resolve 
http://sub.mysite.com/teams?nocache=true&descendants=TeamMember&where=teamMemberEmail.Contains(%27johndoe@arcfyre.com%27)

**Comment by pedromarce** [comment]
I don't think it will be restangular related, but maybe just cross domain issues (long shot), check this [answer](http://stackoverflow.com/questions/14319624/cross-domain-ajax-works-in-all-but-android) in stackoverflow

**Comment by pedromarce** [comment]
Or something probably more appropiate, if you are using cordova to build your mobile apps, check this [one](http://stackoverflow.com/questions/29826971/ionic-requests-return-404-only-on-android-in-chrome-it-works-fine)

**Comment by qz2rg4** [comment]
Thanks. You were correct. What solved my problem is uninstalling and reinstalling from git
cordova plugin add https://github.com/apache/cordova-plugin-whitelist.git

**Comment by pedromarce** [comment]
Perfect, I will close the issue in that case.
