### ISSUE TITLE
Why decoupled service dosn't get triggered?

### ISSUE THREAD

**Issue by MtDalPizzol** [mgonto/restangular#1332]
I'm starting with Restangular and I need to write a decoupled service like the one described in https://github.com/mgonto/restangular#user-content-decoupled-restangular-service.

My goal is to do a single GET to "/layout/default".

```javascript
app.factory('Layout', ['Restangular', function Layout(Restangular) {
  return Restangular.service('layout');
}]);

app.config(['$stateProvider', function ($stateProvider) {
   $stateProvider.state('default', {
      // controller, controllesAs, template...
      resolve: {
         data: ['Layout', function resolveDefaultLayoutData (Layout) {
            console.log('resolveDefaultLayoutData()'); // Everything is fine here
            return Layout.get('default'); // Shoud do GET to "/layout/default" but
                                          // no requests are made and nothing gets loged on "console"
                                          // neither in "network" in the browser inspector tabs
         }]
      }
   })
}]);
```

I saw some issues mentioning that the ".get" method is missing, but in this case, the browser should throw a "has no property" exception... If this is a duplicate, I'm sorry.

**Comment by nbasov** [comment]
Following should work:
```
...
return Layout.one('default').get();
```

**Comment by daviesgeek** [comment]
@MtDalPizzol Did @nbasov 's example this work for you?

**Comment by MtDalPizzol** [comment]
@daviesgeek , I ended up just changing this:
```javascript
return Restangular.service('layout');
```
to this:
```javascript
return Restangular.all('layouts');
```

I don't know if this is actually a decoupled service, but it serves my needs, so...

**Comment by daviesgeek** [comment]
Okay that sounds good and should work. Since it seems to have solved your issue, I'll go ahead and close this. Feel free to re-open if necessary!
