### ISSUE TITLE
1.5.2 and NPMJS

### ISSUE THREAD

**Issue by lloy0076** [mgonto/restangular#1334]
Hi There,

Not quite sure if this is a "bug" but it seems that 1.5.2 hasn't gone up to NPMJS yet which means that lodash >= 3.10.X will probably cause the "_.contains" error.

I've downloaded 1.5.2 via "git clone" and rsynced it over what npm installs, but every time I update it gets overwritten by 1.5.1.

I don't know the fix for his one apart from the fact it's probably something to do with npmjs and the maintainer(s) here to bump the update.

Thanks,

DSL

**Comment by ConcurrentHashMap** [comment]
Hi @lloy0076,

I can't reproduce this problem.

```
npm init
npm install --save-dev restangular
```
leads to restangular 1.5.2 being installed.

May it be your package.json contains a fixed version number?

**Comment by lloy0076** [comment]
It seems it’s magically updated me to the latest version; probably a case of the various mirrors being stale.
