### ISSUE TITLE
How to bulk remove with Restangular.all('customer')

### ISSUE THREAD

**Issue by essivision** [mgonto/restangular#1335]
Hi

Thanks for Restangular. I want to use Restangular in service like this:

`var _customerService = Restangular.all('customer');`

and use this in all method like:
```
this.show = function(id) {
        // GET /api/customer/:id
        return _customerService.get(id);
    }
```
Now I want to remove multiple customer but in [#430](https://github.com/mgonto/restangular/issues/430) you recommend `Restangular.several` to do. 
How to remove several item without `Restangular.several` (use `Restangular.all`) to unified my code?

**Comment by daviesgeek** [comment]
Can you elaborate on this a little more? The code example you have only fetches one customer, which you can send a DELETE request by calling `remove()`. However, it sounds like you're trying to remove multiple customers at once? `Restangular.several` would be the Restangular method you'd call to remove multiple items. You could add this as a separate method, keeping your code clean and unified without being too repetitive.

```js
var route = 'customer',
    _customerService = Restangular.all(route);

this.show = function(id) {
  // GET /api/customer/:id
  return _customerService.get(id);
}

// Where `ids` is an array of integers
this.removeMultiple = function (ids) {
  return Restangular.several(route, ids).remove()
}
```

**Comment by essivision** [comment]
Only with `Restangular.several` I can call to remove multiple items?

**Comment by daviesgeek** [comment]
Yes.

`Restangular.several` makes a single DELETE request to the endpoint with multiple ids. It does not make multiple requests.

```js

// Makes a *single* DELETE request to "/customers/1,2,3,4"
Restangular.several('customers', [1,2,3,4]).remove()
```

**Comment by essivision** [comment]
Thanks

**Comment by daviesgeek** [comment]
Does that solve/answer your question?

**Comment by essivision** [comment]
OK Solved

**Comment by daviesgeek** [comment]
@ConcurrentHashMap or @pedromarce can one of you close this?
