### ISSUE TITLE
Documentation spelling error

### ISSUE THREAD

**Issue by portlandDeveloper** [mgonto/restangular#1336]
under "Configuring Restangular" section of the documentation, under the "setBaseUrl" heading, there is a sentence that reads:

"...The default baseUrl is an empty string which resolves to the same url that AngularJS is running, so you can also set an absolute url like http://api.example.com/api/v1 if you need do set another domain."

I think you meant:
"....The default baseUrl is an empty string which resolves to the same url that AngularJS is running, so you can also set an absolute url like http://api.example.com/api/v1 if you need **to** set another domain."

**Comment by daviesgeek** [comment]
Can you submit a PR with this fix?
