### ISSUE TITLE
RoutePrefix not working

### ISSUE THREAD

**Issue by cariquitanmac** [mgonto/restangular#1337]
Hi,

I have a web api controller with the following definition.
```
 [RoutePrefix("api/Account")]
    public class AccountAPIController : ApiController
    {
```

Back when I was using the '$http' services, I can call the API using the routeprefix like this : 
`$http.post(ngAuthSettings.apiServiceBaseUri + 'api/account/register', signUpData)`

But now i need to specify the full controller name in order for it to work
`Restangular.all('AccountAPI')`

Why is it that the routeprefix is not working when using restangular?

**Comment by cariquitanmac** [comment]
I think I found it. Its my careless mistake.

**Comment by ConcurrentHashMap** [comment]
:laughing: No problem, things like this happen. I guess you named your routes differently? BTW: Nice issue number!

**Comment by cariquitanmac** [comment]
@ConcurrentHashMap what is it about the issue number? :D
