### ISSUE TITLE
Send parameter with additional route

### ISSUE THREAD

**Issue by essivision** [mgonto/restangular#1339]
Hi 

It is possible to get `/api/v1/customer/search?query=test`
`Restangular.all('customer').getList("search",{query:test});`

**Comment by ConcurrentHashMap** [comment]
Hi @essivision, please have a look at the [documentation](https://github.com/mgonto/restangular#collection-methods).

`getList` expects only optional parameters and the first one would be the queryParams object then.

To "navigate" down to custom routes, use the `customGETLIST` function instead.
You could do the call to  `/api/v1/customer/search?query=test` like this:

```
Restangular.all('customer').customGETLIST("search",{query:test});
```

Hope this helps!

**Comment by essivision** [comment]
Okay Thanks

**Comment by daviesgeek** [comment]
I'm going to close this for now. Feel free to re-open if there's still an issue.
