### ISSUE TITLE
How to send real JSON object to server

### ISSUE THREAD

**Issue by essivision** [mgonto/restangular#1340]
Hi

I have a variable like this:
` $scope.task.gallery=[
             {"name": "XCB808tvXNpqXKqekA2HlkJ8H.jpg","size":5112},
             {"name": "s6kA6B0e5m1sdSAjPXqNwtiy4.jpg", "size": 13135}
  ];`

But when get this in server, show me object without quotation:
 ` [
             {name: "XCB808tvXNpqXKqekA2HlkJ8H.jpg",size:5112},
             {name: "s6kA6B0e5m1sdSAjPXqNwtiy4.jpg", size: 13135}
  ];`

I think Restangular change variable and then send. how to send array object JSON as real ?

**Comment by daviesgeek** [comment]
It looks like your server side language is converting it to a native array, not Restangular. What language are you using?

**Comment by essivision** [comment]
ok, I use laravel and find problem in server side. I use `json_decode` that no need

**Comment by daviesgeek** [comment]
Yup! Laravel will automatically use `json_decode` to create a native PHP array.
