### ISSUE TITLE
Response Inteceptor returns object error

### ISSUE THREAD

**Issue by adrn03** [mgonto/restangular#1343]
I tried doing [this ](https://github.com/mgonto/restangular#my-response-is-actually-wrapped-with-some-metadata-how-do-i-get-the-data-in-that-case) but it still produces error.

My data is like this:
![json](https://cloud.githubusercontent.com/assets/17308532/13913201/75998f4c-ef7f-11e5-895e-5fa7f1f16ee9.png)

My controller looks like this:
![controller](https://cloud.githubusercontent.com/assets/17308532/13913206/845eee78-ef7f-11e5-920f-795723fcd5c4.png)

My config for response interceptor looks like this:
![app](https://cloud.githubusercontent.com/assets/17308532/13913222/9f161462-ef7f-11e5-8770-ea4eed9de19a.png)

The result is an object with an error:
![result](https://cloud.githubusercontent.com/assets/17308532/13913231/b31b5f4e-ef7f-11e5-9066-3f9cc641f5c5.png)

I tried doing this in $http and it actually worked:
![http](https://cloud.githubusercontent.com/assets/17308532/13913283/212b5688-ef80-11e5-89a3-93b754aa8a21.png)

Is there any reason why addResponseInterceptor to get the array before returning the response of getList is not working? Or maybe it is an error in my part?

**Comment by nbasov** [comment]
Does it works without "addResponseInterceptor"?

Also I should notice that with "addResponseInterceptor", "then" function parameter became "products" (not object before transformation):
```
baseProducts.getList().then(function(products) {
    vm.data = products;
})
```

**Comment by daviesgeek** [comment]
I was not able to reproduce the issue here: http://plnkr.co/edit/5bAyyxJu9N0BHST8MXrj?p=preview

Can you actually paste your code here? It would be easier to copy & paste the exact code you're using, rather than re-typing it all.

**Comment by aa-go** [comment]
Hi!
@nbasov it throws "Response for getList SHOULD be an array and not an object or something else" when not using addResponseInterceptor

@daviesgeek here is my code

//app.js
RestangularProvider.addResponseInterceptor(function(data, operation) {
      var extractedData;
      if (operation === "getList") {
        extractedData = data.data;
      } else {
        extractedData = data.data;
      }
      return extractedData;
    });

//Controller:
vm.display = function(){
	console.log("hello there");
	console.log($cookies.get('token'));
	baseProducts.getList().then(function(products){
	vm.data = products;
	});
};

//json
{
    "products": [
        {
            "id": 7,
            "prod_name": "Harley Quinn",
            "prod_collection": "Pop Home!",
            "prod_itemCode": "#2467",
            "prod_price": "16.00",
            "prod_quantity": 21
        },
        {
            "id": 8,
            "prod_name": "Iron Man",
            "prod_collection": "Pop Home",
            "prod_itemCode": "#16789",
            "prod_price": "10.00",
            "prod_quantity": 5
        },
        {
            "id": 10,
            "prod_name": "Flash",
            "prod_collection": "Pop DC Heroes",
            "prod_itemCode": "#46876",
            "prod_price": "10.00",
            "prod_quantity": 5
        },
        {
            "id": 11,
            "prod_name": "Arrow",
            "prod_collection": "Pop DC",
            "prod_itemCode": "#56758",
            "prod_price": "10.00",
            "prod_quantity": 6
        },
        {
            "id": 13,
            "prod_name": "Deadpool",
            "prod_collection": "Pop Marvel",
            "prod_itemCode": "#10568",
            "prod_price": "10.00",
            "prod_quantity": 19
        }
    ],
    "_status": 200
}

**Comment by daviesgeek** [comment]
In your interceptor, can you just return the data instead of setting & returning `extractedData`? Also, it's really hard to verify/test something that's broken without something like a plnkr or a fiddle. Any chance you could set one up?
