### ISSUE TITLE
Add custom header cause request method change from GET to OPTIONS

### ISSUE THREAD

**Issue by enryold** [mgonto/restangular#1346]
Hi,

I'm dealing with this trouble.

With this call everything works

`SkinSvc.one(skinId).customGET('events', params).then(success, error);`

With this one with custom header a OPTIONS Http request is send to my API instead of GET request.

`SkinSvc.one(skinId).customGET('events', params, {'Cache-Control':'no-cache'}).then(success, error);`

![get](https://cloud.githubusercontent.com/assets/3513160/13927286/7db644e2-ef91-11e5-96aa-8e7514b6f4e5.png)

![options](https://cloud.githubusercontent.com/assets/3513160/13927275/715dde3a-ef91-11e5-9ebb-088c8761db75.png)

**Comment by daviesgeek** [comment]
The OPTIONS request is a part of [CORS](https://www.w3.org/TR/cors/) (Cross Origin Resource Scripting). Your server should be checking the request and returning the correct headers for a given request (`Access-Control-Allow-Credentials`,  `Access-Control-Allow-Headers`, `Access-Control-Allow-Methods`, `Access-Control-Allow-Origin`, etc…) More detailed info can be found on [the MDN page for CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)

**Comment by enryold** [comment]
Thank you, i solved adding this headers to option request

```
'Access-Control-Allow-Headers', 'Cache-Control'
'Access-Control-Allow-Methods', 'GET'
```

**Comment by daviesgeek** [comment]
Perfect :+1:

**Comment by jedi4z** [comment]
Thanks! 👍

**Comment by pratikpawarnasik** [comment]
This issue is still in angular 6.
