### ISSUE TITLE
In resetangular How to support withCredentials:true for the CORS ?

### ISSUE THREAD

**Issue by uinika** [mgonto/restangular#1349]
I wanna take CORS, but I did not found any info in restangular's markdown.
So , I just want to know is the angular support withCredentials:true in the HTTP request head ?
Any updating, PLS let me know, THX.

**Comment by daviesgeek** [comment]
Restangular uses `$http`, so in a run block, just set `withCredentials=true`:

```js
.run(function($http) {
   $http.defaults.withCredentials = true;
})
```

**Comment by uinika** [comment]
I got ur point, many thx.
