### ISSUE TITLE
oneUrl(...).post() issue

### ISSUE THREAD

**Issue by levgaas** [mgonto/restangular#1350]
When using method **post()** with **oneUrl()** `Restangular.oneUrl(route, path).post(obj) ` 
I have `obj.toString()` appended to my path.

So the path becomes `path/obj.toString() `
For example, `path/[object%20Object]`

Using `customPOST()` instead of `post()` resolves the issue.

Thanks!

**Comment by daviesgeek** [comment]
That's the expected behavior. `post()` is expecting a route as the first parameter, and it'll send the object you're calling the method on as the payload. 

`customPOST()` expects an object as the first parameter (the object to post), and a route as the second.

**Comment by levgaas** [comment]
@daviesgeek So in my case I should do `.post('', {obj})` ? Actually it works.

Yes. Docs says:

> post(subElement, elementToPost, [queryParams, headers]): Does a POST and creates a subElement. Subelement is mandatory and is the nested resource. Element to post is the object to post to the server

But I'm a bit confused when you are using post without 'route' as first parameter.

```
// Declare factory
module.factory('Users', function(Restangular) {
  return Restangular.service('users');
});

// In your controller you inject Users
Users.get(2) // GET to /users/2
Users.post({data}) // POST to /users                    <----------------- here

// GET to /users
Users.getList().then(function(users) {
  var user = users[0]; // user === {id: 1, name: "Tonto"}
  user.name = "Gonto";
  // PUT to /users/1
  user.put();
})
```

Also I've used earlier 
```
Restangular.all('someRoute').post({data}).then(...);
```
And all work like a charm.

Thanks!

**Comment by daviesgeek** [comment]
My apologies. I didn't understand correctly that you were using this as a service. When you create a service with `oneUrl`, the first parameter to `post()` is the route; the second the object.

When you create a service with `all()`, `post()` expects the first parameter to be the object.

**Comment by levgaas** [comment]
@daviesgeek thatnks

**Comment by daviesgeek** [comment]
No problem!
