### ISSUE TITLE
Parent Resource ID missing for restangularize elements

### ISSUE THREAD

**Issue by frikkievb** [mgonto/restangular#1353]
Hi

I am not sure if it is my misunderstanding of Restangular or if it is a bug that is occurring.  My setup is a bit complex to create an example, but I will try and explain as best I can.

I have multiple states for my app, and I make use of resolve provided by ui-router to instantiate my Restangular objects:

`resolve:{
                        "election":["Restangular","$stateParams","organisation",function(Restangular,$stateParams,organisation){
                            return Restangular.one("organisations",organisation.organisationID).one("elections",$stateParams.electionID).get();
                        }]
                    }`

organisation is also a Restangular object.

I basically have a list from which I can add or edit candidates.  All candidates belong to an election.

thus my route for my API is:  

**elections/:electionID/candidates**

From the controller that is being instantiated by this state, I am injecting "election".  This works great since I can now quickly save my objects and work with them more easily.  This is all good until I want to add a new object to the list.

I realized that I first need to restangularize the element before adding it to the list, so that it can share the same functionality.  But when calling save, my electionID seems to disappear from my URL (the parent resource ID is missing)

The path to my resource should be this:

**elections/1/candidates**

but I am getting:

**election/candidates**

This only happens for the restangularized objects.  All  the others are working fine.

Inside the controller which pushes the newly created object to the collection, I am using the following lines of code:

First I inject my "election" object. (election is the parent of candidate)

`function ElectionCandidatesToolbarController(Restangular,election,candidates,$mdToast,$mdDialog)`

then I am receiving my new JSON data for the newly created candidate, which I want to restangularize:

`vm.candidates.push(Restangular.restangularizeElement(election, answer.candidate, 'candidates'));`

This pushes it to the list and it appears all good, until I want to edit and save the newly created object.  This results in the electionID to be dropped from the URL.

I've already checked that the electionID is set in the object with console.log();  It is still present but not in the URL it is generating.

I am using custom ID's.  The code to handle my custom ID's is the following:

`RestangularProvider.configuration.getIdFromElem = function (
                return elem[_.initial(elem.route).join('') + "ID"];
            };`

Hope this makes sense :|

Kind regards

**Comment by frikkievb** [comment]
Looks like it always wants to POST the newly created object...

**Comment by frikkievb** [comment]
By forcing the "fromServer" property to true, it appears to be working.  Not sure if this should be part of the settings for a restangularized object.

**Comment by daviesgeek** [comment]
This should be added later in #1389. Were you able to get it working by just setting `fromServer` to true?
