### ISSUE TITLE
Issue with params on addFullRequestInterceptor

### ISSUE THREAD

**Issue by Gu3** [mgonto/restangular#1358]
Hi everybody !
I try to intercept my request and change some params to filtering or ordering. 
Back side, I use https://github.com/theofidry/LoopBackApiBundle 
So to ordering for example I need to put on my request : ?filter[order][property]=<ASC|DESC>
I try to do something like that : params.filter[order][params._sortField]=params._sortDir;

Without success, worst my app freeze...
Any ideas ? 

Thanks ! 
Guf.

**Comment by daviesgeek** [comment]
Can you provide a code example and a little more explanation of what you're trying to do? It looks like you're trying to send an array of JSON encoded parameters?

**Comment by Gu3** [comment]
Hi ! I found ! 
It's impossible to pass an array to restangulars param... I need to modify the url directly thankful $httpProviders. 
If someone need :

```
$httpProvider.interceptors.push(function() {
            return {
                request: function(config) {
                    if( typeof (config.params) !== 'undefined'
                        && config.params._sortField
                        && config.params._sortDir){

                        if(config.url.split('?').length > 1)
                            config.url = config.url + '&filter[order] ['+config.params._sortField+']='+config.params._sortDir
                        else
                            config.url = config.url + '?filter[order]['+config.params._sortField+']='+config.params._sortDir

                        delete config.params._sortField;
                        delete config.params._sortDir;
                    }
                    return config;
                },
            };
        });
```

**Comment by daviesgeek** [comment]
Glad you figured it out!
