### ISSUE TITLE
Mystery parameter

### ISSUE THREAD

**Issue by ziplizard** [mgonto/restangular#1361]
I'm using the latest angular (1.5.3) and the latest restangular (1.5.2) and am having the strangest issue. I have a simple request Restangular.one('Organization',5).get() that will always pass a mystery parameter that I'm not sure where it's coming from. It will always include "organization=123" (the 123 value is a valid number from my db - that is set in $scope elsewhere). If I set manually like so .get({organization:''}), then it does not get set. Otherwise the organization parameter is always there. Not sure why. Can you help?

**Comment by daviesgeek** [comment]
Can you create a Plunk or fiddle to demonstrate this?

**Comment by ziplizard** [comment]
Much too complex of an app to create a plunk for it. Basically I don't know how/why the organization parameter is being set. It it set every time throughout the system where Restangular is used for "Organization" (both one and all). Somehow the "organization" parameter is being auto set on all of these requests, and I cannot find where or how. I've check the interceptors in the config, and nothing there. What am I missing?

**Comment by ziplizard** [comment]
Just found another place in the system where we're doing Restangular.all('job').getList() and this also appends the ?organization=123 to the request.

**Comment by ziplizard** [comment]
Found the problem. Another dev had used Restangular.setDefaultRequestParams on a single request, when in fact it affected every subsequent request. I have it under control now. Sorry for the false alarm.

**Comment by daviesgeek** [comment]
Ah okay. Great! Glad to hear that
