### ISSUE TITLE
Retrieving an object with property 'head'

### ISSUE THREAD

**Issue by senpairamen** [mgonto/restangular#1362]
Consider the following mongodb item:
```
{
    "_id" : ObjectId("57163ba3dbca3e004d6ccffc"),
    "head" : ObjectId("5716318a5a4c1ae84c57e760"),
    "created" : ISODate("2016-04-19T14:07:31.370Z"),
    "active" : true,
    "name" : "Test Department",
    "__v" : 0
}
```
And the following angular controller code
```
var Departments = Restangular.all('departments');

Departments.one($stateParams.id).get().then(function(department) {
    $scope.department = department;
});
```
While the GET request contains the right JSON, the local `department` variable has it's `head` property set to `undefined`
I managed to resolve the problem by setting the `head` property to `manager`.

Just wanted to let you know ;)

**Comment by daviesgeek** [comment]
Yes that works. You can also use [`setRestangularFields`](https://github.com/mgonto/restangular#setrestangularfields)

**Comment by daviesgeek** [comment]
I am going to close this for now. Feel free to re-open if there's still an issue
