### ISSUE TITLE
Latest version of restangular

### ISSUE THREAD

**Issue by subramn** [mgonto/restangular#1364]
Hi

whether the latest version of restangular can be pushed to nuget ? I use the version 1.4.0

Thanks

**Comment by daviesgeek** [comment]
It looks like [the package](https://www.nuget.org/packages/Restangular/) is maintained by [mtucker](https://www.nuget.org/profiles/mtucker), so I'd recommend contacting them. I may be wrong, but we don't maintain that package

**Comment by daviesgeek** [comment]
I'm going to close this issue. Feel free to re-open if this is still a problem
