### ISSUE TITLE
login page using restangular

### ISSUE THREAD

**Issue by Harshithaharshu** [mgonto/restangular#1365]
i'm trying to write services for login but i didn't get .please send code using restangular

**Comment by bhavanims** [comment]
just do one thing...go through this web below website
http://www.codeproject.com/Articles/897444/Implementing-REST-Services-in-AngularJS-using-Rest

**Comment by daviesgeek** [comment]
@Harshithaharshu Any progress on this?

**Comment by mappedinn** [comment]
:+1:

**Comment by daviesgeek** [comment]
Since it seems like there's no progress or updates on this issue, I'm going to go ahead and close this. OP, feel free to re-open if you still need some help.
