### ISSUE TITLE
How to send customGET with several ids and other parameter

### ISSUE THREAD

**Issue by essivision** [mgonto/restangular#1367]
Hi

I want to send several ids with other parameter from `customGET` method. It's my method but doesn't work:
```
var selection = [2,10,20];

// send GET /api/user/export/file?param1=test&ids=2,10,20
Restangular.all('user').customGET('export/file',{param1:'test',ids:selection}).then(function(response) {
/*  */
        })
```

Thanks

**Comment by daviesgeek** [comment]
Just use [`join`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join)

```js
var selection = [2,10,20]
Restangular.all('user').customGET('export/file', {param1:'test', ids: selection.join(',')})

```

**Comment by daviesgeek** [comment]
I'm going to go ahead and close this. Feel free to re-open if there's still an issue!
