### ISSUE TITLE
Infdig with lodash 2.4.1

### ISSUE THREAD

**Issue by c0bra** [mgonto/restangular#1368]
bower.json says `lodash >= 1.3.0` but with 2.4.1 (from Nuget) I was getting infinite digests.

After I updated to latest (4.11.2) the error went away.

Perhaps the dependency needs to be updated?

**Comment by daviesgeek** [comment]
Looks like that's scheduled for the next release #1327

**Comment by bostrom** [comment]
Fixed in e0b68a021ad9e4f7fc34d66cad4c24af1864ba18
