### ISSUE TITLE
How to send a parameter on the all of request

### ISSUE THREAD

**Issue by essivision** [mgonto/restangular#1369]
Hi

I want to send a parameter as `lang` for all request that use rectangular. Is there any way so I that add this parameter in `.config` section?

Thanks

**Comment by essivision** [comment]
Set the value in the interceptor, e.g:
```
RestangularProvider.setDefaultRequestParams({lang: "en"});
```

**Comment by mappedinn** [comment]
:+1:

**Comment by daviesgeek** [comment]
Does this resolve your issue @essivision ?

**Comment by essivision** [comment]
Yes, Thanks
