### ISSUE TITLE
setting protocol

### ISSUE THREAD

**Issue by acthp** [mgonto/restangular#1372]
How can I set the protocol to https?

**Comment by daviesgeek** [comment]
Just set the protocol in the baseUrl:

```js
RestangularProvider.setBaseUrl('https://your-api-root-here.com');
```

**Comment by acthp** [comment]
Thanks! The app code was overwriting this when I tried it, resulting in urls like ```http://https://foo.org```. After fixing the app code, restangular is working as expected.
