### ISSUE TITLE
Clone / Copy - How does it work

### ISSUE THREAD

**Issue by ADCJustinH** [mgonto/restangular#1373]
The guide while excellent doesn't really get into the details of how the clone method works. I get a lot of data out of my api some of which is cached in local storage to be used when my app starts up. I would like to use this data (from local) then clone, make changes and post it. 
I thought perhaps I could load the data from local storage then 
var usableObj= angular.extend(localData, restangular.one('datasource',localData.id)); 
...
var editObj = usableObj.clone();
editObj.xyz='abc';
editObj.save();

However when calling the clone method all of my data is stripped out leaving only the restangular methods. Why does this happen and is this use case supported?

**Comment by daviesgeek** [comment]
Here's the better way to do what you're trying to do:

```js

// Copy it first
var editObj = angular.copy(localData)

// Restangularize it (this adds all the Restangular methods)
Restangular.restangularizeElement(null, editObj, 'datasource')

editObj.xyz = 'abc
editObj.save()
```
