### ISSUE TITLE
Sending Json type file

### ISSUE THREAD

**Issue by turoni** [mgonto/restangular#1376]
This might be a duplicate of #420 but if it is can someone tell me how I need to apply this in my situation.

I'm trying to upload a file and send it to my backend trough RestAngular.

Using input type=file and [ngf-select](https://github.com/danialfarid/ng-file-upload) I get the following JSon

` Object { externDossierNr: "foo1", internDossierNr: "2016011", rapport: File, testword: 42, testarray: Array[3] }`
and the json of rapport
`File { name: "Rapport.pdf", lastModified: 1463402787393, lastModifiedDate: Date 2016-05-16T12:46:27.393Z, size: 83605, type: "application/pdf" }`$

I then save it with.

`public save(item: any): any  {
        
        
        item["testword"] = 42;
        item["testarray"] = [2,5,9];
        
        console.log("item to save is ", item);
        console.log("rapport is ", item["rapport"]);
                
        if (item.id === undefined) {
                
            this.restService.save(this.metadata.apiDomain, item).then((addedItem: any) => {
                toastr.success(`${addedItem.naam} successfully created.`, `Overzicht Dossiers Created`);
            });
        } else {
            this.restService.update(this.metadata.apiDomain, item).then((updatedItem: any) => {
                toastr.success(`${updatedItem.naam} successfully updated.`, `Overzicht Dossiers Updated`);
            });
        }
    }`

Where this.restService.save() is

`/* POSTs the data object to the {apiUrl}/{type} URL, where apiURL was set during restangular configuration */
    public save(type: string, data: any): any {
        return this.restangular.all(type).post(data);
    }`

I'm writing a custom deserializer to put this in a class.
`package be.ugent.lca.data.entities.deserializers;

import be.ugent.lca.data.entities.Dossier;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;

public class DossierDeserializer extends JsonDeserializer {
    @Override
    public Dossier deserialize(JsonParser jsonParser,
            DeserializationContext deserializationContext) throws IOException {
        ObjectCodec oc = jsonParser.getCodec();
        JsonNode root = oc.readTree(jsonParser);
        Dossier dossier = new Dossier();

        dossier.setExternDossierNr(root.get("externDossierNr").asText());
        dossier.setInternDossierNr(root.get("internDossierNr").asText());

        System.out.println("Intern Dossier nr is " + root.get("internDossierNr"));
        System.out.println("Test word " +  root.get("testword"));
        System.out.println("Test array " + root.get("testarray"));
        JsonNode node = root.get("rapport");
        if(node == null){
            System.out.println("Rapport is a null pointer.");
        }else{
            System.out.println("Rapport is " + node + " with size " + node.size());
        }
        return dossier;
    }
}`

From this I see that I can parse all my parameters in the Json except rapport.
System.out.println("Rapport is " + node + " with size " + node.size());
    gives
Rapport is {} with size 0

Can't restangular send the Json File type or should I be sending it some other way?
Any reference to the Json File type would be apreciated as wel, cause I also can't find anything about it.

**Comment by turoni** [comment]
My problem isn't fixed so I'm not sure if I understand completely but I was under the presumption that by using multipart/formdata in my html form it was already formatted correctly but apparently it was not so I've been able to add it like in #420. As I said, my problem isn't solved so I'm only pretty sure the problem is serverside but I'll close this for now till I know more.

**Comment by daviesgeek** [comment]
Feel free to re-open if it seems like it's actually a problem within Restangular!
