### ISSUE TITLE
Cancel a request

### ISSUE THREAD

**Issue by Clem01** [mgonto/restangular#1377]
To avoid duplication of requests (double click), I would be able to stop a running query. I do not see how. Can you help me please ?

```
let inProcess = false;

return Restangular.withConfig(function(RestangularConfigurer) {
	RestangularConfigurer
		
		...
		
		.addFullRequestInterceptor(function(element, operation, what, url, headers) {
			
			if (inProcess) {
    			// cancel the request here
    			return;
			}
			
			inProcess = true;
            
		})
		
		...
});
```

**Comment by daviesgeek** [comment]
Here's the way I've done it:

```js
let canceler = $q.defer()
Restangular.all('users').withHttpConfig({timeout: canceler.promise}).get()
canceler.resolve() // cancels the request
```

This is a little counterintuitive, so let me explain. `$http` takes a `timeout` parameter (see [the $http docs](https://docs.angularjs.org/api/ng/service/$http):

> timeout in milliseconds, or promise that should abort the request when resolved.

Resolving the promise (`canceler` in this case), will cancel the request

**Comment by Clem01** [comment]
Really great ! It works well, thank you for your solution :)

**Comment by eprevot** [comment]
This doesn't work if I don't cancel immediately after the request is done, can you reproduce ?
```
let canceler = $q.defer()
Restangular.all('users').withHttpConfig({timeout: canceler.promise}).get()
$timeout(() => canceler.resolve(), 0) // doesn't cancel the request
```
