### ISSUE TITLE
execute GET() for each element from getList()

### ISSUE THREAD

**Issue by Nosthertus** [mgonto/restangular#1378]
I am not sure if there is actually a method available in `restangular`, i don't know if `several()` handles this but i cannot be sure because i think it needs more explanation, (i say the same with the rest of the API)

so i was thinking on this.. we have `accounts` resource from the server and it has it's CRUD methods, for now let's just read data for the purpose of this issue

we issue request to `GET: /accounts`

and data returned is like this

```JSON
[
  {
    "id": 1,
    "username": "#fa0798"
  },
  {
    "id": 2,
    "username": "#008874"
  }
]
```

so now i want to get detailed information of each element shown in this response by accessing the resource according to the `id` of each element.

it would be too much code to add to the `controller` or any other place you are executing this code to make an iteration of each element, make calls and then return when all calls are done.

the code could be like this:
```Javascript
//GET: /accounts/1
//GET: /accounts/2
Restangular.all("accounts").iterateId()
    .then(function(data){
        //Data is an array of each element resource gathered from GET: /accounts/[id]
    });
```

if `restangular` already does this, then please show me how it is done, i would like to see if i have skipped something on the documentation or if i am missing a function

**Comment by daviesgeek** [comment]
There isn't really a built in way to do this in Restangular. This should be pretty simple to implement yourself. `several` isn't the answer either, as it just concatenates the IDs together:

```js
Restangular.several('accounts', 1234, 123, 12345) // accounts/1234,123,12345
```

**Comment by oakerele** [comment]
Is there a way to pass in multiple ids as an array into the several method? An example would be
`var ids = ['1','2','3','4'];
Restangular.several('accounts', ids)`

is something like this possible, or is there a "hack" that can work in this same way?

Thanks

**Comment by daviesgeek** [comment]
You are more than welcome to open a PR with a change for this if you so desire

**Comment by Nosthertus** [comment]
Sorry for the late response, i would gladly work on a PR for this feature.. but at this moment i am really busy on my job.

I will keep this in mind and work for this in the future.. if anyone has already worked on this, please let me know

**Comment by daviesgeek** [comment]
No problem. I'm going to go ahead and close this for now, but feel free to submit that PR if you have a chance!
