### ISSUE TITLE
How to make deep-nested api with restangular

### ISSUE THREAD

**Issue by BjornMelgaard** [mgonto/restangular#1387]
My routes looks like this 
```ruby
resources :polls do
    resources :questions do
        resources :options
    end
end
```
How to make this?
```coffee
poll = Restangular.all("polls").post().$object
# poll = {id: 1, title: null, questions: [    {id:11, content: null, options:[{id: 111, content: null}] }   ] }
poll.questions[0].content = "content_11"
poll.questions[0].save() # impossible, questions is json, not restangular object
# PUT api/poll/1/questions/11&content=content_11
poll.questions[0].options.post() # impossible
# POST api/poll/1/questions/11/options, return {id: 112, content: null}
# poll = {id: 1, title: null, questions: [    {id:11, content: "content_11", options:[{id: 111, content: null}, {id: 112, content: null}] }   ] }
```

**Comment by daviesgeek** [comment]
I'm not entirely sure what's happening here…can you please provide some more information?

> impossible, questions is json, not restangular object

Not sure what you mean by this.

I'm going to take a shot in the dark and say that you should probably be using `restangularizeElement`, passing in the parent as the first parameter. See [the docs](https://github.com/mgonto/restangular#restangular-methods)

**Comment by BjornMelgaard** [comment]
I grasp this and will use `restangularizeElement`, thanks :smile:

**Comment by daviesgeek** [comment]
Awesome! Yw!
