### ISSUE TITLE
my restful server is strongloop , param format is filter[skip] it's have problem

### ISSUE THREAD

**Issue by polo13999** [mgonto/restangular#1388]
my code is 

var query = { filter[skip] : 10};
Restangular.all("products").getList("products",query );

error code is
product.factory.js:27 Uncaught SyntaxError: Unexpected token [

**Comment by daviesgeek** [comment]
```js
var query = { filter[skip] : 10}; // invalid JavaScript

var query = { filter['skip'] : 10}; // valid JavaScript
```
