### ISSUE TITLE
Nested resources that can also be top level resources

### ISSUE THREAD

**Issue by TheLudd** [mgonto/restangular#139]
Hello.
I have a restful backend that contains companies and each company has a list of services. I get a companies list of services at the URL "company/{companyId}/servicelist"
However each service is also considered a "top level" entity. To update a service I need to send a PUT request to the address "service/{serviceId}".

If i retreive the list of services for a company with Restangular, each one of the retreived services will have an "incorrect" route. Like this:

```
Restangular.one("company", 42).all("servicelist").getList().then(function(serviceList) {
    var firstService = serviceList[0]; // firstService.id is 1.
    firstService.name = "A new name";
    firstService.put(); // will post to company/42/servicelist/1
});
```

Can I configure this so that the PUT request will be sent to "service/1"?

**Comment by destegabry** [comment]
I'm trying to follow the documentation and looking at the issues but I'm getting really confused.
I have some tables on my DB, let's say User, Customer and UserCustomer (which implements an n:n relation between User and Custom).
I have set up endpoints in my server at /user/[id], /customer/[id] and /user/[iduser]/customer/[idcustomer]
I can CRUD on User and Customer tables using the Restangular.service syntax:
```
angular.module('...')
  .factory('User', function (Restangular) {
    return Restangular.service('user');
  })
  .factory('Customer', function (Restangular) {
    return Restangular.service('customer');
  })
```
In my User factory I would like to define a getCustomer method which populates an user instance with a customers variable, pointing to a collection of Customer.
Seems I can do soething like
```
angular.module('...')
  .factory('User', function (Restangular) {
    Restangular.extendModel('user', function(model) {
      if (model.customers) {
        Restangular.restangularizeCollection(null, model.customers, 'customer');
      }
      return model;
    });
    return Restangular.service('user');
  });
```
but can't figure out how to use it in a controller!
