### ISSUE TITLE
restangular is not working with webpack 

### ISSUE THREAD

**Issue by kalpitpandit** [mgonto/restangular#1397]
Getting **'Argument 'module' is not a function, got Object'** whenever i am trying to 

> require('restangular')

 as a dependency. 

When i use [https://www.npmjs.com/package/restangular-umd](this package) it works fine with webpack setup. 

Can we merge above package changes in official package?

**Comment by daviesgeek** [comment]
There was a PR (#1284) for this not too long ago, but it hasn't been put into a tagged release yet. If you want, you can install Restangular from the master branch and that should work. Hopefully we should be releasing 1.5.3 sometime soon and that will be included in the release.

**Comment by kalpitpandit** [comment]
Thanks. I will give a try.

**Comment by kalpitpandit** [comment]
Thanks. Its working like a charm. But it seems minified file is still pointing to older version file.

**Comment by daviesgeek** [comment]
I'm hoping to release 1.5.3 shortly, so this should be fixed as of that release.

**Comment by GabrielGil** [comment]
What is currently the status of this issue? Any reason it has been reopened? Cheers!

**Comment by samsfisher** [comment]
Hello @kalpitpandit  I tried pulling the latest commit but its still giving me the same error any pointers

**Comment by pierrebeaucamp** [comment]
Same here - no luck after pulling from master.

**Comment by bostrom** [comment]
Can you guys check this issue with the 1.6.0 release?

**Comment by bostrom** [comment]
Considering resolved. Please reopen if problem still persists.

**Comment by GabrielGil** [comment]
Yep, it works but it is not published to NPM. Please do :)

**Comment by bostrom** [comment]
Yes, we'll have to get publishing rights to npmjs.com from @mgonto first.

**Comment by LeoLozes** [comment]
Any news on this?

**Comment by GabrielGil** [comment]
This is working for me since early this year. What is the issue you're encountering?

**Comment by LeoLozes** [comment]
The same 'Argument 'module' is not a function, got Object' stated in the first comment. I'm using the last release available on npm (1.6.1).

**Comment by GabrielGil** [comment]
I am using the exact same version, and it works fine to me. I am importing it using ES6 but don't believe makes a difference. Check your NPM cache and prune your dependencies.

```js
import restangular from 'restangular';

angular.module('MyApp', [
  restangular,
])
```

**Comment by kalpitpandit** [comment]
@LeoLozes I am using exact same version via npm tool. Its working totally fine for me. 

`angular.module('MyApp', [
    require('restangular'),
])`

**Comment by eltonk** [comment]
And how to inject the Restangular in a Angular controller?

export default class DashboardController {
  constructor() {
    Restangular.get('test');
  }

>  Restangular.get is not a function

**Comment by kalpitpandit** [comment]
@eltonk This should work in your case.

```
import restangular from 'restangular';

export default class DashboardController {
    constructor(Restangular) {
        Restangular.get('test'); 
    }

angular.module('MyApp', [
  restangular,
])
```

**Comment by eltonk** [comment]
Thanks, @kalpitpandit!
