### ISSUE TITLE
How to set list of elements as parentless

### ISSUE THREAD

**Issue by jayellsbrg** [mgonto/restangular#1399]
@mgonto How can I request all tenants belonging to an apartment, and then reference the original tenant? I could be doing this wrong, but I don't see any other solution in the documentation.

Say I want a list of all tenants registered at an apartment

```
// /apartments/210/tenants
var tenants = Restangular.one('apartments, 210).all('tenants').getList();
```

Now, that I have all tenants, I want to get all cars belonging to the first tenant, but the url for that is /tenants/15/cars (rather than /apartments/210/tenants/15/cars).

so this doesn't work

```
var firstTenant = tenants[0];
var cars = firstTenant.all('cars').getList();
```

I tried configuring Restangular with setParentless in the documentation
`.setParentless(['tenants'])`

but after that, the first request generates the url path `/tenants` instead of the original `/apartments/210/tenants`.

Any help is appreciated.

Thanks!

**Comment by bostrom** [comment]
Closing due to the nature and age of issue. Please consider the updated [issue guidelines](https://github.com/mgonto/restangular/blob/master/.github/ISSUE_TEMPLATE.md) and reopen if needed.
