### ISSUE TITLE
Testing .put() method using jasmine and karma

### ISSUE THREAD

**Issue by shivanisaz** [mgonto/restangular#1400]
Method in a service- 
saveEducationDetails: function(updatedEducation){
    updatedEducation.put()
        .then(function(response){
                         .......
                 }
});

Unit test-
it('should update education details', function() {
        var edu = {
            institutionName: "",
            degree: "",
            description: ""
        };
        $httpBackend.expectPUT( url)
            .respond(edu);
        educationService.saveEducationDetails(edu);
        httpBackend.flush(1);
        expect(educationService.education).toEqual(edu);
    });

In this case, "edu" is not a restangularized object hence .put() is not recognised as a method so the unit test fails. 
What is the correct way to unit test the put/save method(s) ?

**Comment by bostrom** [comment]
You need to use restangularizeElement on the edu object to populate it with get(), put() etc before passing it to saveEditcationDetails().
