### ISSUE TITLE
Does Restangular 1.x support latest angular 1.5.x?

### ISSUE THREAD

**Issue by kelvinwang139** [mgonto/restangular#1403]
Thanks for this great lib while I have a question that I see:
"Restangular supports all angular versions including 1.0.X, 1.1.X and 1.2.X (1.2.4 being the current at the time)"
Does Restangular 1.x support latest angular 1.5.x?

**Comment by madflow** [comment]
I cannot comment if "Restangular" supports Angular 1.5.x - but we are using both in production and we have not seen compatibility issues yet.

The current testing setup seems to use 1.3.12

https://github.com/mgonto/restangular/blob/master/karma.conf.js

hth

**Comment by Deleugpn** [comment]
+1 for this.

**Comment by kelvinwang139** [comment]
Hi madflow, thanks for your valuable answer.
