### ISSUE TITLE
Deleting part of a JSON Object

### ISSUE THREAD

**Issue by oakerele** [mgonto/restangular#1404]
Hey, thanks for all that worked on this project.

I was wondering if there was anyway to delete part of a JSON Object in a collection. An example will be if I have a few users and I want to delete an item in one of the users cart. The JSON Object will be set up like this:

`
{   "_id" : "username@domain.com", 
    "name" : "NameofMe", 
    "cart" : [
        {
            "item_id" : "ryhXFEEu"
        }
    ]
}`

And in this JSON Object, rather than deleting the whole JSON object, I'll like to only Delete the "item_id" inside the cart array.

Some of the methods I tried implementing like CustomDELETE did not seem to work since I did not even know if it will work in the first place. Any help is appreciated. Thanks

**Comment by daviesgeek** [comment]
I'm guessing you want to make a DELETE request based on the `item_id`?

Here's how to do that. In your service:

```js

let service = Restangular.all('service')

service.addElementTransformer('service', false, function (item) {
  
  item.deleteChildItem = function (id) {
    item.customDELETE('child/' + id )
  }
})
```

If you want it on each individual item, you could do this:

```js
service.addElementTransformer('service', false, function (item) {
  if(item.cart.length) {
    for (var i = 0; i < item.cart.length; i++) {
      let cartItem = item.cart[i]
      cartItem.delete = function() {
        item.customDELETE('child/' + cartItem.item_id)
      }
    }
  }

})
```
