### ISSUE TITLE
customGETLIST with nested array parameters

### ISSUE THREAD

**Issue by oakerele** [mgonto/restangular#1406]
Is it possible to use a nested array as a parameter when using customGETLIST to get data from a collection based on the passed in argument? So the code will look something like:

``` js
Restangular.all('data').customGETLIST('', {
    user: {
        email: 'email@domain.com'
    }
}).then(function (data){
    $scope.data = data;
    console.log(data);
});
```

**Comment by daviesgeek** [comment]
What is the end result you are trying to accomplish? It looks like you're trying to put an object in the URL parameters?

**Comment by bostrom** [comment]
Closing due to the nature and age of issue. Please consider the updated [issue guidelines](https://github.com/mgonto/restangular/blob/master/.github/ISSUE_TEMPLATE.md) and reopen if needed.
