### ISSUE TITLE
Error is file:///android_asset/www/ gets added before the rest URL https://www.abcd.com/api/getdata

### ISSUE THREAD

**Issue by appplumbr** [mgonto/restangular#1407]
Environment:
Using cordova 5+
Android 5+ 
iOS development workstation 
AngularJS 1.4.x +  

when I make a GET rest call all i can see in console is file:///android_asset/www/ gets added before the rest URL https://www.abcd.com/api/getdata like below? 

If I make the same call using angular $http.get it works, what am I missing?

Is it in Cordova or Restangular like issue raised here > http://stackoverflow.com/questions/34876836/cordova-http-request-issue-in-android-device

**Comment by daviesgeek** [comment]
Can you please provide a more thorough example of your code please? I am not sure exactly what's happening, but there's nothing to go on when there's no code example.

**Comment by appplumbr** [comment]
@daviesgeek - I resolved this issue myself please go ahead and close this one.

**Comment by naji-makhoul** [comment]
> @daviesgeek - I resolved this issue myself please go ahead and close this one.

can you explain how did you fix it please...
