### ISSUE TITLE
how to use restangular as data layer?

### ISSUE THREAD

**Issue by behroozshafiabadi** [mgonto/restangular#1408]
Hi
i'm new to restangular and i want to know how to use this module as data layer in my app ?
can it store data inside object we create ?
i have factory like this : 
`function doctorDataModel(Restangular) {
    return Restangular.service('doctor');
}`
can this service keep data inside after we change route ???

**Comment by behroozshafiabadi** [comment]
chernobyl is here!

**Comment by mappedinn** [comment]
https://github.com/mgonto/restangular/issues/1048#issuecomment-241263655

**Comment by daviesgeek** [comment]
Can you elaborate on what you're trying to do @behroozshafiabadi ?

**Comment by daviesgeek** [comment]
@mappedinn the original author has passed the project on, so it hasn't gotten as much attention lately as it needs :/

**Comment by mappedinn** [comment]
@daviesgeek  thanks for noticing us.

the project is still maintained or not?

**Comment by bostrom** [comment]
Closing due to the nature and age of issue. Please consider the updated [issue guidelines](https://github.com/mgonto/restangular/blob/master/.github/ISSUE_TEMPLATE.md) and reopen if needed.
