### ISSUE TITLE
Put and nested gets

### ISSUE THREAD

**Issue by brandhaug** [mgonto/restangular#1410]
I'm having the same problem as this unsolved question: http://stackoverflow.com/questions/27855472/nested-resources-with-restangular

Im using the MEAN stack

First I get my club (api/clubs/club_id)

```
    Restangular.one('clubs', $routeParams.id).get().then(function (club) {
            $scope.club = club;
    });
```

Im following the Restangular documentation and try to do this nested call: 

`$scope.club.getList("contactpersons")`

But it does not work. I believe my nested call goes to api/clubs/contactperson and not api/clubs/club_id/contactpersons as it should.

I'm also trying to update the club information. like this

```
    $scope.saveInfo = function () {
            var newClub = Restangular.copy($scope.club);

            newClub.put();
        };
```

I get an error in my console that says the call goes to api/clubs and not api/clubs/club_id as it should.

If i write:
`Restangular.one('clubs', $routeParams.id).all('contactpersons').getList().then(functi‌​on (contactPersons) { $scope.contactPersons = contactPersons; });`
I get the contactpersons the right way

**Comment by daviesgeek** [comment]
The way to do nested resources is with a service:


```js

let Club = Restangular.service('clubs')

Restangular.addElementTransformer('clubs', false, function(club) {
  club.getContacts = function() {
    return club.customGET('contactpersons')
  }
  return club
})

Club.getList().then(function(list) {
  list[0].getContacts() // works like you want here
})

```

In your second example, use `save` instead of `put` and that should resolve your problem
