### ISSUE TITLE
How do i get baseurl using restangular?

### ISSUE THREAD

**Issue by ravindra-miyani** [mgonto/restangular#1411]
I only wanted to get the restangular baseUrl. how do i get only baseUrl ?

**Comment by daviesgeek** [comment]
As far as I know, there's no way to do this. It wouldn't be that hard to implement a `getConfig()` method. Feel free to submit a PR if you want to.

I'm going to close this for now, since I did already answer it, but feel free to re-open if you need to elaborate more.
