### ISSUE TITLE
Worst Documentation Ever

### ISSUE THREAD

**Issue by justgeek** [mgonto/restangular#1412]
This is a very bad issue you got right now, you have a real bad documentation, and it was my mistake to use restagnular for my project, wasted a whole day trying to post my data as payload but in vain, absloutely unstarred.

**Comment by juanvillegas** [comment]
I think its just .post("", data) ?

**Comment by daviesgeek** [comment]
I understand that the docs may not be the clearest in the world, but take a look at the big code example: https://github.com/mgonto/restangular#lets-code

```js
Restangular.all('accounts').post({ ................... })
```
