### ISSUE TITLE
Client_credentials grant type not supported??

### ISSUE THREAD

**Issue by thiagosoeiro** [mgonto/restangular#1413]
Code below won't work. Grant type is client_credentials. It returns null response with status -1. API is okay. Both requests work fine on postman

```
function authentication(user) {
            return Restangular
                .all('token')
                .post('grant_type=client_credentials&client_id=' + APPLICATION.clientId + '&client_secret=' + 'XYZ',
                undefined, { 'Content-Type': 'application/x-www-form-urlencoded' });
        }
```

Code below works perfectly with password grant type.

```
function authentication(user) {
            return Restangular
                .all('token')
                .post('grant_type=password&username=' + user.username + '&password=' + user.password + '&client_id=' + APPLICATION.clientId,
                undefined, { 'Content-Type': 'application/x-www-form-urlencoded' });
        }
```

What is wrong?

**Comment by daviesgeek** [comment]
You're posting a string as the payload of the request, if I'm reading the example correctly. Swap the parameters:

```js
function authentication(user) {
  return Restangular.all('token')
                    .post(
                      null, // don't post anything
                      'grant_type=client_credentials&client_id=' + APPLICATION.clientId + '&client_secret=' + 'XYZ', // this is where the query parameters should go
                      { 'Content-Type': 'application/x-www-form-urlencoded' } // And then the headers
                    );
}
```

**Comment by thiagosoeiro** [comment]
Did not work. It should be a form data payload. It's generating a query string in the format below. And if that was the problem, example 1 should also not work, but it's fine. `0=g&1=r&10=%3D&11=c&12=l&13=i&14=e&15=n&16=t&17=_&18=c&19=r&2=a&20=e&21=d&22=e&23=n&24=t&25=i&26=a&27=l&28=s&29=%26&3=n&30=c&31=l&32=i&33=e&34=n&35=t&36=_&37=i&38=d&39=%3D&4=t&40=m&41=e&42=u&43=E&44=i&45=n&46=s&47=t&48=e&49=i&5=_&50=n&51=-&52=n&53=g&54=A&55=u&56=t&57=h&58=%26&59=c&6=t&60=l&61=i&62=e&63=n&64=t&65=_&66=s&67=e&68=c&69=r&7=y&70=e&71=t&72=%3D&73=a&74=b&75=c&76=@&77=1&78=2&79=3&8=p&9=e`

**Comment by bostrom** [comment]
Closing due to the nature and age of issue. Please consider the updated [issue guidelines](https://github.com/mgonto/restangular/blob/master/.github/ISSUE_TEMPLATE.md) and reopen if needed.
