### ISSUE TITLE
toJSON ignored when I am sending params via query 

### ISSUE THREAD

**Issue by andrejkaurin** [mgonto/restangular#1414]
Here is the code of my object:

```
var query = {
name: 'Andrej',
email: 'Kaurin',
toJSON: function() {
 return {name: this.name}
}
};
```

As I can see Restangular internally uses angular $http, which internally uses JSON.stringify that, by specification will look at toJSON method first for serialization.
As I can see this is totally ignored when I am sending request like this one

`Resrtangular.one('zap-rest/campaigns', campaign.id).one('stats').get(query)`

Am I missing something?

**Comment by bostrom** [comment]
This seems to work for me:

```
Restangular.all("projects").post({
      name: "Old",
      toJSON: function () {
        return {
          name: 'New'
        };
      }
    })
```

The resulting HTTP request's payload is `{name: 'New'}`. 

Also make sure your `this` is referencing the correct object.
