### ISSUE TITLE
Resolved instance replaced on getList()

### ISSUE THREAD

**Issue by frikkievb** [mgonto/restangular#1418]
Hi

I am not sure if I am doing something wrong, but what I am trying to achieve is the following:

I have two nested views:
- A list view
- A filter

The filter is a view that will allow users to filter the dataset that is displayed on the list.

We are implementing ui-router and in the resolve I resolve a call to the API (Restangular) into a variable named: "projects".  This is being injected into each of the views.

I can see that the state is shared since I was able to remove, edit and add from both views and the changes would reflect immediately.  However, when I try to execute a getList(), the shared state is removed.  

When I do something like this in either controller:

`projects[0].name ="HELLO"`

The change reflects in both controllers.

As soon as I execute the filter function on my FilterController, the reference is replaced.
(projects is injected from the resolve)

**FilterController:**
`function filter(filter) {
            projects.getList(filter)
                .then(function (data) {
                    projects = data;
                })
        }`

This will update the data only for the filter controller.

Now when I execute this again:
`projects[0].name ="HELLO"`

The change is not reflecting in both controllers, but only on the one.

Hope this makes sense.

**Comment by bostrom** [comment]
Closing due to the nature and age of issue. Please consider the updated [issue guidelines](https://github.com/mgonto/restangular/blob/master/.github/ISSUE_TEMPLATE.md) and reopen if needed.
