### ISSUE TITLE
How uniTest custom Directive with Restangular??

### ISSUE THREAD

**Issue by Zacknero** [mgonto/restangular#1419]
Hi guys i have a problem to write unit-test with Restangular inside custom directive.
My directive is:
` angular.module("CommonBusInfo", []).directive("jeepMenu", ['Restangular', function(Restangular){
        // Runs during compile
        return {
            restrict : 'E",
            link : function (scope, element, attrs) {
                var _urlTemplate = '',_codApp = attrs.application;

```
            if(angular.equals(_codApp,'gaps') || angular.equals(_codApp,'lirico') || angular.equals(_codApp,'topolino')){
                var utente = scope.userLogged;
                Restangular.one('users', utente.codUtente).one('readers', 'menu').one("commands", "menu")
                    .get()
                    .then(function (data) {
                        scope.loadingPercentage += 20;
                        scope.staticMenuTest = data.bodyResponse.dataWorkFlow.innerMenu;
                        _urlTemplate = 'components/commons/menu/menuDynamicView.html';
                    },function(err){
                        scope.loadingError = true;
                    });
                scope.staticMenuTest = [];
            }
            else{
                scope.loadingPercentage += 20;
                scope.staticMenuTest = '';
            }

            scope.getContentUrl = function(){
                return _urlTemplate;
            }
        },
        template: '<div ng-include="getContentUrl()"></div>'
    };
}])`
```

My file template index.html is:
`<jeep-menu application="{{codAppDirective}}"/>`

So how i can write best unit-test??

Thanks guys!

**Comment by bostrom** [comment]
The most convenient way to unit test Restangular services are by setting up mock endpoints using $httpBackend. Search the Internet for examples, or post your question on [StackOverflow](http://stackoverflow.com/search?q=restangular) for more detailed answers. 

There's also already a question regarding this among the old issues: https://github.com/mgonto/restangular/issues/98#issuecomment-19091163
