### ISSUE TITLE
{ responseType: 'arraybuffer' } results in empty buffers

### ISSUE THREAD

**Issue by GideonPARANOID** [mgonto/restangular#1422]
I'm developing a node app where I pull down a zip & unzip it in memory, so am needing to make a request to the file on the server & have the content up-front.

```
const result = await Restangular
  .withHttpConfig({ responseType: 'arraybuffer' })
  .one('test.zip')
  .get();
```

The problem is that this resolves to an empty array (not even a typed one). On inspecting this in a response interceptor, I can see that the `ArrayBuffer` is populated as expected, but here `result` is empty. I wrote a hack in my own code to move the buffer to a sub-property of the response & it preserves it fine, though I obviously need to address it differently after that.

```
Restangular.addResponseInterceptor((data, operation, what, url, response) =>
  response.config.responseType === 'arraybuffer' ?
    { buffer: data } : data);
```

Obviously, that isn't a good solution. I suspect that the issue arises with the Restangularisation of the response, which only happens on finishing the response interceptor.

**Comment by GideonPARANOID** [comment]
I see that this comment on another issue  https://github.com/mgonto/restangular/issues/833#issuecomment-52437828 suggests that writing that interceptor is the correct way to manage this. Should this be the case? It doesn't feel very good.

**Comment by bostrom** [comment]
If @mgonto says so, then that's the case.
