### ISSUE TITLE
Dist folder hasnt been updated

### ISSUE THREAD

**Issue by Zander1983** [mgonto/restangular#1425]
The code in the dist/ folder hasn't been updated in 8 months. Is this be design? I want to use the method customPATCH(), which exists in src/ but not in dist/.....

**Comment by madflow** [comment]
The last release is from February: https://github.com/mgonto/restangular/releases. The dist folder contains releases. Hence 8 month.

**Comment by bostrom** [comment]
1.6.0 now released, i.e. dist folder updated.
