### ISSUE TITLE
How to pass multiple params in Restangular

### ISSUE THREAD

**Issue by martin2630** [mgonto/restangular#1427]
i need something like this

/events/5/conferences/?fields=pk,name,date

i have this:

Restangular.one('events', 5).getList('conferences', {fields: ['pk', 'name','date']}).then(function(conferences) {
                    console.log(vm.conferences);
});

the result show me only the date. 

Can you help me? 

Regards!

**Comment by bostrom** [comment]
Try `Restangular.one("events", 5).all("conferences").getList({fields: "pk,name,date"})`.
