### ISSUE TITLE
 unable to send params to the rest api

### ISSUE THREAD

**Issue by ksvasu4u** [mgonto/restangular#1429]
Hi,
I need to send credentials as parameters to the rest functionality, below is the url required 

**http://localhost:8082/springRest1/helloRest/authenticate?username=""&password=""**

but the URL which is getting framed during the call is below 

http://localhost:7001/http://localhost:8082/springRest1/helloRest/authenticatspringRest1/helloRest/authenticate

the coding part for that is 

```
                   var path ='http://localhost:8082/springRest1/helloRest/authenticate'; 
        var params = {"username":uname,"password":pword};

        Restangular.allUrl(path).post(params).then(function(response){
            console.log(response);
        },function(error){
            console.log(error);
        });
```

AS the url which is framed is getting wrong its give me 404 error
could any body help me on this please ?  thanks in advance

**Comment by bostrom** [comment]
As stated in the docs

> allUrl(route, url): This creates a Restangular object that is just a pointer to a list at the specified URL.

the allUrl method takes the route and the URL, so modify your code to use

```Restangular.allUrl('/', path)```

and it should at least generate the correct URL. 

Also according to the docs

> post(elementToPost, [queryParams, headers]): Creates a new element of this collection.

you should try 

```.post({}, params)```

to send the credentials as query parameters.

Recap:

```
Restangular.allUrl("/", path).post({}, params).then(function(response) {
  console.log(response);
}, function(error) {
  console.log(error);
});
```
should do the trick.
