### ISSUE TITLE
Have a progress bar with Restangular file upload using formData

### ISSUE THREAD

**Issue by demonmind** [mgonto/restangular#1431]
I have a restangular request that sends a file with formData to a remote api endpoint.

Is there a way I can track the upload progress in Restangular?

**Comment by bostrom** [comment]
[This](http://stackoverflow.com/questions/25859505/restangular-is-it-possible-to-have-a-progress-bar) might help. Otherwise, just Google it. 

Please consider the updated [issue guidelines](https://github.com/mgonto/restangular/blob/master/.github/ISSUE_TEMPLATE.md) and reopen if needed.
