### ISSUE TITLE
Please add setPlainByDefault to d.ts file

### ISSUE THREAD

**Issue by SayusiAndo** [mgonto/restangular#1432]
Hi, 

I would like to ask you to add setPlainByDefault method and its type information to restandular.d.ts file, under restangular.IProvider.

Thanks,

András

**Comment by bostrom** [comment]
There's no `restandular.d.ts` file, nor `restangular.IProvider` in this project. Please explain.

**Comment by bostrom** [comment]
Closing due to lack of info. Reopen if you can provide more info.
