### ISSUE TITLE
Restangular.setPlainByDefault is not a function

### ISSUE THREAD

**Issue by Temoto-kun** [mgonto/restangular#1443]
I've read https://github.com/mgonto/restangular/pull/1184 saying that the PR has been merged. However, when I try to use `setPlainByDefault`, it doesn't exist neither in the source nor in the binary files. Perhaps the way on how to achieve this has been changed, or maybe the PR wasn't fully integrated? I've looked into the docs and the method is still there. The version is 1.5.2 at the time of posting.

**Comment by madflow** [comment]
The 1.5.2 release is from February 2016. The PR was merged in August 2016.

**Comment by bostrom** [comment]
Released in 1.6.0.
