### ISSUE TITLE
add support for matrix parameters

### ISSUE THREAD

**Issue by cthiebaud** [mgonto/restangular#1447]
> Matrix URL notation is an idea first floated in a [1996 proposal](https://www.w3.org/DesignIssues/MatrixURIs.html) by the founder of the web, Tim Berners-Lee.
> 
> Although matrix notation never made it into the HTML standard, it is legal and it became popular among browser routing systems as a way to isolate parameters belonging to parent and child routes. 

(quote from [angular.io docs](https://angular.io/docs/ts/latest/guide/router.html))

FYI There is a node.js matrix parser implementation [here](https://github.com/duaraghav8/matrix-parser).

I understand that full support might be a bt far fetched. Is there any way to produce matrix-complientURLs with the current Restangular, maybe using interceptors ? 

I more or less tried it, but could not made it, but my knowledge of Restangular is rather basic. I am happy to get guidelines if this is possible.

thanks

**Comment by bostrom** [comment]
There's a PR (https://github.com/mgonto/restangular/pull/1070) open about matrix URLs. Can you have a look at that?

**Comment by bostrom** [comment]
Closing since also duplicate to https://github.com/mgonto/restangular/issues/968.
