### ISSUE TITLE
Calling getList() retunrs data collection and Restangular internal methods

### ISSUE THREAD

**Issue by highiq** [mgonto/restangular#150]
---
## OVERVIEW

This is my first attempt using Restangular and my first attempt to call my own REST url returns my data objects along with the internal Restangular methods which are passed to my grid view. Am I doing something wrong with calling my data with the all and getList()?

---
## REST Url

http://localhost:9000/api/datatable/json/0
## Returns:

[{Id: "1",
Name: "abc",
Source: "http://www.abc.com",
DateCreated: "01/01/2010",
Active: "true"},
{Id: "2",
Name: "xyz",
Source: "http://www.xyz.com",
DateCreated: "02/02/2010",
Active: "false"}]

---
## Config Section

RestangularProvider.setBaseUrl('/api');

---
## Controller Section

$scope.myData = Restangular.all('datatable/json/0').getList();

---
## HTML Output

My grid view is filled with unreadable ... and the word Id and All and thats it. I can see when I debug the returned data that my two json objects are there as objects but there are also a bunch of methods returned as well.

**Comment by ongeri** [comment]
You can get the plain original response by doing Restangular.stripRestangular(elem) This may be useful if you want to post the response back after some edits but you don't want to post with the restangular properties
