### ISSUE TITLE
Delete / application/json

### ISSUE THREAD

**Issue by ctjhoa** [mgonto/restangular#159]
Hi,

First of all very nice work, I love your module.
As I love it, I used it a lot :) and find something strange:

On the same object I use both PUT and DELETE actions.
With PUT my HTTP header Content-Type is set to "application/json" which is ok
but with DELETE Content-Type is set to "text/plain".
I don't understand why DELETE should be a text/plain as it's called on a js object.

My server accept only application/json content-type and I wanna be sure that's normal behavior before to create custom deletes ?

Thanks

**Comment by volkerrichert** [comment]
But content will be send inside a delete request (1.4.0) So it would be good to have application/json as content type
