### ISSUE TITLE
Sending authorization header along with a Restangular call - Not global??

### ISSUE THREAD

**Issue by iangregsondev** [mgonto/restangular#160]
Hi there,

I have implemented 2 Restangular services, 1 is the pure Restangular that i will use to send across my token and the other is what I have called AuthRestangular where I need to build the Authorization header.

I did get it to work.. using the following but I think this is changing it on a global scale, which i believe is going to affect my standard Restangular injected variable.

```
            var encoded = base64.encode('userb:userb');
            $http.defaults.headers.common.Authorization = 'Basic ' + encoded;
```

I did try the following new method but I think i am calling it wrong...

```
           AuthRestangular.setDefaultHeaders({'Authorization': 'Basic ' + encoded });
```

It doesn't give me an error but it doesn't seem to be sending the header across, my rest service never detects it.

Any ideas ? I can't seem to find any examples.

Thanks

**Comment by ricker07** [comment]
hi mailmrmanoj,

is apiKey: token, auto generated?

**Comment by dvolaart** [comment]
I've got the same issue with version 1.4.0, is there already a solution for this problem?

**Comment by billmcknight1953** [comment]
For people not seeing the auth header in their api calls (even though they have used Restangular.setDefaultHeaders),  make sure you distinguish the preflight or OPTIONS request from the request itself.  Preflighted requests never send an auth header. You can read  https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS.  to learn about them.  Obviously, your API needs to handle an OPTIONS request without expecting an Auth  header.

**Comment by gravisrinivas** [comment]
I am still facing this issue? Did anybody find a solution. Ok even if it's a temporary one also.

**Comment by billmcknight1953** [comment]
Just use Restangular.setDefaultHeaders to set your authorization header.  It should work, if you are using a newer version of Restangular.  But please note that **before** the authorization header is sent as part of the real request, a pre-flight check is done to see what sort of authorization is even required.  This pre-flight request doesn't have an authorization header.  See [https://github.com/mgonto/restangular#setdefaultheaders](url)

**Comment by gravisrinivas** [comment]
Hi Bill ,
Thanks for the reply.
I am using restangular 1.5.2 . The problem is when I am making a restangular call after setting headers using Restangular.setDefaultHeaders on the header with name Authorization is missing and changing to undefined. The other headers are remaining intact. But I want to set a token for the header 'Authorization'. Can you please help me with this.

**Comment by yaoelvon** [comment]
The RestangularProvider.setDefaultHeaders will work for requests made via Restangular only.
While $http.defaults.headers.common will work on all requests made via $http including Restangular requests, because Restangular also use $http behind the scene.

**Comment by raihanorium** [comment]
No solution yet?
