### ISSUE TITLE
How can i put something with post data instead of query params?

### ISSUE THREAD

**Issue by scarletsky** [mgonto/restangular#163]
In my case, I want to make a request like PUT /user/123 and post some import data to backend.

In $resouce, i can do it like this:

``` javascript
.factory('Test', function ($resouce) {
     return $resource('/user/:userId', {}, { update : 'PUT' })
})

Test.updae({ userId : 123 }, { pw : 456 }, function () { something })
```

In restangular, I try to do it like this:

``` javascript
Restangular.one('user', 123).put({ pw:123 })
```

but the result is `PUT /user/123?pw=123`. This is not suitable for me.
I just want to `PUT /user/123 and POST data { pw : 123 }`.

Is there any solution?
Thx!

**Comment by rafialikhan** [comment]
@mgonto - only option 2 works for POST. Thanks 
@nodesocket - works
