### ISSUE TITLE
addRestangularMethod difference paramter orders based on safety of HTPP Method

### ISSUE THREAD

**Issue by rynz** [mgonto/restangular#171]
Consider we have an API Endpoint `POST /comments?m=delete` that accepts an array of comment id within the POST request.

`?m=delete` is to tell the API we are invoking a special method on the comments resource 'delete' and we will pass the array of id in the body of the POST request.

The special method can be created by:

``` javascript
RestangularConfigurer.addElementTransformer('comments', true, function(comments) {
  comments.addRestangularMethod('remove', 'post', undefined, {m: 'delete'});
  return comments;
});
```

If we call `Restangular.all('comments').remove()` we indeed get `POST /comments?m=delete` but as soon as we start adding in parameters `Restangular.all('comments').remove([5, 18, 42])` the URL becomes `POST /comments?0=5&1=18&2=42`.

Thus we lose our special `?m=delete` and parameters are being added to the query string rather than the body of the POST request.

Bug or what am I doing wrong?

**Comment by WaseemBepari** [comment]
how to use remove if url is 192.168.1.1:8000/timelog/list/145?projectId=12
