### ISSUE TITLE
remove method is hanging pending

### ISSUE THREAD

**Issue by devmondo** [mgonto/restangular#193]
hi, 
when i do for example 
listItem.remove(); 
chrome keeps hanging until i refresh the page

Side note : i have to admit that i have came to see restangular like 3 or 4 times and could not understand the benefit until i played with the code and now i say wow you are genius, i makes life so much easier and code more concise, thanks for this awesome library

**Comment by jasmeetssalech** [comment]
How can I pass single parameter say an Integer in customPost and remove?
say a replacement of this:
http://localhost:8080/addClass/'+$scope.classID

Thanks

**Comment by rhodul** [comment]
It does not work. It still sends {} as payload, and what is worse, it sends Content-Type:text/plain;charset=UTF-8.

**Comment by ezk84** [comment]
Also run into the `Content-Type: text/plain;charset=UTF-8` issue with version 1.5.1 of restangular, this causes problems with my server.

**Comment by MRHarrison** [comment]
This doesn't seem to work for me either.  Also, setRequestInterceptor is deprecated.  My loadbalancer doesn't accept DELETE requests with payloads.

```
RestangularProvider.setRequestInterceptor(function(elem, operation) {
  if (operation === "remove") {
     return null;
  } 
  return elem;
});
```

Is there another solution?

**Comment by kamleshkrjha** [comment]
**setRequestInterceptor** is deprecated [see here](https://github.com/mgonto/restangular#setrequestinterceptor)

**addRequestInterceptor** works.

    
     RestangularProvider.addRequestInterceptor(function(elem, operation, what, url) {

                if (operation === "remove") {
                    return null;
                }

                return elem;

            });
