### ISSUE TITLE
Restangular + Angular Kendo (Telerik's Kendo UI) setting datasource

### ISSUE THREAD

**Issue by Griimm** [mgonto/restangular#240]
Hi everyone, I'm very new to Angular JS and Restangular but so far i'm learning through research and experimentation.

Part of what i'm trying to achieve is integrating Angular JS, Restangular and Kendo UI. I'm following this as my source of information on integrating Angular JS and Kendo UI: http://kendo-labs.github.io/angular-kendo/#/. 

I have the grid generating correctly but for the life of me I cant get my datasource to display correctly that's being returned by this restangular call:

var allProducts = Restangular.all("products").getList();
var localDataSource = new kendo.data.DataSource({ data: allProducts  });
$scope.products = localDataSource;

My data returns as follows:

[{"Id":1,"Name":"Tomato soup","Category":"Groceries","Price":1.39},{"Id":2,"Name":"Yo-yo","Category":"Toys","Price":3.75},{"Id":3,"Name":"Hammer","Category":"Hardware","Price":16.99}]

I can bind that just fine to a table's ng-repeat but it just does not want to bind to as this DataSource.

If i try this instead it works just fine:

var manualProducts = [{
            "Id": 1,
            "Name": "Tomato soup",
            "Category": "Groceries",
            "Price": 1.39
        }, {
            "Id": 2,
            "Name": "Yo-yo",
            "Category": "Toys",
            "Price": 3.75
        }, {
            "Id": 3,
            "Name": "Hammer",
            "Category": "Hardware",
            "Price": 16.99
        }];
    var localDataSource = new kendo.data.DataSource({ data: manualProducts });
    $scope.products = localDataSource;

I'm struggling to figure out how i "clean" my result set being returned by Restangular into an acceptable plain JSON format which Kendo can accept as a datasource.

I would really value any advice!

**Comment by salmanAhmad143** [comment]
Hi there i am stuck while using restangular. Actually my problem is that i am using populate in my query and i want to add where condition on populated collection. 
Below is my code.

Restangular.all('companyproduct').getList({company_id:companyID, populate:'product_id',is_archived:0}).then(function(data){

});

How can i give condition on product_id collection field. I want to populate only those records who is_archived:0

Please help me any one??

**Comment by pbosin** [comment]
Salman, IMHO you will be better off, if after getting list from Restangular, you set it in Kendo dataSource via data(...) method and then apply dataSource.filter: http://docs.telerik.com/kendo-ui/api/javascript/data/datasource#methods-filter
