### ISSUE TITLE
Options property clobbered by restangular

### ISSUE THREAD

**Issue by tyson-benson** [mgonto/restangular#266]
I have a resource which has a property named options. This property is being overwritten by restangular's options method on the restangular element. What should I do? For now i have commented out the options method in restangular.

**Comment by achadee** [comment]
+1 on this issue. I think you guys should prefix all your methods in a later release

**Comment by thescopan** [comment]
+1

**Comment by sherbrow** [comment]
+1

**Comment by daviesgeek** [comment]
That sounds like a possibly good idea. In my own REST library, I've actually put all the methods on the prototype so that they don't get broken like this.

There are a lot of things to take into account though if the method signatures are changed. It would probably required a 2.0 release.
