### ISSUE TITLE
PUT as collection method

### ISSUE THREAD

**Issue by chekyassine** [mgonto/restangular#286]
my server REST api PUT route is /objects (not objects/{id}) because it accepts json data representing the object to be updated, including its id.

The problem in restangular is that put is an element method, meaning that it will always have routes like /objects/{id} witch is not suitable for me (and for other people as well) because the server update method gets the id from the object received in the request body.
an example of my java server update method : 

@Consumes({ MediaType.APPLICATION_JSON })
@PUT
public Response update(SomeObject object) {
          String objectId = object.getId(); // No need for the id in the url !
        ...
}
I think there should be some kind of configuration for the put method to fit to those needs.

I hope I make sense

**Comment by alohaq1dev** [comment]
editUser.put().then(
				function(res) {
					console.log(res);
				},
				function (error) {
					console.log(error);
				});

**Comment by grabbou** [comment]
```js
editUser.put().then(function() { });
```

**Comment by sokeno** [comment]
Hi i have the same problem with laravel(method not allowed)
function update(taskId, data, onSuccess, onError) {

        Restangular.all("api/task").customPUT(data, taskId).then(function (response) {
       // Restangular.one(data, taskId).customPUT(data, 'api/task').then(function (response) {

            onSuccess(response);

        }, function (response) {

            onError(response);

        }
        );

    }

here is my service function

$api->put('task/{id}', 'App\Api\V1\Controllers\TaskController@update')

and my api laravel route

what am i not doing right?
