### ISSUE TITLE
Impossible to pass JSON data in a customPOST request?

### ISSUE THREAD

**Issue by akarelas** [mgonto/restangular#320]
Also I believe the documentation of customPOST's parameters is wrong.

When I do this:

``` javascript
Restangular.one('users', 'alex').customPOST(1, 2, {a: 3}, 4)
```

I get a POST request to this URL: https://local.talkspot.org/api/users/alex/1

`1` (according to the documentation) should be the element, not the path, hence I believe the documentation is not correct. Also `{a: 3}` turned into a request header, rather than `params` as stated in the documentation, so that further strengthens my belief that the documentation is not good.

Finally, How do I pass my custom JSON in this customPOST? I don't see this option anywhere. There should be a place, shouldn't there?

**Comment by DeepakChuahan** [comment]
Still facing the same issue in v1.5.1,  I passed the json in first argument but not sent in the request , req.body is empty.
