### ISSUE TITLE
How to do a simple POST?

### ISSUE THREAD

**Issue by andreasadk** [mgonto/restangular#331]
I have some trouble understanding POST and PUT. The examples seem to revolve around first fetching an object and then posting to it?
How can I do a POST to a service, where I do not specify id, just the body as JSON?

``` javascript
$scope.saveClaim = function() {
    var newClaim = {
        "customerRegNo": $scope.policy.customerRegNo,
        "claimDate": $scope.claimDate,
        "coverage": $scope.coverage,
        "siteOfDamage": $scope.incidentDescription,
        "policy" : $scope.policy
    };
    Restangular.one('claim').post(newClaim);
};
```

Something like this. Basically a simple POST to this url: http://localhost:8888/myapp/api/claim

**Comment by nathekame** [comment]
hi @mgonto i am facing a similar issue to the one above, i keep getting 400(Bad Request) when i try to POST data from angular frontend to NodeJs backend using Restangular 

i tried what @Matheno suggested but it did not solve the problem, initially i had problem with CORS which i sorted out... but till now i havent been able to solve the problem... Please what im i doing wrong? if u need further information about my code im here...

http://stackoverflow.com/q/40634791/1615867

NOTE: i have modified my controller script to what @Matheno suggested...
