### ISSUE TITLE
Non-integer ID field + PUT - property not being escaped

### ISSUE THREAD

**Issue by migajek** [mgonto/restangular#337]
ID field for my REST resource is the string Name property, thus I have:

```
.factory("Dormitory", ['Restangular', function (Restangular) {
    return Restangular.withConfig(function (RestangularConfigurer) {
        RestangularConfigurer.setRestangularFields({ id: "Name" });
    });
} ]);
```

GET works fine, when called like this:

`Dormitory.one("dormitory", encodeURIComponent($route.current.params.Id)).get();`

unfortunately, when I later edit (through form with ng-model) the retrieved object and want to store it in the backend, I call

`$scope.dorm.put().then(_redirect);`

which causes the invalid url to be built, i.e. the "Name" property should be escapeURIComponent-ed, but they're not. In my case, when I type "Akademik #1" as the Name, I end up with the PUT request being sent to the following URI:

`PUT http://localhost:8080/dormitory/Akademik%20`

as you can see, the Name property is being trimmed after first space.

**Comment by RichardBradley** [comment]
This is still broken for me -- you escaped the ID on [line 674](https://github.com/mgonto/restangular/blob/de8a48bf4c13587b9ba5a975b5be1b0c3dd7a4bd/src/restangular.js#L674) but not on [line 663](https://github.com/mgonto/restangular/blob/de8a48bf4c13587b9ba5a975b5be1b0c3dd7a4bd/src/restangular.js#L663)

**Comment by RichardBradley** [comment]
Actually, I think the bug I am experiencing is in `ng-admin`, sorry.

**Comment by RichardBradley** [comment]
I think my specific bug was caused by `ng-admin`, not Restangular, sorry.
Line 663 does look bugged to me though.
