### ISSUE TITLE
Exclude parent resource in PUT/POST/DELETE ONE requests

### ISSUE THREAD

**Issue by thebne** [mgonto/restangular#345]
When having a single, unique object, and using PUT/POST/DELETE method, it doesn't make sense to send the request to /parent/_id_/resource/_id_. Most interfaces (such as flask_restless) only implement GET views for such URLs. There should be a `setParentless` equivalent option that disables it.

Referring to issue #154, `setParentless(['resource'])` is "ugly" because of several reasons:
- That means to have logic within my app initialization code, that refers to one of my models (does app.js need to know that some module named "resource" exist?)
- It requires me to explicitly define a list where this issue is relevant, while it seems to be relevant in most cases.
- There are cases where an object should be parentless in one situation and parentful in another. For instance, GET /parent/_id_/resource is okay, as well as GET /parent/_id_/resource/_id_, but PUT /parent/_id_/resource/_id_ (for the very same resource) may be unacceptable.

**Comment by pdorgambide** [comment]
+1 
I am aggre with @thebne the url resource endpoints on DELETE, PUT operations are the easiest form: 
`/api/people/2` instead of using the parent resource prefix.
Do you have this option implemented or in the roadmap?
