### ISSUE TITLE
Which the HTTP method use instead of LINK / UNLINK?

### ISSUE THREAD

**Issue by sorbing** [mgonto/restangular#362]
I need a method (RESTful API) that to link/unlink relationship between the two entities, example it's `User`, `Comment`.
I'm use:

``` javascript
Restangular.one('users', 2).get().then(function(resource) {
  $scope.user = resource;
});

Restangular.one('comments', 4).get().then(function(resource) {
  $scope.comment = resource;
});

$scope.user.link('comments', $scope.comment.id);
```

Which the HTTP method you recommend use instead of LINK/UNLINK? These HTTP methods seem to be out of date , right? Thanks.

**Comment by akovalyov** [comment]
Guys, any information or updates about it?

**Comment by stalinkay** [comment]
@mgonto, please implement LINK/UNLINK.
