### ISSUE TITLE
Is there a way to use object.put without copying the object first

### ISSUE THREAD

**Issue by langerc** [mgonto/restangular#367]
I load an object from a server, everything plays nice. After modifying the object the values are changed but put sends the original version back to the server.

If i use Restangular.copy() and send the copied object everything is fine.

Is there a way to do a put or post without copying the object? so load, modify, save.

Could not find any hints till yet, any answer would help.

Thanks for the excellent Job!!

**Comment by softwords** [comment]
Striking similar problems in May 2016, but I think the problem with something like this:

```
      this.myObject.post().then(function(resp) {
            angular.extend(this.myObject, resp);
        });
```

is that the ```resp``` is itself Restangularized, and so ```angular.extend``` copies over the new definitions of angular methods (```post()``` etc). So for that reason, subsequent calls to 

```
this.myObject.post()
```
just keep posting back the first response.

Easy fix:

```
      this.myObject.post().then(function(resp) {
            angular.extend(this.myObject, resp.plain());
        });
```
