### ISSUE TITLE
Why `POST` and `DELETE` request call `OPTIONS`?

### ISSUE THREAD

**Issue by AlmogBaku** [mgonto/restangular#368]
I'm trying to do `DELETE` or `POST` request to some singleton rest object, and the result is that it actually calling `OPTIONS` instead(which failed, because I have no such a method in my API)..

``` javascript
$scope.$$event=API.one('events', id);
$scope.$$rsvp = $scope.$$event.one("rsvp");

//trying to request REMOVE action to /events/:id/rsvp
$scope.$$rsvp.remove();
```

How can I pass it?

**Comment by danrevah** [comment]
@aroban your solution also worked for me 
Thanks.

**Comment by pratikpawarnasik** [comment]
I got this issue. i am using codeigniter in backend api but still not fixed. Tell me proper solution for this.
