### ISSUE TITLE
POST  / don't send the full restangular object

### ISSUE THREAD

**Issue by andrenerd** [mgonto/restangular#370]
Martin,

maybe it's not an issues at all, i'm just trying to find a way to remove excessive data (body) from post requests.

so, if i do:
Restangular.one(resource, item.id).post()
it sends (as data) the whole Restangular object with all the methods, not just properties {id:...}.

to prevent it i have to tweak the code a little:
Restangular.one(resource, item.id).post('', {id:...})

could Restangular not to send the whole object? 

thanks,
savva

**Comment by vaibhav-jain** [comment]
Unable to post 

```
        var payload = {
          "title": newTodo,
          "is_completed": false,
        };
        TodoService.one(hash).post(payload).then(
          function (success) {
            console.log(success);
          }
        );
```
On Server:

```[23/Jun/2016 15:37:21] "POST /v1/todos/2753469ff7ae/[object%20Object]/ HTTP/1.1" 405 41```


If I do TodoService.post(payload) then POST request if in proper shape but URL is 404 which It should.

My Issue is How do I post to ```/v1/todos/hash/``` I can't change the URL to ```/v1/todos/``` . Can someone tell me how do I post???

**Comment by JulioC** [comment]
I got around with this using `element.post(undefined, payload)`

Anyway, Restangular should allow us to do that more easily.

**Comment by vaibhav-jain** [comment]
And I got around using `customPOST(payload)`
