### ISSUE TITLE
Canceling restangular call

### ISSUE THREAD

**Issue by j-walker23** [mgonto/restangular#387]
Hey man,

I have a situation where i need to cancel a restangular call. I have a server side search going on. On every key press i make a call. Sometimes previous key search responses come in after the latest search response and the old data overwrites the new data on the screen.

I found this snippet below. But i am not sure if i can pass the timeout object through restangular to $http service. 

If thats even the best way, basically just wondering how you would handle this problem with your stuff?

Thanks for any help!

the link to this is http://stackoverflow.com/questions/13928057/how-do-to-cancel-an-http-request-in-angularjs

var canceler = $q.defer();
$http.get('/someUrl', {timeout: canceler.promise}).success(successCallback);
// later...
canceler.resolve();  // Aborts the $http request if it isn't finished.

**Comment by rck935** [comment]
@jaydiablo thanks for .withHttpConfig method. But if I need to timeout my restangular post request after certain milliseconds e.g. 500ms how to configure that? is it possible?
Thanks in advance.
