### ISSUE TITLE
CORS AngularJS and Restangular

### ISSUE THREAD

**Issue by jhiemer** [mgonto/restangular#405]
Hi there,
I tried to upgrade to AJS1.2 today and ran into the issue that I was not able to call CORS resources. It worked without any problems before. Even adding: 

``` javascript
RestangularProvider.setDefaultHeaders({
    "Content-Type": "application/json",
    "X-Requested-With": "XMLHttpRequest"
  });
```

Did not solve the issue. Are there any other things I need to take care of?

**Comment by spaky08** [comment]
https://gist.github.com/danharper/06d2386f0b826b669552
