### ISSUE TITLE
multipart form data submit with restangular

### ISSUE THREAD

**Issue by zoheb** [mgonto/restangular#420]
I have to submit a form which includes a user selected file to the server. I can get this working using $http directly as below,

```
    var fd = new FormData();
            fd.append("profile",angular.toJson(profile));
             fd.append("file", file);
            return $http.post("/server/api/profile/me/bio", fd, {
                withCredentials: true,
                headers: {'Content-Type': undefined },
                transformRequest: angular.identity
            });
```

I tried to do the same submit using restangular as below
    return userAPI.one('me').customPOST(fd,"bio",{}, {'Content-type':undefined});

However this doesn't do the multipart submit correctly and attempts to send a empty payload request. I suspect this is because I need to specify the transformRequest flag to address this issue: https://github.com/angular/angular.js/issues/1587

Is there a way to do set a request transformer just on this request? 

Thanks

**Comment by gen4sp** [comment]
It still here, guys. I have same problem with 1.4
What i can do with it?

````
Restangular.all('points').withHttpConfig({transformRequest: angular.identity}).customPOST(formData,'',undefined,{'Content-Type': undefined}).then(function (response) {
```

**Comment by ncourtial** [comment]
Hi,
All seems to be OK when you don't set global default headers.
When adding the following default values in config step, form data are posted without requested headers : form-data and boundary  but with 'application/json'.
RestangularProvider.setDefaultHeaders({
                "Content-Type": "application/json",
                "X-Requested-With": "XMLHttpRequest"
            });

When removing  "Content-Type": "application/json" from config , customPOST(formData,'',undefined,{'Content-Type': undefined}) does its stuff.

Any idea?

Many thanks in advance.

Cheers

**Comment by Tallyb** [comment]
+1

**Comment by diosney** [comment]
Hi!

I'm trying to implement this but can't figure it out with my use case since it seems that `Restangular.service('entities')` doesn't have a valid `.withHttpConfig()` method.

How can achieve that functionality using the service approach?

Thanks in advance.

**Comment by diosney** [comment]
It seems that `Restangular.service('entities')` only exports `getList(), get(), post()` methods :(

Nevertheless, in my Entities service I changed `Restangular.service('entities')` for `Restangular.all('entities')` and the file upload worked like a charm.

**Comment by steinerj** [comment]
I'm having the exact same issue with using httpConfigs for objects created with .service

I have provided a PR, because I think this is a bit of a inconsistency. See #1068

**Comment by aug-riedinger** [comment]
Thanks for comments and code snippets. It helps quite a lot!

I have a working implementation but I'm halfly satified because it uses Base64-encoded data upload which seems less efficient than Multipart Upload, and would not work with heavy file (as far as I understood). 

@deltaepsilon I tried your code but it only sends the file itself, whereas I would like to update my user during the same call. It should be possible as that's what a regular form does.

Here's the code:

View:
``` 
<img ng-src="{{user.avatar}}" class="img-circle img-responsive">
<input type="file" name="avatar" onchange="angular.element(this).scope().updateClientImage(this.files)" />
<input class="btn btn-success btn-lg" type="submit" value="Save" ng-click="save_user()" />
```

Controller:
```
        $scope.save_user = function() {
            var deferred;
            // if ($scope.file) {
            //     var formData = new FormData();
            //     formData.append('user[avatar]', $scope.file);
            //     deferred = $scope.user.withHttpConfig({transformRequest: angular.identity}).customPUT(formData, undefined, undefined, {'Content-Type': undefined});
            // } else {
                deferred = $scope.user.put();
            // }
            deferred.then(function(res) {
                console.log(res.msg);
            }, function(err){
                console.log('An error occured:');
                console.log(err);
            });
        };

        $scope.updateClientImage = function(files) {
            $scope.file = files[0];
            var reader = new FileReader();
            reader.onload = function(e) {
                $scope.user.avatar = e.target.result;
                $scope.$apply();
            };
            reader.readAsDataURL($scope.file);
        };
```

Simply calling `$scope.user.put()` sends a Base64-encoded image as a user.avatar attributes, which works Ok in my backend.

But how can I have a `customPUT` that sends over the user attributes + the formData - user.avatar (otherwise it is sent twice)?

```
 $scope.user.withHttpConfig({transformRequest: angular.identity}).customPUT(formData, undefined, undefined, {'Content-Type': undefined});
```

I'll report final working solution. Thanks a lot!

**Comment by ArthurianX** [comment]
Any progress on this? I'm having the same problem. :(

**Comment by Waxo** [comment]
I'm using jsPDF to create a PDF then i try to submit it with `return Restangular.all('users').one('pdf', id).withHttpConfig({transformRequest: angular.identity}).customPOST(fd, 'submit', undefined, {'Content-Type': undefined});`  
But the header is application/json and i need a multipart/*
If i force the Content-Type to multipart/form-data i have a boundary problem. Is there a workaround ?

**Comment by rhodul** [comment]
@ncourtial, the default headers problem is fixed like so:
                postFile: function (dataUri, path, keyName, fileName) {
                    var authenticatedHeaders = angular.extend({},
                        DEFAULT_HTTP_HEADERS,
                        {"x-authtoken": localStorage.authtoken});
                    authenticatedHeaders["Content-Type"] = undefined;
                    var formData = new FormData();
                    var blob = dataURItoBlob(dataUri);
                    formData.append(keyName, blob, fileName);
                    // kill default headers
                    var restangularRoute = Restangular.withConfig(function (RestangularConfigurer) {
                        RestangularConfigurer.setDefaultHeaders(authenticatedHeaders);
                    });
                    return restangularRoute.one(path).withHttpConfig({transformRequest: angular.identity})
                        .customPOST(formData, '', undefined, authenticatedHeaders);
                }

**Comment by suvarnajayanth** [comment]
if i set ["Content-Type"] = undefined, It calls webservice , but i i want to send text data in other language (utf-8) it won't receive as expected in Rest api

**Comment by andrzej-aa** [comment]
I found a workaround for setting default headers. Instead of setting undefined, set a function returning undefined:
```
RestangularProvider.setDefaultHeaders({
  'Content-Type': 'application/json'
});


return API.all(UPLOAD_RESOURCE)
  .withHttpConfig({transformRequest: angular.identity})
  .customPOST(file, 'image', {}, {
    'Content-Type': () => {
      return undefined;
    }
  });
```

**Comment by abbood** [comment]
I can't seem to have it work.. this is what I'm using:

I'm using restangular 1.51 with angular 1.6. My html looks like this
 
    <input type="file" name="file" />

and the angular code:


    let directive = {
      ..
      link: (scope, element, attrs) => {
            let inputElement = angular.element(element[0].querySelector('input'));
            inputElement.bind('change', function () {
            var formData = new FormData();
            formData.append('file', inputElement[0].files[0]);
    
            API.all('stores/csv').withHttpConfig({transformRequest: angular.identity})             .customPOST(formData,'' , undefined,
              { 'Content-Type': undefined }).then((response) => {console.log(response);
              });
        });
      
 
laravel code:


    public function upload(Request $request)
    {

        $this->validate($request, [
            'file' => 'required',
            'type'  => 'in:csv,xls,xlsx',
            ]);

        $file = $request->input('file');
        var_dump($file);
        return response()->success(['file' => $file]);
    }

thing is the $file here is appearing as an empty array in the laravel dump. The documentation is pretty bad on this. Ideas?


  [1]: https://github.com/mgonto/restangular

**Comment by abbood** [comment]
so basically i had to brute force the content-type to `application/x-www-form-urlencoded`.. 

btw i'm using restangular 1.51.. more details here https://stackoverflow.com/questions/49077674/how-to-upload-files-with-angular-using-cors/49081727#49081727
