### ISSUE TITLE
ErrorInterceptor not works for 401?

### ISSUE THREAD

**Issue by AlmogBaku** [mgonto/restangular#425]
I'm trying to define ErrorInterceptor, but it seems it never called:

``` js
RestangularConfigurer.setErrorInterceptor(API.errorHandler);
API.errorHandler = function(result) {
            console.log(result);
            if([401,403].indexOf(result.status)!=-1) { // @TODO check if it works on the device
                $phonegap.fbLogout();
                return false;
            }
        };
```

why is that? am I doing right?

thanks!

**Comment by enapupe** [comment]
I'm having a similar issue right now..  But it is getting to the error part in "plain" angular $http. What could that be?

**Comment by enapupe** [comment]
Nope, actually I had more than one call to  `Restangular.setErrorInterceptor()` and only the first one was handling the error.
