### ISSUE TITLE
Bulk remove

### ISSUE THREAD

**Issue by lxsameer** [mgonto/restangular#430]
Hi and thanks for restangular

Here is a question: How can i make a DELETE request and remove a collection ?

or: How can i make a DELETE request and pass an array of object ids as its parameters ?

**Comment by markusfalk** [comment]
I still get an error when using several()

```javascript
// postBody = [1,2,3];
Restangular.several(resource.url, postBody.toString).delete().then(function(foo) {
   console.log(foo);
});
```

Error msg:
```bash
Uncaught TypeError: Restangular.several(...).delete is not a function
```

Any idea?

**Comment by GeBeater** [comment]
@markusfalk Use remove() instead of delete() .
