### ISSUE TITLE
Allow caching for individual urls

### ISSUE THREAD

**Issue by stuplum** [mgonto/restangular#441]
Is it possible to enabled caching for individual urls? Or alternatively, disable for certain urls.

My use case is that I want most urls to static data to be cached, however I have updates being applied to customer data as an example which I don't want to be cached.

I have seen the issue #133 suggesting to invalidate the cache using an interceptor, and whilst this might work for me, I think it would be wrong to invalidate the entire cache.

**Comment by cjroth** [comment]
+1 for the single url request. It would be nice to have the ability to ignore caching for a single request.

**Comment by Arkanain** [comment]
you can use this way(set true / false val for cache variable will turn on / off caching) before requests which you need to cache / uncache:
School.withHttpConfig({cache: false}).get('users')
