### ISSUE TITLE
Promises not working in angular for restangular collections

### ISSUE THREAD

**Issue by melcher** [mgonto/restangular#451]
Sorry if this is a duplicate, I didn't see any open tickets addressing this.

So, with restangular 1.1.8 and angular 1.2.0-rc2 one could do something like this:

```
  $scope.items = Restangular.all('items').getList();
```

and in a view you could ng-repeat over items and it would "just work". The $scope.items would initially contain a promise but would resolve into the array from the response, and the view would see the change and update.

In angular versions 1.2.1-1.2.3 this promise never seems to resolve in the view, and "$scope.items" just contains the unresolved promise. This means you have to do:

```
  Restangular.all('items').getList().then(function(result){
    $scope.items = result;
  }
```

So my question is, how is it supposed to work? If only the second form is supported, I'm  looking at having to rewrite much of my app, so I'm _hoping_ that this is either a bug in angular or restangular that, once resolved, will work either way.
I created a plunkr to illustrate the point. You can change the angular version to 1.2.0-rc2 and see the working list.
http://plnkr.co/edit/M6Rk0abb92diszip1lwz?p=preview

Thanks for any help!
- Graham

**Comment by radams0x** [comment]
Hi @mgonto!
First off, thanks so much for all your fine work on Restangular!

// I have this code, which works, and I later assign the return value to a property on $scope, to be consumed by an angular template:

return this.restangular.all(this.route).getList(params).$object;

however, I would like to be able to iterate the object and do some work with it before returning it to angular; I tried the following:

this.restangular.all(this.route).getList(params)
.then(function (data) {
    var result = data;
	// do something with result before passing to angular template
	// this works, I can access the data in result
    return result; // this doesn't work, in that angular no longer renders the template that this gets passed to 
});

Any advice would be much appreciated!
Thanks!!
