### ISSUE TITLE
How to manage responseType = 'blob'

### ISSUE THREAD

**Issue by montesq** [mgonto/restangular#479]
I call an API endpoint that returns a file. As you can see below, I success to implement a full javascript snippet to download the file using xhr :

```
    window.URL = window.URL || window.webkitURL;

    var xhr = new XMLHttpRequest();
    xhr.open('GET', Restangular.one('attachments', idAtt).getRestangularUrl(), true);
    xhr.setRequestHeader('X-Auth-Token', 'token');
    xhr.responseType = 'blob';

    xhr.onload = function(e) {
        if (this.status == 200) {
            var blob = this.response;
            var url= window.URL.createObjectURL(blob);
            window.open(url);
        }
    };
    xhr.send();
```

But now, I would like to use only Restangular instead! However, it doesn't seem to be possible setting the responseType to 'blob'...
I've tried to convert the text response to blob, but I finally get a corrupted file at the end.
Has someone already solved this kind of problem?

**Comment by devjon** [comment]
@vishwajeetv : did you manage to download the pdf file.

**Comment by devjon** [comment]
@vishwajeetv : stuck on the same problem. Any heads up ??

**Comment by felixfbecker** [comment]
responseType is just what the type the response should be in your JS. Blob is for everything binary like a pdf or image. You can download it for example by constructing a link with `URL.createObjectUrl()` and then pointing an `<a download="">` to it or by `window.open()`, display it in iframe, etc etc

**Comment by Dmitry9999** [comment]
In my case `$window.open()` resulted in "popup blocked" browser message, but
`$window.location.href = url;` worked perfectly (no popup)

**Comment by luanntvn** [comment]
blob would work but I use arraybuffer to be able to decoded error response to json if any

Restangular.one('downloadPDF')
            .withHttpConfig({ responseType: 'arraybuffer' })
            .get()
            .then(function (response) {
                var fileName = 'file.pdf';
                var a = document.createElement('a');
                document.body.appendChild(a);
                a.style = 'display: none';
                var file = new Blob([response], {type: 'application/pdf'});
                var fileURL = (window.URL || window.webkitURL).createObjectURL(file);
                a.href = fileURL;
                a.download = fileName;
                a.click();

                (window.URL || window.webkitURL).revokeObjectURL(file);

            }, function (response) {
                //error
            });

**Comment by doubl3p** [comment]
you also can use the paket "angular-file-saver" and use it in the "then block":

```
Restangular.one('downloadExcel')
  .withHttpConfig({ responseType: 'arraybuffer' })
  .get().then(function(response) {
  
    var blob = new Blob([response], {
      type: "application/vnd.ms-excel ; charset=charset=utf-8"
    });
    saveAs(blob, "MyExcel.xls");

}, function (response){
  //error
});

```

type depends on your case: excel, pdf, etc.

**Comment by kennlebu** [comment]
Using `withHttpConfig({responseType: 'blob'})` kept giving me an error `The selected responseType is not supported`

`withHttpConfig({responseType: ResponseContentType.Blob})` worked for me instead.
