### ISSUE TITLE
Automatically retry GET requests with a response of 502/503 a number of times

### ISSUE THREAD

**Issue by bmarini** [mgonto/restangular#528]
I'm looking to add in some auto retry logic for all my GET requests. It looks like I could almost implement this in a response interceptor if I had access to the request data as well.

Since I'm pretty unfamiliar with this codebase I'm looking for some suggestions as to the right place to implement this. Any thoughts?

**Comment by niemyjski** [comment]
But if you retry a request then the interceptors don't run on the second request? When I get a status code of 0 (servers down or soem other error), I want to retry the request x times before I hit my error interceptors.. Is there away to have the interceptor called and pass it extra data like how many times it's been run? @mgonto  Can this be something that's added to 2.0?
