### ISSUE TITLE
$watch not working with $object

### ISSUE THREAD

**Issue by mattschultz** [mgonto/restangular#532]
If I use $object, $watch only gets triggered when the empty array is created. It doesn't get triggered again when the array is populated with the result.

Here's an example:

```
scope.posts = Restangular.all('posts').getList().$object

scope.$watch 'posts', ->
  console.log scope.posts
```

All that gets logged to the console is:

```
[]
```

Using $watch without $object works fine, however:

```
Restangular.all('posts').getList().then (posts) ->
  scope.posts = posts

scope.$watch 'posts', ->
  console.log scope.posts
```

```
[]
[Object, Object, Object, ...]
```

**Comment by derekgreer** [comment]
Perhaps there's something wrong with this example, but your suggestion doesn't appear to work.

http://plnkr.co/edit/5GOpSUFqefri8dvYPgRS?p=preview
