### ISSUE TITLE
Problem with .put after using angular.copy

### ISSUE THREAD

**Issue by cjwprostar** [mgonto/restangular#55]
While converting from $resource to Restangular, I came across an issue. When using angular.copy on a Restangularized object, modifying the copy, then doing a .put on the copy, the .put sends the old data. Should I be copying the object in a different way or is this a bug?

``` javascript
Restangular.one('thing', id).get().then(
    function(thing) {
        // thing.name is "Old Name"
        var thingCopy = angular.copy(thing);
        thingCopy.name = "New Name";
        thingCopy.put(); // Puts thing.name as "Old Name"
    }
);
```

**Comment by dboczek** [comment]
Also something like below will still not work.

    Restangular.extendModel('elements', function(model) {
        var updateOnSuccess = function(element){
            return function(updatedElement,a,b){
                angular.copy(updatedElement, element);  // next put sends old data
                // Restangular.copy(updatedElement, element);  // not implemented
            };
        };
        model.save = function() {
            this.is_saving = true;
            if(this.is_new){
                this.post().then(updateOnSuccess(this));
            } else {
                this.put().then(updateOnSuccess(this));
            }
        };
        return model;
    });

I want to "replace" element with updated version from server. I thought I could use `angular.copy` as it seems to be desinged for that:
> `angular.copy(source, [destination]);`
> If a destination is provided, all of its elements (for arrays) or properties (for objects) are deleted and then all elements/properties from the source are copied to it.
But I run into bug mentioned here. **The problem is `Restangular.copy` doesn't support `destination`.**
