### ISSUE TITLE
Undefined attributes are dropped when saving (POST, PUT)

### ISSUE THREAD

**Issue by adrianboimvaser** [mgonto/restangular#553]
Let's say I want to save this object:
```
{
  foo: 1,
  bar: "...",
  baz: undefined
}
```
I would expect this to get sent:
```
{ "foo": 1, "bar": "...", "baz": null }
```
Instead what gets sent is:
```
{ "foo": 1, "bar": "..." }
```

**Comment by grabbou** [comment]
Explanation:

> JSON.stringify() converts a value to JSON notation representing it:

Properties of non-array objects are not guaranteed to be stringified in any particular order. Do not rely on ordering of properties within the same object within the stringification.
Boolean, Number, and String objects are converted to the corresponding primitive values during stringification, in accord with the traditional conversion semantics.
If undefined, a function, or a symbol is encountered during conversion it is either omitted (when it is found in an object) or censored to null (when it is found in an array).
All symbol-keyed properties will be completely ignored, even when using the replacer function.

**Comment by mark0978** [comment]
That's not at all what I found.  I found that it was the bind you were doing when the object was received.  I documented it pretty clearly above.  If you angular.copy an object, the methods within the object are still BOUND to the original.  One of my ways around this is to never use those methods, but to use the service that returned them.  This means I can get and put via the service and not thru the object.

I'm not doing JSON.stringify anywhere and that is NOT this bug.

**Comment by grabbou** [comment]
I was replying to the original bug as title of this issue states. After looking into your comments, there's a second one introduced here which is about angular.copy breaking the application. Not sure if this can be easily fixed (there's a Restangular.copy method for doing so) because of `_.bind` as you explained. In V2 this is going to be changed completely and angular.copy will be working flawlessly due to prototype nature of new version. I will create a new issue for this particular problem in order to keep things clean, how that sounds?

**Comment by mark0978** [comment]
I've worked around it as indicated above, I don't find the serviceName.save(obj) to be a big problem, so all the decorating restangular does for me is really just useless overhead.  I know there was talk about putting all the methods on the prototype, but I really wonder if the methods need to be there at all.

**Comment by dmeneses** [comment]
I'm having the same problem, i had a model like this:
```javascript
var sale = {
car: {}, //Restangularized collection
owner: {}, //Restangularized collection
id: 13213,
startDate: 
...
}

sale.put();
```
And when I do the put stuff the owner it deleted. Strange thing that the car is not.

**Comment by mark0978** [comment]
You can't do any form of copy of the object.  There is a bind that is bound
to the original data. Obj.put has a different this than you are expecting.

**Comment by dmeneses** [comment]
mmm not sure, but at the end I did this:

```javascript
 service.update = function (sale) {
  Restangular.one(resource, sale.getSetId()).customPUT(sale);
 };
```

with that the car and owner object were save successfully.

**Comment by mark0978** [comment]
Yea, that will do it too

**Comment by LeonardoGentile** [comment]
@grabbou why was this closed? I stumbled upon this bug after using `angular.copy()`. Did you open another issue specifically for this?

This prevent this use case: I want to clean up/transform the data before sending them but I don't want to modify the original scope object linked to the user inputs. The logical way would be to `angular.copy($scope.formData)` but doing so break things.

**Comment by LeonardoGentile** [comment]
Nevermind, I found a solution by reading the docs: https://github.com/mgonto/restangular#copying-elements
