### ISSUE TITLE
Default and customizable error messages

### ISSUE THREAD

**Issue by alex88** [mgonto/restangular#566]
Hello, I'd like to be able to have a default notifications in case of service errors while being able to override it if I want to notify the user with custom messages.

As a starting point I've overridden the errorInterceptor in my `configure` stage of the app:

``` coffee
App.config ['RestangularProvider', (RestangularProvider) ->
  RestangularProvider.setErrorInterceptor (response, promise) ->
    toastr.error 'There has been an error contacting the server, please try again'
]
```

This way on every error toastr shows the default notification. Now, since I want to be able to override the message or do custom actions, I've tried to use the promise trying to get it returned valued using `promise.reject()` so in my controllers I could:

``` coffee
UserService.get('me').then (user) ->
    $scope.user = user
    $scope.userLoading = false
  , ->
    toastr.error 'There has been an error loading the current user!'
    false
```

and checking the return value in my default error handling I'm able to skip the default behaviour. However from promise.reject() I always get undefined as result, is there a way to achieve this?

**Comment by btiernay** [comment]
@mgonto Why not run the local error handlers first, before the global handler? This is how most web frameworks work as it allows the local context to override the default global context.
