### ISSUE TITLE
How can i Cancel the request

### ISSUE THREAD

**Issue by zakialidev** [mgonto/restangular#589]
### This code is not Canceling the request, why?   
         RestangularConfigurer.addFullRequestInterceptor(function (element, operation, route, url, headers, params, httpConfig) {
                var defer = $q.defer();
                defer.reject();
                httpConfig.timeout = defer;
                return {
                    element: element,
                    headers: headers,
                    params: params,
                    httpConfig: httpConfig
                };
            });

**Comment by daviesgeek** [comment]
That's the correct way to cancel the request.

See also https://github.com/mgonto/restangular/issues/1377#issuecomment-226625799
