### ISSUE TITLE
responseExtractor not parsing reponse when there is an HTTP error

### ISSUE THREAD

**Issue by SimplGy** [mgonto/restangular#597]
I have configured Restangular with the intent to intercept both successful responses and error responses.

```
RestangularProvider.setResponseExtractor(responseHandlerProvider.parse)
RestangularProvider.setErrorInterceptor(responseHandlerProvider.parseError)
```

I would like to be able to transform both the success and error response so that my application always sees the same shape object (in my case, success unwraps a response so that a `data` property is the only thing that my application code sees). I can unwrap successful responses, but on HTTP error, my application code is sent the fullResponse, and this makes error handling on a model-by-model basis complex.

Is there a way to parse the response even in an error case? The value I return from my `errorInterceptor` is not used for anything, I think.

**Comment by ashokmahla** [comment]
i am using 1.6 version getting status -1 in ther error response when my service is down in case of 503

**Comment by ashokmahla** [comment]
Hi @mgonto  can you please help .
