### ISSUE TITLE
Document examples of using array functions on RestangularCollections

### ISSUE THREAD

**Issue by boxxxie** [mgonto/restangular#611]
this would be really helpful.

`collection.map/filter/whatever` breaks the RestangularCollection.

i know there is a function on Restangular to turn an array into a RestangularCollection, but i would like to see an example of it.

thank you :)

**Comment by grabbou** [comment]
Closing in favour of #953

**Comment by kogratteMarket** [comment]
Closed in favour of #953, closed too, without any change... We need some documentation, really :)
