### ISSUE TITLE
customPUT not working with false value passed as elem

### ISSUE THREAD

**Issue by jpeters-programmer** [mgonto/restangular#634]
My desire is to call
url: /myapi/mycontroller/0/setAtRisk
payload: false

I try to do this via the following
Restangular.one("mycontroller", 0).customPUT(false, "setAtRisk");

I get correct url, incorrect payload
url: /myapi/mycontroller/0/setAtRisk
payload: {id: "0"}

The work around is to pass in a string for false values like this:
Restangular.one("mycontroller", 0).customPUT("false", "setAtRisk");

**Comment by mikola-spb** [comment]
Hey, I've just faced with the same problem. I think this can be improved. CustomPUT works fine with boolean true, it also works with numbers, but doesn't with false value. IMO it's natural to pass boolean variable to this method.
I found a line in elemFunction(operation, what, params, obj, headers) function, which I think does the check. 
>  var callObj = obj || this;
