### ISSUE TITLE
Restangular.stripRestangular not striping everything

### ISSUE THREAD

**Issue by JonCognioDigital** [mgonto/restangular#644]
Hi,

I noticed that some functions such as customGETLIST, customOperation, doGETLISTand withHttpConfig  are still atached after using Restangular.stripRestangular.

I know another issue was posted here https://github.com/mgonto/restangular/issues/518 and the issue was fixed a couple of months ago but I downloaded the lasted version from the dist folder and it still seems to be happening.

Anyone else got this working?

**Comment by rysilva** [comment]
There should be a way to add methods which are not included in the raw element.  One of the reasons that I chose restangular is the ability to extend the model with functions that run business logic.  Restangular should not attempt to send these functions to the server on a save (which is what currently happens, but they get stripped out by $http).

So sure, keep extendModel as a way to manipulate the data model attributes, but there should be some other way to do this, like maybe an overload of `addRestangularMethod`.

```javascript
Restangular.extendModel('employees', function(model) {
    model.addRestangularMethod('isStaff', function(employee) {
        return employee.employed && employee.admin;
    });
});
...
if ( employee.isStaff() ) { ... }
```
