### ISSUE TITLE
Iterating over object with restangularized data

### ISSUE THREAD

**Issue by max** [mgonto/restangular#649]
I'm [requesting an endpoint](https://devcenter.heroku.com/articles/platform-api-reference#config-vars-info) with Restangular that returns an object with key value pairs:

``` js
// /apps/:appName/config-vars
$scope.configVars = Restangular.one('apps', $routeParams.objectName).one('config-vars').get().$object;
```

The response from the API looks as follows:

``` json
{
  "FOO": "bar",
  "BAZ": "qux"
}
```

In my view I would like to iterate over `configVars` like so:

``` html
<li ng-repeat='(key, value) in configVars'>{{key}}: {{value}}</li>
```

Unfortunately because the data is restangularized this will also iterate over the keys added by Restangular. To work around this I'm adding a new key to the response with the original non-restangularized data with `setResponseExtractor` so that I can do the following:

``` html
<li ng-repeat='(key, value) in configVars.originalElement'>{{key}}: {{value}}</li>
```

That seems like a bad workaround for this type of situation. How should I be doing this?

**Comment by KhaledMohamedP** [comment]
We can also call `.plain()`

```javascript
.then(function(response) {
    $scope.configVars = response.plain();
  });
```
