### ISSUE TITLE
selfLink leading slashes

### ISSUE THREAD

**Issue by cstephe** [mgonto/restangular#658]
An API I'm using internally is giving back its selfLink as

ref:'/users/12345'

I'm using:
```
   Restangular.setRestangularFields({
      selfLink:'ref'
     });
Restangular.setBaseUrl(hostUrl + "/someservice/v1/");
```
However its generating the url as
```
   http://0.0.0.0/someservice/v1//users/12345
```

I seems to me that what we are doing isn't that odd to attempt.  Is there a way of dealing with this or is our selfLink just wrong.

**Comment by grabbou** [comment]
This is now being solved in #1045 that uses pretty nice reggae replace to get rid of // slashes in the URL.  Copying @jleskovar code to the above solution as a additional test case.
