### ISSUE TITLE
Laravel pagination.

### ISSUE THREAD

**Issue by bweston92** [mgonto/restangular#662]
No Laravel pagination support, how hard would this be to put in?

**Comment by javalight** [comment]
all you have to do with laravel is return $query->paginate(5)->getCollection() this with auto json everything, then for your ajax request set the url parameters as ?page=2 or ?page=3 ...

**Comment by bweston92** [comment]
@javalight I was using "dingo/api" which follows JSON rest specification. Which is more then just returning the collection.

**Comment by essivision** [comment]
[http://stackoverflow.com/questions/34535178/how-to-force-restangulars-getlist-to-work-with-laravel-5s-pagination-object](http://stackoverflow.com/questions/34535178/how-to-force-restangulars-getlist-to-work-with-laravel-5s-pagination-object)
