### ISSUE TITLE
Use of prefixed internal attribute names

### ISSUE THREAD

**Issue by szmeti** [mgonto/restangular#675]
Let's say my server returns the following object:

{ id: 1, name: "name", route: "ABC" }

Restangular then adds its own methods and properties to the object. "route" is used by Restangular, so it shadows my route property. Even if I called Restangular.stripRestangular(response), it would remove "route" from the object.

It would be better if Restangular used some prefix internally to avoid name clashes.

**Comment by davinkevin** [comment]
Issue closed, but I think the original request should be integrated in the Restangular framework.

Working with a prefix helps a lot, I'am working in a project right now with a name conflict with Restangular...
