### ISSUE TITLE
Unwrap a promise with AngularJS 1.2

### ISSUE THREAD

**Issue by bmw0128** [mgonto/restangular#678]
I have an output of the following from my Go code, using json.Marshal(myData):
`{"0":"hypertension","1":"blue","Name":"hypertension","Color":"blue","route":"rest/diseases","parentResource":null,"restangularCollection":true}`

This is just one record, and I want a page in AngularJS to just display the "Name" field, so I did the following in the page:

````
<div ng-controller="SecondCtrl">
    <div ng-repeat="disease in allDiseases">
        {{disease}}
    </div>
</div>
````

My controller is:

````js
function SecondCtrl($scope, Restangular){
var diseases = Restangular.all('rest/diseases');
diseases.getList().then(function(dis){
        $scope.allDiseases = dis;
    })
};
````

My page displays the following, I'd like to know how to get just "hypertension" to display:
hypertension
blue
blue
hypertension
true
rest/diseases

**Comment by grabbou** [comment]
Closing. Please feel free to comment with code samples and we will investigate that again.
