### ISSUE TITLE
module should return from closure

### ISSUE THREAD

**Issue by jadrake75** [mgonto/restangular#68]
It would be helpful now that you are using a closure for the restangular file to have it return module from the closure.  This would allow cases like when used with RequireJS to treat the inclusion of restangular as an object rather than undefined (allowing you to get the name for example).  Here is an example of an application using requireJS + restangular....

(function (define) {
    'use strict';

```
define([
    'angular',
    'js/controllers',
    'restangular',
], function (angular, controllers, restangular) {
    var modules = [controllers.name, 'restangular'];
    myApp= angular.module('myApp', modules);
    ...
    return myApp;
   )};
```

})();

So in this case, since upon loading the restangular.js file restangular doesn't return the module, it is loaded, but is not an object so I couldn't do things like restangular.name for example (in the above example it is undefined)

If you are not using requireJS there would be no impacts that I am aware of, and it would be a benefit with requireJS.

**Comment by mazhimazh** [comment]
i want to know,how to inject restangular using requirejs?

**Comment by subramn** [comment]
Even i am trying to do this. how to use restangular with requirejs
