### ISSUE TITLE
Collection.clone() gives previous version

### ISSUE THREAD

**Issue by miraage** [mgonto/restangular#684]
I've next code

``` javascript
$scope.curEdit.put().then(function(newElem) {
    // Replacing new elem in collection, np, works fine
    $scope.rows.splice($scope.curIndex, 1, newElem);

    // Shows fresh updated collection
    console.log($scope.rows);
    // Shows previous version of collection
    console.log($scope.rows.clone());
});
```

What I do wrong? How can I latest collection data via clone()?

// upd
This works fine.

```
Restangular.copy($scope.rows);
```

**Comment by cstephe** [comment]
Quick question is collection clone supposed to also keep the "this" wiring of its elements intact?  I'm using an older version and noticed that it only seems to fix itself. I wanted to make sure I understood the way its supposed to work.

**Comment by mattdarveniza** [comment]
FYI this also occurs for `Collection.plain`, presumably because it also uses `clone`under the hood. Any progress on this by the way? Seems to have been kicking around for a while now?
