### ISSUE TITLE
Add configuration option to use plain() by default

### ISSUE THREAD

**Issue by pleerock** [mgonto/restangular#696]
I like restangular, but there are some features I dislike. I don't like that restangular appends its own methods to the objects and arrays(!). I know this is one of the principle of restangular, but personally I don't think that its a RIGHT principle. 

I like new `plain()` method you've introduced, but I also would like to see the option to configure it to use it by default, e.g. `getList`, `get` methods return promise that will contain already a plain object.

**Comment by wibobm** [comment]
+1

**Comment by chuckweinberger** [comment]
+1

**Comment by eventures-io** [comment]
+1

**Comment by tylercollier** [comment]
:+1: 

I've been (minimally) using this library for 6+ months without realizing the 'big idea' of 'restangularization', which is a very cool idea but surprises you when you look at your $http response and it has all these restangular properties bundled in.

I think that fact should be mentioned in a "Critical/Minimum understanding" section of the README, not because the way it works by default is "wrong", but because people like me will miss out on perhaps the coolest part of the project.

**Comment by nevcos** [comment]
I think that in a MVC application (where there should be a service class responsible for making the CRUD) the "retangularization" doesn't help, instead it creates problems [clobbering properties](https://github.com/mgonto/restangular/issues/266) and when making debugging hard.

I suggest that the "restangularization" should be an option that, If turned off, the object should be clean as it come from the server (without any clobbered properties nor additional methods).

**Comment by rafaelmotta** [comment]
+1

**Comment by jebarjonet** [comment]
+1

Would be especially useful when having a bunch of conditions on object size sent from server, currently needs a `plain()` for each of them.

**Comment by marcdexet-cnrs** [comment]
+1

Restangular is wonderful but in most of the cases we don't need all the methods. 
A raw response without unnecessary methods additions will be a very appreciated feature.

**Comment by dparnane** [comment]
+1

**Comment by mspoerer** [comment]
+1

**Comment by lougaou** [comment]
:+1:

**Comment by zorzysty** [comment]
:100:

**Comment by agustinjlopez** [comment]
+1

**Comment by daviesgeek** [comment]
This is addressed in this PR #696

**Comment by chillyistkult** [comment]
Would be cool to have this merged as soon as possible.

**Comment by poppahorse** [comment]
+1

**Comment by daviesgeek** [comment]
Merged. Will be in a release shortly.

**Comment by DmitryGonchar** [comment]
@daviesgeek Any chance of the new release?
