### ISSUE TITLE
Save method work incorrectly after cloning.

### ISSUE THREAD

**Issue by aantipov** [mgonto/restangular#697]
Hi!
I tried to use new save() method, but unfortunately can't use it as I expected.
I have a service, that returned empty restangular object:

```
myModule.factory('dataItem', function(Restangular) {
 return Restangular.one('myRoute');
});
```

Then in my contoller I use it to create new item:

```
var item = dataItem.clone();
item.save();
```

But this initiate PUT request, not POST, as I expected.
After some research I realized that the problem is with `fromServer` property - after cloning  it's value become true, ie `dataItem.save()` initiate POST request, but `dataItem.clone().save()` initiate PUT request.

**Comment by grabbou** [comment]
To be merged this weekend! :1234:

**Comment by tachang** [comment]
Was this merged?

**Comment by Szpadel** [comment]
+1
Waiting for merge

**Comment by novgo** [comment]
+1

**Comment by hwhelchel** [comment]
+1

**Comment by mgibas** [comment]
Same in scenario:
```javascript
var model = Restangular.one('models');
//POST as expected
model.save().then(function(id){
    model.id = id;
});

...

//POST instead of PUT
model.save();
```

after this line:
```javascript
company.fromServer = true;
```
```save()``` works as expected.

**Comment by muenchdo** [comment]
Any reason why this hasn't been merged yet?

**Comment by meishier** [comment]
Any reason why this hasn't been merged yet?

**Comment by shulcsm** [comment]
bump

**Comment by kenfdev** [comment]
+1

**Comment by soyuka** [comment]
Same here

#684 related

**Comment by k1ng440** [comment]
@mgonto please merge this

**Comment by mudassir0909** [comment]
Is there anything we can do to get this issue fixed(even if it means to come up with a different solution if the repo owner is not happy with the one presented above)? I really hate forking & maintaining my own version

**Comment by daviesgeek** [comment]
@mudassir0909 I was waiting for #938 to be rebased, but it looks like the author of the PR has disappeared 😢

**Comment by mudassir0909** [comment]
ah too bad! but those are like 4 line changes, how about we add those changes in our repo? I could generate a PR if you want me to

**Comment by daviesgeek** [comment]
Sure thing that would be awesome!!

**Comment by mudassir0909** [comment]
Here you go https://github.com/mgonto/restangular/pull/1417

**Comment by mudassir0909** [comment]
#1415 this one has tests as well
