### ISSUE TITLE
Send array of params on GET

### ISSUE THREAD

**Issue by tyler-boyd** [mgonto/restangular#700]
Hi, my issue is as follows:

I do a `GET` request where the parameters include arrays. Eg:

`GET /products?query=mug&categories=drinkware&categories=coffee`

The server sees:

``` ruby
PARAMS: 
{ 
"query" => "mug",
"categories" => ["drinkware", "coffee"]
}
```

How can I generate an address like that?

Currently I'm doing

`````` coffee
searchProducts: (query, categories) ->
      params = { query: query }
      _.each categories, (cat, index) ->
        params['categories'] = cat.name
      Restangular.all('products').getList(params)```

But this only sends the last category as the parameter. I also tried:

```coffee
    searchProducts: (query, categories) ->
      params = { query: query }
      _.each categories, (cat, index) ->
        params['categories[' + index + ']'] = cat.name
      Restangular.all('products').getList(params)
``````

But the server receives that as an array of hashes

``` ruby
{
"query" => "mug",
"categories" => { "0" => "drinkware", "1" => "coffee" }
}
```

Any advice would be greatly appreciated!

I know that I _could_ solve the issue by changing how I process the params (I could do a map down into an array, I could just do `categories=JSON.stringify(category_names)` in the client, but I'll bet there's a pretty solution I'm missing.

Thank you.

**Comment by CLOUGH** [comment]
I recently ran into this issue recently and i had to a bit of research to solve the problem. So for anyone with the same issue here is a solution i came up with.

If you want to pass an array of items with angular all you need to do is store the property name with an open and close square brace:

```
$scope.filters = {
   title : "string",
   'type[]': ['Full Time','Part Time']
};

Restangular.all('jobs').getList($scope.filters);
```
I hope this help.

**Comment by lognwching** [comment]
@CLOUGH thanks a lot man! Your comment just saved me! :raised_hands: :rocket:

**Comment by gbittmann** [comment]
Using the method described by @CLOUGH the braces are converted to %5B%5D, which does not work.

`$scope.filter = {
            'tags[]': ['live','design']
            };
        Restangular.all('search').getList($scope.filter);`

**Comment by daviesgeek** [comment]
@gbittmann Can you please provide a live example on Plunker, JSFiddle or the like?

**Comment by KKrisu** [comment]
I confirm the issue that @gbittmann has.
In my case, I've just passed simple key: array format:
```js
const params = {
    country: ['fr', 'pl'],
};

Restangular.all('jobs').getList(params);
```
This generates url with `&country=fr&country=pl`

**Comment by gbittmann** [comment]
Sorry. I lost track of this somehow.

https://plnkr.co/edit/Ig2qWW4FfL2r1nkIpqtx?p=preview

You can open up the console and see that it is posting the encoded version of the brackets. Which is probably what it should be doing according to the http spec, but causes issues when you are posting to a php server and getting to accept that as an array. An option to force the encoding to not happen would probably be the only thing that could be done. The current behavior seems to be correct.
