### ISSUE TITLE
Custom error processing in addResponseInterceptor

### ISSUE THREAD

**Issue by gregbty** [mgonto/restangular#703]
I just started using Restangular a couple of days ago. In my backend service when there is an internal error, session expiration, or any other error that occurs within the flow of the application I usually send a custom error object back via a status 200 response. 

For example, when the user submits invalid data to the backend, instead of sending the following:

```
status: 500
statusText: "You have submitted invalid data."
```

I send:

```
status: 200
data: {
  status: 500,
  statusText: "You have submitted invalid data."
}
```

Is it possible to add an interceptor that would transition the "successful" response object into an "error" response via the addResponseInterceptor or any other method?

**Comment by maximveksler** [comment]
@mgonto 

You have missing ")" in your sample code:

```javascript
 RestangularProvider.addResponseInterceptor(function(data, operation, what, url, response, deferred) {
    // If conditions for reject are met run the following
    deferred.reject(data);
})
```
