### ISSUE TITLE
missing array on newResponse

### ISSUE THREAD

**Issue by SeppItv** [mgonto/restangular#730]
There is a missing line in the documentation. The originalElement array has to be initialized.

RestangularProvider.setResponseExtractor(function(response) {
  var newResponse = response;

newResponse.originalElement = [];

  if (angular.isArray(response)) {
    angular.forEach(newResponse, function(value, key) {
      newResponse[key].originalElement = angular.copy(value);
    });
  } else {
    newResponse.originalElement = angular.copy(response);
  }

  return newResponse;
});

**Comment by grabbou** [comment]
Closing due to lack of the response. Please comment when you have time and we will reopen to discuss it further. Thanks again for choosing Restangular :)
