### ISSUE TITLE
Cant build restangular with  browserify 

### ISSUE THREAD

**Issue by iancrowther** [mgonto/restangular#749]
Initially thought it was due to lodash not being included, but tries with a script tag and still no joy.

**Comment by grabbou** [comment]
Adding CommonJS/RequireJS support would be interesting. Something similar to what `ui-router` is doing along with publishing Restangular @ npm.

**Comment by jgoux** [comment]
Now that all the angular libraries are on NPM, it would be nice to add this little export. :+1:

**Comment by defel** [comment]
I agree. Many angular-libs and angular itself is npm-installable by now. 

Please add snippet as suggeted by @ludicast 

```javascript
var _ = window._ || require("lodash");
```

This should do the trick.

**Comment by gottfrois** [comment]
+1, would be nice to load restangular with

```js
angular.module('myApp', [require('restangular')])
```

You you guys are using webpack, you can expose lodash this way:

```js
require('expose?_!lodash')
```

**Comment by olsonpm** [comment]
+1

> Could you detail why you are trying to do so?

@pauldijou: I'm somewhat new to angular, but my understanding is that the angular way expects you to include each module separately in a different script tag via index.html.  Preferably there would exist a single script tag with your concatenated/minified scripts (assuming it is reasonable in size).

**Comment by nolazybits** [comment]
Coming from #1012 and wondering when Restangular will officially support requirejs.
Meanwhile is there any workaround?
Thanks!

**Comment by olsonpm** [comment]
@nolazybits - [newtriks' solution](https://github.com/mgonto/restangular/issues/749#issuecomment-47983835) is the correct way to go about it

**Comment by nolazybits** [comment]
Thanks @olsonpm, but I still can't figure it out...

This is my requirejs config
```
require.config({
    baseUrl: './',
    paths: {
        'angular': '<angular path>',
        'lowdash' : '<lowdas path>',
        'restangular': '<restangular path>'
    },
    shim: {
        'angular': {
            deps: ['jquery'],
            exports: 'angular'
        },
        'lowdash': {
            exports: '_'
        },
        'restangular': {
            deps: ['angular', 'lowdash']
        }
    }
})
```

and my main.js file is like this
```
define(['angular', 'restangular'], function(angular, restangular) {
    var app = angular.module('app', [
        'restangular'
    ]);

    //  this will fail, with 'Restangular: Error: Unknown provider'
    app.factory('test', ['Restangular', function (Restangular) {
        console.log(Restangular);
    }]);
}
```
Any idea... or better link to working examples?

Thanks!

**Comment by olsonpm** [comment]
If your problem is related to requirejs, then your best bet is to find help via stackoverflow.  The solution I gave is only relevant to browserify which I thought was what you were asking about.

I haven't messed with require.js in some time since I haven't come across any problems since using commonjs.

**Comment by episodeyang** [comment]
Personally I am switching from requirejs to browserify. It is a painful process, but it seems to be where things are heading.

**Comment by olsonpm** [comment]
@episodeyang - Depending on how far along you are in the migration process, you may find less friction using webpack.

**Comment by Sleepyowl** [comment]
Please fix NPM package by adding correct imports and exports.
Import lodash and export angular module's name as all official angular modules do.

**Comment by bholloway** [comment]
I love **Restangular** so I really wish it wasn't such a mess in **Browserify** and **Webpack**.

Unless I'm mistaken the `lodash` dependency in the **Restangular** `package.json` is pointless because the source code does not use it.

For consistency this needs to go. Or better yet be utilised per @ludicast's [suggestion](https://github.com/mgonto/restangular/issues/749#issuecomment-46250118), or some similar solution..

**Comment by nlitwin** [comment]
+1
I'm using Webpack and Angular and have spent hours trying to figure out how to include restangular using ES6 `import`.

**Comment by dalgard** [comment]
+1

**Comment by creimers** [comment]
+1 in 2016.

**Comment by dreef3** [comment]
If it helps someone, here's how you can use Restangular with Webpack:
```javascript
angular.module('app', [
    require('imports?angular=angular&_=lodash!exports?"restangular"!restangular')
]);
```

Same with ES2015 imports:
```javascript
import restangular from 'imports?angular=angular&_=lodash!exports?"restangular"!restangular';
angular.module('app', [restangular]);
```

[Exports loader](https://github.com/webpack/exports-loader) loader is optional in second case.

**Comment by bholloway** [comment]
Definitely #1284 is the way to go.

UMD is pretty much the 'everything to everyone' fix.

**Comment by joshmanders** [comment]
Since this talk is over a year old, and PR 3 months old with no clear direction of if it's going to land, I took some time today and made this https://github.com/joshmanders/restangular-umd

It takes the official release source file, removes the first and last lines, and wraps it in UMD support, I am using this without issues in Webpack.

**Comment by cypherq** [comment]
@joshmanders I've done same thing - thanks for publishing on NPM!

I also asked @mgonto about pull request state:
https://github.com/mgonto/restangular/pull/1284#issuecomment-194801698
