### ISSUE TITLE
Can't set authorization header

### ISSUE THREAD

**Issue by bazani** [mgonto/restangular#760]
I need to set a default header for basic http authentication. I set the header in a function that logs the user in my webapp but restangular don't send the authorization header. Even with the header hardcoded in the configuration section of the app the problem persists.
Here a plnk who illustrates my problem: http://plnkr.co/edit/FFKrlxRnVOfQ9I5V21yf?p=preview

Thanks for now.

**Comment by dhaowoods** [comment]
Hi, @mgonto I have set the basic authenticaion using RestangularProvider.setDefaultHeaders({'Authorization':'Basic '+btoa("username:password")});
However, the first time I open my app that used ui.router and restangular, the browser prompt for username and password, but subsequent actions that cause API request to mysql's http plugin do not cause browser prompt, even when I reload or open it in new tab, or open a new browser window while the first browser window is still opened, it is just happened when I open totally new browser window process, and launch my app the first time,, how could my app be wrong?

**Comment by billmcknight1953** [comment]
For cross-domain calls, I found that both Restangular, and even Angular's $http service, first do a preflight request. (OPTIONS request) (For more about preflight see the section on preflighted requests at https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)  The Authorization header is null on preflight requests, even if you've set default headers as pzaich does above . However, I found the header is present on the actual GET, POST, PUT, etc request in Restangular 1.4

**Comment by dhaowoods** [comment]
okey thank you :-D so, the server should not authenticate OPTIONS request?

**Comment by grabbou** [comment]
From spec http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0

When creating preflight request based on another request:

> Exclude the author request headers.
> Exclude user credentials.

**Comment by bazani** [comment]
Is there any example on how use CORS with Restangular? I'm kind newbie here. =/

**Comment by grabbou** [comment]
You should actually try to find "how to set up CORS with <name of your server framework here>". Restangular only builds URLs you query to get responses so it has nothing to do with CORS.
