### ISSUE TITLE
Second PUT call sends old data

### ISSUE THREAD

**Issue by miraage** [mgonto/restangular#772]
I receive data via `Restangular.all('notices').getList().$object`.
Then I do PUT request on some element - works as expected.
But other PUT requests on this element send old data.

What I do wrong?

**Comment by hartz89** [comment]
I was having this issue because I was using angular.copy() to copy an element into scope for editing prior to the PUT rather than using Restangular.copy().  There's a section in the docs about this.

**Comment by daviesgeek** [comment]
This sounds like a duplicate of #811. @miraage can you provide an example?

**Comment by daviesgeek** [comment]
I'm going to go ahead and close this. @miraage if there's still an issue, feel free to re-open the issue

**Comment by miraage** [comment]
@daviesgeek i've been figured out this issue by switching `$object` to `then(result => ...)`.
