### ISSUE TITLE
POST to undefined path

### ISSUE THREAD

**Issue by arg20** [mgonto/restangular#779]
In order to take advantage of the extended restangular model I have a code looking like this:

```javascript
$scope.things = Restangular.all('things').getList().$object;

$scope.newThing = Restangular.one('things');

$scope.saveThing = function () {
  $scope.newThing.save().then( function(createdThing) {
     $scope.things.push(createdThing)
  });
}
```

What I do there is once creation is successful, I add the `newThing` to the `things` array that I fetched upon controller creation, so I avoid asking for all things again to refresh the list. So far so good, the problem arises when I wish to edit this newly added thing:

```javascript
$scope.saveChanges = function(thing) {
  thing.save().then(function(){
    console.log('Thing saved');
  })
}
```

if i wish to update the newThing that I just posted to the server, the http method now should be `PUT`, and it is, but to the url: 

`http://localhost:8080/api/things/undefined/the-id-of-the-thing`

I am guessing that this is because the `save()` method returns a subresource of Thing (and i created the thing doing `Restangular.one('things')` without passing an id ), but this is a bit unexpected in my case. All I want to do is create a Thing, then post it, then once I get the Thing back from the server with its id, update it without restangular adding that undefined in the middle.

**Comment by Blaze34** [comment]
+1

**Comment by grabbou** [comment]
Using
```js
$newObject = Restangular.all('todos').post({objectToPost});
```
as per documentation solves the issue. Undefined appears because of wrong usage of `one()` that needs a second parameter `id`. Because of the fact it's not present, you get those undefined values.
