### ISSUE TITLE
Restangular sends empty {} request payload when removing object

### ISSUE THREAD

**Issue by gryphon** [mgonto/restangular#78]
Rails application crashes with message "The document "{}" does not have a valid root" when making simple object remove. 
Seems to be caused by {}:none request params which should not be included into DELETE request.

**Comment by netes** [comment]
Just for the record - `setFullRequestInterceptor` is deprecated, use `addFullRequestInterceptor` instead.

**Comment by Ahmedmousa20** [comment]
Where should I put this Code?

 RestangularProvider.setRequestInterceptor(function(elem, operation) {
  if (operation === "remove") {
     return undefined;
  } 
  return elem;
})
