### ISSUE TITLE
Remove method not sending as from data

### ISSUE THREAD

**Issue by ramesh-babu-ch** [mgonto/restangular#792]
Hi,
I am trying to send form data to server with DELETE request. 
I am trying remove(), customDELETE() methods to send form data to server but they are passed as query parameters instead of form data.

My code is as fallows:
var items = ['1','2'];
var data = {"deleteFlag": 'xx', "eventIdList": JSON.stringify(items)}
Restangular.service('events', Restangular.one('user', 12)).one().remove(data);

**Comment by grabbou** [comment]
@mgonto I think we should focus on supporting REST methods and leave more advanced usages up to users, especially when they have `customOperation` method :) 

To all - please refer to `customOperation` as @luto stated and follow the #930 as we are trying to sort out why `delete` has stopped working.
