### ISSUE TITLE
Restangular.copy not copying arrays inside restangular object

### ISSUE THREAD

**Issue by tomazahlin** [mgonto/restangular#800]
I have a restangular object, which has an array of more restangular objects.

console.log(originalData); // displays the object correctly.
var data = Restangular.copy(originalData);
console.log(data); // the main object is copied ok, but the children restangular objects in an array are not coppied, but are empty/defallt restangular objects.

The original object has a structure like this:

originalData.services[0].name; // name is ok
data.services[0].name // undefined

Can you help me solve this issue? Should I maybe not use the regular array to store subitems (services) and use something else? Thanks!

**Comment by daviesgeek** [comment]
Any update on this? @tomazahlin

**Comment by tomazahlin** [comment]
Unfortunately not. I am not working on a "restangular" project anymore.

**Comment by daviesgeek** [comment]
Okay I'll close this then.
