### ISSUE TITLE
Oauth2

### ISSUE THREAD

**Issue by marijang** [mgonto/restangular#801]
Can you give some best practise for oauth2 password grant type.

Tnx

**Comment by grabbou** [comment]
Google is your friend @marijang :)

One random result -> http://stackoverflow.com/questions/23896690/securing-oauth-clientid-clientsecret-in-angularjs-application

**Comment by fernandomoraes** [comment]
I'm working in a lib for this, take a look https://github.com/fernandomoraes/angular-implicit-oauth2

Sorry, but there's no doc in the moment ... So take a look at source...
