### ISSUE TITLE
How to get requested url + params called by $http ?

### ISSUE THREAD

**Issue by ArTiSTiX** [mgonto/restangular#803]
I need to obtain the URL, and the passed request params which is called by $http through Restangular.

I usually do:

```
Restangular.all(mymodel).getList(myparams).then(...)
```

But now I want to obtain the corresponding **URL + query params**, instead of playing it.

_Use case: User fills a form, with many filters, and want to choose between playing the request, or getting the url to get it himself._

**Comment by ptanov** [comment]
@ArTiSTiX , I know what you mean.
@mgonto is talking about the case where the elements have been previously gotten from the server whereas you're talking about constructing an URL without getting the element from the server.

I have faced the same problem and the solution I have found is to explicitly add the request parameters (there is one more solution at the bottom of this comment):

```javascript
var someUrlParams = {hello: "world"};
var endpoint = Restangular.all("someroute");
endpoint[Restangular.configuration.restangularFields.reqParams] = someUrlParams;
endpoint.getRequestedUrl() 

```

this will return `/someroute?hello=world`. I think this is what you expect.


Long story:
in https://github.com/mgonto/restangular/blob/e795cd3a39a395eac9b71febb45fa6334da37db3/src/restangular.js
config.restangularFields.reqParams is referenced in these two lines:

1) `function restangularizeElem(parent, element, route, fromServer, collection, reqParams) {` ( https://github.com/mgonto/restangular/blob/e795cd3a39a395eac9b71febb45fa6334da37db3/src/restangular.js#L770 )
2) `Path.prototype.fetchRequestedUrl = function(current, what) (` https://github.com/mgonto/restangular/blob/e795cd3a39a395eac9b71febb45fa6334da37db3/src/restangular.js#L694 )

2) is the code that is invoked by `.getRequestedUrl()` so the only place that params are implicitly set is in 1)

`restangularizeBase` is referenced in two places - `restangularizeElement()` and `restangularizeCollection()` - and the only place where `reqParams` (the last argument) is passed to `restangularizeElement()` is in `okCallback()` - when the element has actually been gotten from the server.

So the second workaround (first is `endpoint[Restangular.configuration.restangularFields.reqParams] = {hello: "world"};`) is to use `Restangular.restangularizeElement()` and to pass req params to the empty element.
