### ISSUE TITLE
.all().one() does not work for numbers

### ISSUE THREAD

**Issue by ntrrgc** [mgonto/restangular#813]
This works:

```
> Restangular.all("models").one("1").getRestangularUrl()
/api/models/1
```

This also works:

```
> Restangular.one("models", 1).getRestangularUrl()
/api/models/1
```

But this triggers an error:

```
> Restangular.all("models").one(1).getRestangularUrl()
Error: You're creating a Restangular entity with the number instead of the route or the parent. You can't call .one(12)
```

Shouldn't this be allowed for consistency reasons?

**Comment by diosney** [comment]
Same issue here, had to typecast to String in order to use it properly:

     if (instance_id) {
          return model
            .one(String(instance_id));
        }

+1 to  @ntrrgc way of using it, like `tasks.one(15).get()`, and if a String, parse internally to number.
