### ISSUE TITLE
Is it plan to add an upload progress on POST/PUT ?

### ISSUE THREAD

**Issue by bertrandg** [mgonto/restangular#821]
For an angular project using restangular I'm currently working on, I needed an upload progress bar.

Sadly, Restangular doesn't implement it (or tell me if it does?) and I had to add [angular-file-upload](https://github.com/danialfarid/angular-file-upload).
Is it plan to add an upload progress on POST/PUT ?

Thanks for your great work!

**Comment by Sshuichi** [comment]
is this solved? can we use the third argument ?
