### ISSUE TITLE
Multiple REST requests

### ISSUE THREAD

**Issue by Surender246** [mgonto/restangular#822]
I need data from multiple tables to display on a page so am calling multiple REST requests but only some requests are giving me the data and am getting empty array from the remaining requests.How to call multiple REST requests in restangular so that i get data from all the requests.. please help me..

thanks in advance

**Comment by daviesgeek** [comment]
Were you able to resolve this issue?

**Comment by Surender246** [comment]
No am not able resolve that instead i removed some calls from onLoad to onClick
.

**Comment by daviesgeek** [comment]
Okay, I'm going to close this for now. Feel free to re-open if there's still an issue.
