### ISSUE TITLE
Clone/Copy Performance

### ISSUE THREAD

**Issue by cstephe** [mgonto/restangular#829]
Restangular is using angular.copy in its copy/clone method.  If you have a list of 10k+ items in your response then this is very slow.

I believe it would be better to use JSON.parse(JSON.stringify(responseData))) and then rerestangularize the item, This is a much faster way to deep copy data.  Since responses are just JSON, angular.copy is overkill for them.

I'm going to be deep diving into restangular to figure out how to do this right but wanted to get thoughts in the mean time.

**Comment by grabbou** [comment]
@cstephe if you have any further questions or ideas how this can be improved, feel free to comment and we will be more than happy to reopen this issue again.
