### ISSUE TITLE
Null value getting passed as String in params

### ISSUE THREAD

**Issue by randallmeeker** [mgonto/restangular#83]
```
params = {filter: Null}
Restangular.all('employees').getList(params)
```

The Null value is being generated from the ui-router's params, so I'm not sure who's issue this is, but when I pass their object (with a null value) into restangular, restangular translates it into a string

```
/employees/?filter=null
```

instead I need

```
/employees/?filter=
```

**Comment by chanakyachatterjee** [comment]
just dont pass any value .. like /employees/?filter=
