### ISSUE TITLE
"Each time, there're more Production WebApps using Restangular. If your webapp uses it and it's not in the list, please create an issue or submit a PR"

### ISSUE THREAD

**Issue by mmahalwy** [mgonto/restangular#839]
Quran.com will shortly be using `Restangular` and you can currently see the alpha version at alpha.quran.com

**Comment by grabbou** [comment]
@mmahalwy hope you didn't change your mind in the meantime :)

**Comment by mmahalwy** [comment]
haha, don't worry! Still using it strong!

In the past 2 weeks, it's powered over 100k+ API calls - and this is just the alpha site ;)

**Comment by mmahalwy** [comment]
Thanks for merged :)

**Comment by grabbou** [comment]
You're welcome :) That's good news! Good luck on the next stages of the development!
