### ISSUE TITLE
Could you add an easy possibility for retrieving unrestangularized data?

### ISSUE THREAD

**Issue by andimeier** [mgonto/restangular#870]
First of all, I love Restangular, I'm used to be very happy with it. I then encountered this problem and I am aware that this has been discussed before (s. issue #100) and I am also aware of the solution proposed in the FAQ (https://github.com/mgonto/restangular#how-can-i-access-the-unrestangularized-element-as-well-as-the-restangularized-one).

However, I still have an issue with that:

My application is an analysis and reporting tool which receives its data via Restangular from a REST resource. The problem is that I expect many many data events coming. The solution proposed in the FAQ effectively doubles the volume of data which the Javascript app has to hold. This might not be an issue for most apps, but it is for mine.

That being said, I am unhappy with Restangular turning:

````
[  
    {  
        "data1":0.75,
        "data2":2.0,
        ... <<many more>>...
        "data100":1.45
    },
    {  
        "data1":0.83,
        "data2":2.1,
        ... <<many more>>...
        "data100":1.65
    }
]
````

into:

````
[  
    {  
        "data1":0.75,
        "data2":2.0,
        ... <<many more>>...
        "data100":1.45,
        "originalElement":{  
            "data1":0.75,
            "data2":2.0,
            ... <<many more>>...
            "data100":1.45
        },
        "route":"/data",
        "reqParams":null,
        "fromServer":"localhost:8083",
        "parentResource":null,
        "restangularCollection":false
    },
    {  
        "data1":0.83,
        "data2":2.1,
        ... <<many more>>...
        "data100":1.65,
        "originalElement":{  
            "data1":0.83,
            "data2":2.1,
            ... <<many more>>...
            "data100":1.65
        },
        "route":"/data",
        "reqParams":null,
        "fromServer":"localhost:8083",
        "parentResource":null,
        "restangularCollection":false
    }
]
````

I am voting strongly for some kind of switch or additional parameters to the fetch methods (one() getList()) or whatever to let the user choose on a per-resource basis whether the response should be restangularized or not. After all, in my special case:

* retrieve a *whole lot* of data
* I don't want to write the data back
* I don't want to change the data
* I don't need to remember the request info

... I simply want the data fetched as efficient as possible - and I would not like an responseInterceptor doubling the volume of the data, which could lead to performance issues in my SPA.

I hope this does not sound rude - I think you guys did/do a terrific job. But if you would add such functionality, I think it would quite help to stretch the application scenarios for Restangular.

Currently I am thinking about requesting such mass data with ngResource of $http instead of Restangular - but I would not like to.

**Comment by elliotec** [comment]
There is an easy way to do this. Just use the plain() method on your response. Took me forever to find this since it's not in the docs. Something like this hooked to an ng-click worked for me:

```javascript
$scope.showData = function () {
  baseUrl.post(someData).then(function(response) {
    console.log(response.plain());
  });
};
```

**Comment by juanchavezlive** [comment]
Thanks a lot @elliotec. Your answer has saved me a lot of time :)

**Comment by grabbou** [comment]
Side note -> Plain should be documented. Thanks @juanchavezlive  and @elliotec .

**Comment by elliotec** [comment]
Agreed @grabbou. I've updated the readme in pull request #1049, hopefully it gets merged and can help others looking for this.

**Comment by grabbou** [comment]
Ok. Although @mgonto probably is going to kill me, I am merging that PR as it's only a readme update :)
