### ISSUE TITLE
What is the best way to bulk remove objects?

### ISSUE THREAD

**Issue by burakkilic** [mgonto/restangular#875]
Hi;

I want to remove the selected objects from my table. I have an array of object ids. What is the best way to remove them from server?

**Comment by grabbou** [comment]
Can you show us a bit of your code and the current implementation you used so we can decide which approach will be the most efficient? Thanks.

**Comment by burakkilic** [comment]
Now I am sending delete requests one by one. What I need is sending array of ids with DELETE type.

**Comment by grabbou** [comment]
Have you tried customDELETE then mentioned in the docs?

**Comment by grabbou** [comment]
```js
Restangular.several('users', 1234, 123, 12345).remove()` 
/ DELTE /users/1234,123,12345
```
or play around with custom deletes.
