### ISSUE TITLE
Response of head()-function is null

### ISSUE THREAD

**Issue by igler** [mgonto/restangular#876]
In my case a
<pre><code>Restangular.one('locations', location.id).head().then(function(response) {
    console.log(response.headers);
});
</code></pre>

does not return a response and therefore I get a <code>TypeError: Cannot read property 'headers' of undefined</code>. What's the exact usage of <code>head()</code> so I can access for instance the ETag value?

**Comment by grabbou** [comment]
Yep, that's how it should be done :) Glad you figured that out by yourself.
