### ISSUE TITLE
Feature Request: noConflict Mode

### ISSUE THREAD

**Issue by mike-marcacci** [mgonto/restangular#879]
My apologies if this has already been discussed.

Would you consider adding a "noConflict" mode, configurable through a property like `setPrefix`? If set, all Restangular methods applied to a retrieved element (and possibly collections) would use the given prefix (probably something like `$`). This way, Restangular could be used with API's that use otherwise overwitten properties like "post" and "options."

**Comment by grabbou** [comment]
Hey,
For now - not. To consider in Restangular 2. For now, please refer to https://github.com/mgonto/restangular#setrestangularfields and that should do the trick :)
