### ISSUE TITLE
Strange behaviour of put, customPUT and patch methods

### ISSUE THREAD

**Issue by mistahselectah** [mgonto/restangular#880]
Hello.
Sorry for my lame english)

I've found some strange behaviour of put, customPUT and patch methods.
I'm trying to do editable table. And i have only 2 seconds to edit or to fill new model and press submit button to send request to the backend, otherwise if i write some human friendly text 2-3 seconds pass, the request doesn't send to the server and i get error callback with following object:
```
{
   "data":"",
   "status":0,
   "config":{
      "method":"PUT",
      "transformRequest":[
         null
      ],
      "transformResponse":[
         null
      ],
      "headers":{
         "Accept":"application/json, text/plain, */*",
         "Content-Type":"application/json;charset=utf-8"
      },
      "url":"/rest/Platforms",
      "data":{
         "name":"asdf sadf",
         "description":"asdf asdfasdf"
      }
   },
   "statusText":""
}
```
If i change put method to post method everithing works fine.
But the idea is to use:
put  - for creating
patch - for updating
post - for search, limit, offset etc.

On my backend i have declared following  url patterns for the REST controller:

// Get list 
array('rest/list', 'pattern' => 'rest/<model:\w+>', 'verb' => 'GET'),

// Search by params (limit, offset, filters etc)
array('rest/search', 'pattern' => 'rest/<model:\w+>', 'verb' => 'POST'),

// Get model by ID
array('rest/view', 'pattern' => 'rest/<model:\w+>/<id:\w+>', 'verb' => 'GET'),

// Update model 
array('rest/update', 'pattern' => 'rest/<model:\w+>/<id:\w+>', 'verb' => 'PATCH'),

// Delete model by ID
array('rest/delete', 'pattern' => 'rest/<model:\w+>/<id:\w+>', 'verb' => 'DELETE'),

// Create new 
array('rest/create', 'pattern' => 'rest/<model:\w+>', 'verb' => 'PUT'),

<b>Here is my frontend controller:</b>

```
function PlatformsCtrl($scope, Restangular, ModalService) {

    var platforms = Restangular.all("Platforms");
    $scope.platforms = [];

    var fetch = function() {
        platforms.getList().then(function(response) {
            $scope.platforms = response;
        });
    }

    fetch();

    $scope.isAdding = false;
    $scope.editIndex = -1;
    $scope.new = {
        name: '',
        description: ''
    }

    $scope.add = function() {
        $scope.isAdding = true;
        $scope.editIndex = -1;
    }

    $scope.edit = function(index) {
        $scope.isAdding = false;
        $scope.editIndex = index;
    }

    $scope.cancel = function() {
        $scope.isAdding = false;
        $scope.editIndex = -1;
    }

    $scope.save = function(index) {
        if(index < 0) {
            $scope.platforms.customPUT($scope.new).then(
                function(platform) {
                    $scope.platforms.push(platform);
                    $scope.cancel();
                },
                function(response) {
                    ModalService.error('Error: ' + response.data.status, response.data.message);
                    $scope.cancel();
                    fetch();
                }
            );
        } else {
            $scope.platforms[index].patch().then(
                function() {
                    $scope.cancel();
                },
                function(response) {
                    ModalService.error('Error: ' + response.data.status, response.data.message);
                    $scope.cancel();
                    fetch();
                }
            );
        }
    }

    $scope.remove = function(index) {

      var confirm = ModalService.confirm('Warning! The operation is final.', 'Are you sure to delete platform?');
        confirm.result.then(
            function() {
                $scope.platforms[index].remove().then(
                    function() {
                        $scope.platforms.splice(index, 1);
                    },
                    function(response) {
                        ModalService.error('Error: ' + response.data.status, response.data.message);
                    }
                );
            }
        );
    }
}

angular.module('app').controller('PlatformsCtrl', PlatformsCtrl);
```

<b>Here is my template:</b>

    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <?php if(Yii::app()->user->checkAccess('editSystem')):?>

                <th>
                    <button type="button" class="btn btn-default" ng-click="add()">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </th>

            <?endif;?>
        </tr>
    </thead>
    <tbody>
        <?php if(Yii::app()->user->checkAccess('editSystem')):?>

            <tr ng-if="isAdding">
                <td></td>
                <td><input type="text" maxlength="50" name="name" ng-model="new.name" placeholder="Enter platform name"></td>
                <td><input type="text" maxlength="50" name="description" ng-model="new.description" placeholder="Enter plstform description"></td>
                <td>
                    <button type="button" class="btn btn-primary" title="save" ng-click="save(-1)">
                        <span class="glyphicon glyphicon-save"></span>
                    </button>
                    <button type="button" class="btn btn-default"  title="cancel" ng-click="cancel()">
                        <span class="glyphicon glyphicon-ban-circle"></span>
                    </button>
                </td>
            </tr>

        <?endif;?>

        <tr ng-repeat="platform in platforms">
            <td ng-if="editIndex != $index">{{platform.id}}</td>
            <td ng-if="editIndex != $index">{{platform.name}}</td>
            <td ng-if="editIndex != $index">{{platform.description}}</td>

            <?php if(Yii::app()->user->checkAccess('editSystem')):?>

                <td ng-if="editIndex != $index">
                    <button type="button" class="btn btn-default" title="edit" ng-click="edit($index)">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </button>
                    <button type="button" class="btn btn-danger" title="remove" ng-click="remove($index)">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                </td>

                <td ng-if="editIndex == $index">{{editing.id}}</td>
                <td ng-if="editIndex == $index">
                    <input type="text" maxlength="50"  name="name" value="{{platform.name}}" ng-model="platform.name"
                           placeholder="Enter platform name" required="">
                </td>
                <td ng-if="editIndex == $index">
                    <input type="text" name="description" value="{{platform.description}}" ng-model="platform.description"
                           placeholder="Enter platform description">
                </td>
                <td ng-if="editIndex == $index">
                    <button type="button" class="btn btn-primary" title="save" ng-click="save($index)">
                        <span class="glyphicon glyphicon-save"></span>
                    </button>
                    <button type="button" class="btn btn-default" title="cancel" ng-click="cancel()">
                        <span class="glyphicon glyphicon-ban-circle"></span>
                    </button>
                </td>

            <?endif;?>
        </tr>
    </tbody>

Hope someone can help me.
Thanks in advance.

**Comment by grabbou** [comment]
Please provide working plunkr example or head to Stackoverflow as the issue does not seem to be Restangular related.
