### ISSUE TITLE
Refreshing a collection with .getList()

### ISSUE THREAD

**Issue by prewk** [mgonto/restangular#885]
Hi! (sorry about close->reopen)

How do I refresh a Restangular collection without replacing it?

The only way I've solved it is by pushing and popping arrays, after doing a `getList()`. Is it possible to do something like this instead?

````js
var accounts = Restangular.all('accounts');

var refresh = function() {
    accounts.getList();
};

refresh();
$scope.accounts = accounts;
````

I know of `getList().$object` but to use it I have to overwrite my previous object every time. So that's out of the question for any kind of binding from service <-> controller.

What I'm doing now instead:
````js
var accounts = Restangular.all('accounts');

var refresh = function() {
    accounts.getList().then(function(data) {
        while (accounts.length) {
            accounts.pop();
        }

        while (data.length) {
            accounts.push(data.shift());
        }
    });
};
````

**Comment by grabbou** [comment]
Hey,
what about
```js
var rest = Restangular.all('accounts');
$scope.allItems;
function refresh() {
   $scope.allItems = rest.getList();
}
refresh();
```

**Comment by prewk** [comment]
Thanks, that'll overwrite the `$scope.allItems` array every time, though. It'll work because of Angular dirty-checking, but if I want to keep the data as a single source of truth in a service I'm out of luck, unfortunately.

(Since I posted I've moved to React so I may be wrong)

**Comment by grabbou** [comment]
Yeah, if you plan to use pagination, you can implement something more fancy to update the entire collection, this should be supported in V2 in my opinion.
