### ISSUE TITLE
Route is undefined after post(), put(), save()

### ISSUE THREAD

**Issue by Cranespud** [mgonto/restangular#892]
Hi mgonto, could you tell me what am I doing wrong here?  When calling save() or post() the request is good but responseAlarm.route is undefined, so if I try to update the object later the request url is wrong.  I noticed that responseAlarm.parentResource is populated with the route among other properties.

var Alarms =  Restangular.service('alarms');
var newAlarm = Alarms.one();
newAlarm.name = 'test';
newAlarm.save().then(function(responseAlarm) { // post request is ok
   responseAlarm.put();  // leads to PUT alarms/undefined/34  (34 is the last inserted id)
});

Thanks in advance!

**Comment by tachang** [comment]
Running into this as well. Though on older code it seems to work fine? Odd.

**Comment by grabbou** [comment]
Actually when user tries to pass undefined value as a operation param this should be treated as a implementation error. Further fixes to be carried on here -> #1010

**Comment by grabbou** [comment]
Using `Accounts.one()` is a wrong way of creating a new object. One is meant for query building where you plan to get/delete/put some additional details. 

From docs:

```js
var baseAccounts = Restangular.all('accounts');

var newAccount = {name: "Gonto's account"};

// POST /accounts
baseAccounts.post(newAccount);
```

**Comment by OrganicPanda** [comment]
Why should you need to POST to your API to create something new? In my app this is highly inconvenient, I need a simple way to have a local-only instance that can be saved later. Not sure why this was closed as it's completely valid.

**Comment by KokaChernov** [comment]
I second @OrganicPanda 's lament. It is ugly to have to post explicitly and then save. I was hoping to have save to be universal method. Can we have an @mgonto comment on this?
