### ISSUE TITLE
ObjectId created in other document's field after post() 

### ISSUE THREAD

**Issue by sayaa** [mgonto/restangular#895]
Hi, 
I'm new in restangular, 
I have to create a document which have an array field like this : 

{
"_id" : ObjectId("542e4ad806d7f154114e38ec"),
"id" : 001,
    "name" : "name",
    "news" : [ 
        {
            "title" : "tittle 1",
            "content" : "content 1"
        }, 
        {
            "title" : "tittle 2",
            "content" : "content 2"           
        }
    ]
}

when I add a document in my database, an ObjectId is also automaticaly set in my "news" field in the created document, like : 
 "news" : [ 
        {
            "title" : "tittle 1",
            "content" : "content 1",
            "_id" : ObjectId("542e4ad806d7f154114e38ed")
        }, 
        {
            "title" : "tittle 2",
            "content" : "content 2",
            "_id" : ObjectId("542e4ad806d7f154114e38ee")           
        }
    ]

I'd like to know if there is a way to prevent that. Or at worst if there is a way to remove it after its creation.
thanks for help

**Comment by grabbou** [comment]
The _id field is mandatory and you need to provide a unique value for each doc, but it doesn't have to be an ObjectID. You could use an integer value instead to save space, but it's up to you to ensure each doc's value is unique.If you fancy, you can define custom _id field on your schema and change the way it's being created or auto incremented.
