### ISSUE TITLE
$type getting stripped out of request

### ISSUE THREAD

**Issue by kentcooper** [mgonto/restangular#896]
I was getting a ton of json serialization errors when I was posting/putting back to the server. Turned out $http strips any property that starts with a $ which is kind of a problem when you need to pass in type information. I have simple fix for this and I can submit a PR but wasn't sure if it would be desirable to fix it in restangular or not.

**Comment by grabbou** [comment]
This is now solved in Angular 1.3.x and above. Issue was with their implementation of serialisation that was stripping variables starting with $. With new versions, it only deletes the ones starting with $$.
