### ISSUE TITLE
Chained promises are not enhanced

### ISSUE THREAD

**Issue by simonbreak** [mgonto/restangular#903]
Chaining an enhanced promise results in a regular, non-enhanced promise. In other words, this does not work:
```
enhancedPromise.then(function (data) { data.foo = 'bar'; return data; }).get('foo');
```
... because there is no `get` method on the promise returned by the `then` method.

It seems to me that `restangularizePromise` should augment the promise's `then` method to enhance `then`'s returned promise. Without this feature the enhancements are pretty useless to me because they are only available on promises which haven't been chained.

**Comment by grabbou** [comment]
This is not supported in V1 and I am not sure if it will ever be. We might consider using Bluebird in the future that has plenty of exciting features, like dynamic getters that can work with that. For now, please rewrite your code to:

```js
Restangular.all('results').getList().then(function(data) {
   return data.get('foo'); //return another promise from here and continue with then/catch and stuff
});
```
