### ISSUE TITLE
Missing Collection.put method

### ISSUE THREAD

**Issue by akarelas** [mgonto/restangular#909]
Suppose I want to create an element with a user-defined id. According to http://www.restapitutorial.com/lessons/httpmethods.html , this requires a PUT method. From the page: "However, PUT can also be used to create a resource in the case where the resource ID is chosen by the client instead of by the server"

However I don't see a Put method that I can use in Restangular. All I see in collection methods is:

```
putElement(idx, params, headers): Puts the element on the required index and returns a promise of the updated new array
```

Where (in which parameter of putElement) do I get to describe my new object? Nowhere. That's why we need a method to be able to PUT (create new objects with known id).

**Comment by grabbou** [comment]
Hey, have you tried **customPUT** method?

From docs:
```
customPOST([elem, path, params, headers]): Does a POST to the specific path. Optionally you can set params and headers and elem. Elem is the element to post. If it's not set, it's assumed that it's the element itself from which you're calling this function.
```

Simple example:
```js
// yourCollection/{{elementToInsertId}}
yourCollection.customPUT(elementToInsert, elementToInsertId);
```

This should do the trick :)
