### ISSUE TITLE
Change URL of Element

### ISSUE THREAD

**Issue by meenie** [mgonto/restangular#91]
Hey Again,

I have a scenario where I've done a search for a row of data in a table using `Restangular.all('filters/search')`.  I then display that in a table and give the option to copy an element to another collection of elements I've pulled from my datasource using `Restangular.all('filters')`.  Now I have a collection of elements where one of them has the URL of `/filters/search` and the rest `/filters`.  If I wanted to further manipulate that new element, I need to somehow change its url to `/filters` so it will post to the correct URL.

Does this make sense?

Cheers,
meenie

**Comment by Meekohi** [comment]
I don't understand how this answer solves the problem: how do you get a Restangular list of "filters" from the "fitlers/search" url, such that you could do the following:
```javascript
var filters = Restangular.all('filters/search').getList();
filters[0].remove(); //this will be an error because it will try to do "DELETE filters/search/1"
```

**Comment by gustperz** [comment]
@Meekohi agree with you, and I'm having the same issue

**Comment by Meekohi** [comment]
@gustperz For what it's worth, we ended up switching to just using `ngResource`. This repo is basically abandonware now.
