### ISSUE TITLE
Restangular TypeError: Cannot set property 'route' of null

### ISSUE THREAD

**Issue by RobertVogt** [mgonto/restangular#910]
This is a Angular function that previously worked...

```js
    $scope.InsertLabelText = function () {

    var MapText = $("#txtMapLabel").val();
    Restangular.setBaseUrl(BaseURL);

    if (MapText != null) {
        //Call WebAPI to enter text then refresh map.


        var TextObjs = Restangular.all('PostObjects');
        NewTextObject = {TypeMapId: "5", GrowerId: $("#GrowerName").val(), CropYear: $("#CropYear").val(), NAME: MapText, SHAPE: coordinates}

        TextObjs.getList(NewTextObject).then(function (data) {
            $scope.Label = data;
            if ($scope.Label.Success = true) {

                var geojson_format = new OpenLayers.Format.GeoJSON();
                var Object_style = OpenLayers.Util.extend({}, layer_style);
                Object_style.fillOpacity = 0.7;
                Object_style.label = MapText;
                Object_style.graphicZIndex = 4999;
                Text.style = Object_style;
                Text.addFeatures(geojson_format.read($scope.Label.TextObject));

                LabelLine.destroyFeatures();
            }
            else {
                console.log(data);
                var Error = prompt($scope.Label.TextObject);
                console.log("There was an error saving");
            }
            $("#divMapInputText").hide();
        });


    }

};
```

It fails on the call TextObjs.getList with the error "TypeError: Cannot set property 'route' of null"

I have 3 other functions in the same controller with the same code pattern but they all work?

Here is the whole error from chrome...

TypeError: Cannot set property 'route' of null
at g (http://localhost/FarmMapsMvc4/Scripts/ThirdParty/restangular.min.js:8:8705)
at t (http://localhost/FarmMapsMvc4/Scripts/ThirdParty/restangular.min.js:8:11154)
at http://localhost/FarmMapsMvc4/Scripts/ThirdParty/restangular.min.js:8:13225
at http://localhost/FarmMapsMvc4/Scripts/ThirdParty/lodash.min.js:72:226
at y (http://localhost/FarmMapsMvc4/Scripts/ThirdParty/lodash.min.js:16:110)
at Function.Et (http://localhost/FarmMapsMvc4/Scripts/ThirdParty/lodash.min.js:72:191)
at http://localhost/FarmMapsMvc4/Scripts/ThirdParty/restangular.min.js:8:13149
at h (http://localhost/FarmMapsMvc4/Scripts/ThirdParty/angular.min.js:78:33)
at http://localhost/FarmMapsMvc4/Scripts/ThirdParty/angular.min.js:78:266
at Object.e.$eval (http://localhost/FarmMapsMvc4/Scripts/ThirdParty/angular.min.js:88:3

**Comment by grabbou** [comment]
Can you please create a JSFiddle with the code that can reproduce this? Thanks.

**Comment by RobertVogt** [comment]
Thanks for reaching out but this was months ago...I'm sure I don't know what it was refering to as I have moved to something else. 

----- Original Message -----
