### ISSUE TITLE
Linked fields

### ISSUE THREAD

**Issue by ivldev** [mgonto/restangular#911]
Hey there,

Firstly, thanks so very much for providing this resource. It's just immense. 

I fear my question betrays a really fundamental ignorance. This will be the first time I've consumed a REST-based resource. From what I've read, Restangular solves the problems I would otherwise have had - but, as I've not ran into them before, how Restangular works by fixing them isn't as intuitive for me as it may otherwise be. Which is to say, if this is is stupid, sincere apologies. 

Basically, my REST resource expresses the relationships between objects by means of links. For example, 

[
    {
        "id": 1, 
        "name": "Project 1.0", 
        "project_doc": "http://127.0.0.1:8000/api/project_doc/1/.json"
    }
]

{
	"id": 1, 
	"project": "http://127.0.0.1:8000/api/projects/1/.json", 
	"creation_date": "01/01/01",
	"participants": 
		["http://127.0.0.1:8000/api/participants/1/.json", 
		"http://127.0.0.1:8000/api/participants/2/.json"]
}

I'm looking for a way to make Restangular aware of these links. As I understand it, Restangular makes it easy and elegant to get either or both of the structures, and it would be easier if I could construct my urls in a /api/projects/1/participants/2/ way, but I sadly can't. 

Any guidance on how best to approach these things in Restangular would be very much appreciated. 

Thanks.

**Comment by grabbou** [comment]
In order to construct the above URLs (assuming you already created needed endpoints), you can do:
```js
Restangular.one('projects, 1').one('participants', 2).get()
or
Restangular.one('projects', 1').all('participants').get(2);
```
