### ISSUE TITLE
subresource named 'save'

### ISSUE THREAD

**Issue by matteosister** [mgonto/restangular#913]
Hello everybody, and thanks to all contributors for this awesome library...

I got a problem with a resource like this:

``` json
{  
   "id":1,
   "others": "...",
   "save":{  
      "id":1
   }
}
```

the embedded resource "save" has the same name of an [element method](https://github.com/mgonto/restangular#element-methods).
As a result I'm unable to access the data (element.save) inside my template...

Is there a way to rename the save method on the elment? I really can't change the resource name...

Many thanks in advance!

**Comment by grabbou** [comment]
:+1:
