### ISSUE TITLE
customPUT not generating path correctly

### ISSUE THREAD

**Issue by rocketegg** [mgonto/restangular#914]
When using the customPUT function, the path is not generated correctly:

If I do Restangular.one('user', user.id).customPUT('edit'), restangular ends up sending a POST /users/id.json instead of sending a PUT /users/:id/edit.

If I do Restangular.one('user', user.id).customOperation('PUT', 'edit'), then it sends a POST with X-HTTP-Method-Override: put on /users/:id/edit (the correct path).

This is on version 1.2.2 but also noticed the same issue in 1.4.x

**Comment by molekilla** [comment]
+1

**Comment by grabbou** [comment]
First argument to `customPUT` is element to send, the second one is `path`. Because you overwrite element, not path, you are actually sending edit string to /users/id.

You can try
```js
Restangular.one('user', user.id).customPUT(user, 'edit');
```
