### ISSUE TITLE
First call is aborted

### ISSUE THREAD

**Issue by ackimwilliams** [mgonto/restangular#921]
I am not sure if this is related to my config, but I noticed that my very first Restangular call is ABORTED or CANCELLED. 

My solution to this problem is forcing `Restangular.all('entity').getList();` which I expect to get cancel, then I use Restangular to handle subsequent api calls.  Any suggestion on how to debug this issue?

**Comment by grabbou** [comment]
I don't think that this is going to be an issue as long as timeout uses milliseconds in every case (haven't heard of any implementations that use a different unit) :)
