### ISSUE TITLE
Cancel a request when cached data is available

### ISSUE THREAD

**Issue by astrism** [mgonto/restangular#926]
I would like to send a request and have Restangular intercept and resolve the request if cached data is available. This may be related to #589 but I came up with a jsfiddle which demos how I'm attempting to do this:
http://jsfiddle.net/astrism/q9qyox50/13/

The request is still made when the code runs. Any ideas?

**Comment by f0def** [comment]
Change
```javascript
                var defer = $q.defer();
                defer.reject();
                httpConfig.timeout = defer;
```
to
```javascript
                var defer = $q.defer();
                defer.resolve();
                httpConfig.timeout = defer.promise;
```
Example here http://jsfiddle.net/q9qyox50/14/

**Comment by fmclopes** [comment]
The request is cancelled but the cached data is not sent. 

Any suggestions?

**Comment by f0def** [comment]
I wrote example, using decorator for $http, that caching request promise to prevent multiple request to the same url
Example here (http://jsfiddle.net/referee/hh30bh0q/)

**Comment by grabbou** [comment]
To review & update docs.

**Comment by daviesgeek** [comment]
Will update docs with referenced issue #1391
