### ISSUE TITLE
service with custom methods not working

### ISSUE THREAD

**Issue by piernik** [mgonto/restangular#928]
When I add new service like:
```
.factory('apiAdmin', ['Restangular', function (Restangular) {
        return Restangular.withConfig(function (RestangularConfigurer) {
            RestangularConfigurer.addElementTransformer('admin', true, function (admin) {
                admin.addRestangularMethod('login', 'post', 'login');
                return admin;
            });
        }).service('admin');
    }])
```
and then use it like `apiAdmin.login()` I got undefined error. `console.log(apiAdmin)` gives me only `one`, `post`, and `getList` functions.
Can I use services with my custom methods?

**Comment by FabienDehopre** [comment]
I think also that this is related to #719.
@mgonto did not release a new version since my PR was merged. So, for now, you should refer to the latest commit.

**Comment by grabbou** [comment]
Yeah, closing this in favour of #719. For now, transformers work only with elements, #719 is about adding this feature to collections as well. Stay tuned.
