### ISSUE TITLE
code typo in example: How can I handle errors?

### ISSUE THREAD

**Issue by nobalmohan** [mgonto/restangular#929]
Found:
}, function(response) {
  
Correct syntax: 
}), function(response) {

**Comment by grabbou** [comment]
Nope, it's not a typo.
```js
Restangular.all("accounts").getList().then(function() {
  console.log("All ok");
}, function(response) {
  console.log("Error with status code", response.status);
});
```
`then()` from `$q` accepts two parameters, one function for handling resolved response, the second one for rejections :)
