### ISSUE TITLE
Nested Associations

### ISSUE THREAD

**Issue by mrdanparker** [mgonto/restangular#93]
Hi,  

I was wondering if there was any way to "restangularize" nested associations without having to perform two API calls?  i.e. Say I had a /ships endpoint and everywhere I use a ship I always need to know about it's crew.  My API actually returns the crew information as part of the response.  e.g. /ships/1 returns:

``` javascript
    {
        id:1, 
        name: "Queen Anne's Revenge", 
        crew: [{
            id:1, 
            name: "Blackbeard"
        }]
    }
```

What I'd like to be able to do is somehow let restangular know that my response contains a crew collection and that it should also be restangularized to give me all the restangular method decoration goodness on the crew members.

This would also be useful on 'has one" associations too.  ie. (for want of a better example) If requesting by crew member first: /crew/1 returning:

``` javascript
    {
        id:1, 
        name: "Blackbeard", 
        ship: {
            id:1, 
            name: "Queen Anne's Revenge"
        }
    }
```

It'd be good if we were able to tell it to restangularize Blackbeard's ship.

Great library BTW - Thanks,

Dan

**Comment by airlst** [comment]
Still not getting the complete picture how you would cleanly implement the case above if "crew" was a collection. 

I understand that ```Restangular.restangularizeCollection(parent, elem, route)``` is responsible to restangularize the "crew" collection, but from where would i call it?

I tend to hide my Restangular object behind a service and configure them with ```Restangular.withConfig()```. Where would I place the call to ```restangularizeCollection``` then?

**Comment by fstbraz** [comment]
Hi mgonto, same problem like airist. my restangular object is on a service, and the configuration on a config file for all the app.Where would I place the call to restangularizeElement ?

**Comment by fstbraz** [comment]
What i get from my api is a thing like this:

```
{
  "total": 2,
  "per_page": 10,
  "current_page": 1,
  "last_page": 1,
  "next_page_url": null,
  "prev_page_url": null,
  "from": 1,
  "to": 2,
  "data": [
    {
      "id": 1,
      "start_date": "2006-08-20 05:11:32",
      "end_date": "2009-10-18 23:03:06",
      "created_at": "2016-06-23 08:41:51",
      "updated_at": "2016-06-23 08:41:51",
      "unity": {
        "id": 224,
        "code": 20060810,
      },
      "user": [
        {
          "id": 1,
          "username": "Kiara Runolfsdottir",
          "created_at": "2016-06-23 15:56:56",
          "updated_at": "2016-06-23 15:56:56"
        },
        {
          "id": 2,
          "username": "Zoe Dach",
          "created_at": "2016-06-23 15:56:56",
          "updated_at": "2016-06-23 15:56:56"
        },
        {
          "id": 3,
          "username": "Mrs. Zelma Johnston III",
          "created_at": "2016-06-23 15:56:56",
          "updated_at": "2016-06-23 15:56:56"
        },
      ]
    }
  ]
}
```

Tnks !

**Comment by fstbraz** [comment]
Any help,  please?

The best try that I can get , is having all the test objects on the edit route. using the `getList()` like:

```javascript
 this.show = function(id) {
        // GET /api/scale/:id
        var data = _scaleService.getList('scaleuser');
        return data;
}

```

But with this I can't pass the id, to choose the right data object to be edited. The output of this is $object : Array[2] and I need only the selected object (id).

**Comment by fstbraz** [comment]
Ok, after a one day fight, finally I find a solution for my edit route list problem:
Something simple using a javascript promise:

this.show = function(id) {
        // GET /api/scale/:id
        var data =  _scaleService.getList().then(function (users) {
            var data = users[id-1];
            scalesCache.put('show' + id, data);
            return data;
        }) 
};

@mgonto  I suggest a better documentation about nested objects. Tnks for this amazing plugin!
