### ISSUE TITLE
list of urls in collection

### ISSUE THREAD

**Issue by Tallyb** [mgonto/restangular#932]
Hi, 
I might miss something very basic, so please help me on this one. 
I have a reaquest that return a list of URLs. 
e.g. the call to Restangular.all('accounts').getList will return 
"urls": [
"www.example.com/accounts/23", 
"www.example.com/accounts/28", 
"www.example.com/accounts/34", 
"www.example.com/accounts/35", 
]
I managed to clean the "urls": part with response inceptor. 
I need to get it into my controller $scope.accounts to show a list of data. 
Is that a common method of using REST? 
Any suggestion on how to do that properly with Restangular?

**Comment by grabbou** [comment]
Hi @Tallyb, you have two options, either provide essential details in your getList() rest api which is quite clever way of getting rid of N additional requests or check out this (take from readme):

```js
baseAccounts.getList().then(function (accounts) {
  // Here we can continue fetching the tree :).

  var firstAccount = accounts[0];
  // This will query /accounts/123/buildings considering 123 is the id of the firstAccount
  $scope.buildings = firstAccount.getList("buildings");
```

Change `firstAccount.getList("buildings")` to `firstAccount.get()` and that should work. 

I'd suggest mapping promises to have them resolved at one time, this code uses `Bluebird` promises but I am pretty sure you can adapt that to `$q` pretty easily.

```js
var detailsOfAccounts = Promise.map(accounts, function(account) { 
    return account.get();
});
```
