### ISSUE TITLE
200 Response but no JSON Data returned - Restangular issue?

### ISSUE THREAD

**Issue by acSpock** [mgonto/restangular#933]
Using restangular and the stub hub api. I can hit this API on the firefox restclient and get a response body back with all the JSON data.

But in my app, I get a 200 but no response body... the content length even says something's there

albeit the api says you just need GET/URI endpoint and Authorization: Bearer {token}

![screen shot 2014-11-07 at 11 01 40 am](https://cloud.githubusercontent.com/assets/5063540/4958712/7d36fe90-66b1-11e4-9774-69088de74b60.png)

![screen shot 2014-11-07 at 11 01 59 am](https://cloud.githubusercontent.com/assets/5063540/4958715/8108814c-66b1-11e4-94fd-9d4993f2dfd6.png)

Here's my restangular config

```
'use strict';
angular.module('myapp')
.config(['RestangularProvider', function(RestangularProvider){
    RestangularProvider.setBaseUrl('https://api.stubhub.com/');
    RestangularProvider.setDefaultHeaders({
        Accept: 'application/json',
        Authorization: 'Bearer 198u2190832190831432742(notreallymytoken)'
    });
    RestangularProvider.setDefaultHttpFields({
        withCredentials: false
    });
}]);
```

and here's my controller

```
$scope.searchEvents = function(){
    Restangular.one('search/catalog/events/v2?title="san francisco"').get().then(function(response){
        $scope.searchResponse = response;
    }, function(response){
        console.log("something went wrong");
    })
}
```

How can I begin to debug? I want to keep using restangular so hopefully I can get around this somehow.

**Comment by grabbou** [comment]
In the screenshot provided, i see "No response body", can you provide plunkr or paste some more accurate console.logs and response logs? Thanks.

**Comment by shashvattrip** [comment]
Facing the same issue here. There's not response body in the chrome network call but its there in POSTMAN.

**Comment by shashvattrip** [comment]
I figured out what the problem was and could be in your case too.
The Content-Type for youre response would have probably been something like application/javascript and NOT application/json.
Which is why it is not caught by Restangular but by browser or REST clients.

**Comment by daviesgeek** [comment]
@acSpock Any update? Can you provide more information/an example?

**Comment by joshuar500** [comment]
In my case, the server side configuration was wrong. I had to make sure that the server supported credentials. I'm using Flask-CORs.

**Comment by shashvattrip** [comment]
In my case, there was a special character in the DB (because of copy-pasting some text through PHPMyAdmin) which resulted in this odd empty response.
