### ISSUE TITLE
customOperation and addRestangularMethod would not use BaseUrl

### ISSUE THREAD

**Issue by niy** [mgonto/restangular#937]
Hi,

I've been trying to create a custom method named 'upVote' for a resource called 'posts', the posts api url is at "/rest/users/{username}/posts" while the url for the vote action is at "/rest/posts/{postId}/vote".

I have added the following configuration:

``` javascript
RestangularProvider.setBaseUrl(Routing.getBaseUrl() + '/rest');
RestangularProvider.addElementTransformer('posts', false, function(post) {
     post.addRestangularMethod('upVote', 'patch', 'vote', {_token: ajaxToken}, {});
     return post;
});
```

But the method sends the request to the wrong url (`/post/{postId}/vote`) and does not use the provided baseUrl at all.

Is there a way to make the method use the baseUrl for it's requests, or am I doing this the wrong way?

Best,
Nima

**Comment by pencilcheck** [comment]
+1

**Comment by daviesgeek** [comment]
The easiest way to accomplish this is to add your own custom method:

```js
RestangularProvider.addElementTransformer('posts', false, function(post) {
  post.upVote = function() {...} // add the method here
})
```
