### ISSUE TITLE
Confusing behaviour after .post()

### ISSUE THREAD

**Issue by porebrique** [mgonto/restangular#944]
I'm not sure if it is a bug (in fact, i'm pretty sure it is not), or just some unobvious behaviour, or I am doing something wrong with no understanding of some ideas, that restangular is based on.

My case is: form, where I create new resource instance, problem is not related to what resource exactly, let's say, it is a book, just to have some route.

```javascript
$scope.book = Restangular.one('book');
```
(I also tried to use .restangularizeElement on empty object {}, both ways seem ok to me, and both lead to the problem I describe here)

I fill book model with some data, do  .save() and update $scope.book with what I got from backend (in fact I need only id, but things could get more complicated):

```javascript
/* this goes to POST http://localhost:8000/api/v1/book which is correct */
$scope.book.save().then(function(response){
    console.log('This is first log', $scope.book)
    $scope.book = response;
    console.log('This is second log', $scope.book)
})		
```
First console.log gives me this (complete log is bigger, of course, here is only fields, thatt seem important to me): 
```
id: undefined
title: "Awesome book"
route: "book"
parentResource: null
```
And second gives this (note route and parentResource): 
```
id:3
title: "Awesome book"
route: undefined
parentResource: Object { route="book", singleOne=undefined, parentResource=null}
resource_uri: "/api/v1/book/3/"
```
so, when I save updated from the response $scope.book, PUT goes wrong:
```
PUT http://localhost:8000/api/v1/book/undefined/3/
```
So, my question is: why there is not freshly saved object as a response, but what seems to be saved objects's nested resource (but model doesnt have any nesting)? I almost sure I do something wrong, but my way  seems natural to me, so I don't have any ideas about where is my mistake. I hope that problem comes from some misunderstating, so I could fix it and go on with really nice instrument, that restangular is.

(I realize that question could be better with plunkr, but problem involves interaction with backend and I dunno how to make a fake one for plunkr, sorry)

**Comment by tachang** [comment]
+1

I am using restangular like this and ran into the issue as well. It seems really intuitive to do it the way at the top.

**Comment by Blaze34** [comment]
+1

**Comment by grabbou** [comment]
Please see my explanation in #892. Basically, in order to create a new element, you cannot use `one()`. The correct way is `Restangular.all('books').post({newBook})` which creates new book. Using one will produce undefined errors that you have encountered above. 

Please see this unit test:

```js
it("post() should add a new item with data and return the data from the server", function() {
     restangularAccounts.post(newAccount).then(function(added) {
       expect(added.fromServer).toEqual(true);
       expect(added.id).toEqual(newAccount.id);
     });
});
```
