### ISSUE TITLE
Clone / Copy sets fromServer flag to 'true'

### ISSUE THREAD

**Issue by MarkOfSine** [mgonto/restangular#945]
When cloning or copying a restangular model the fromServer attribute is always set to 'true'. 

Because of this when you create a new model on the client, and call the save() method it does a PUT as opposed to a POST.

The fromServer attribute should reflect the original entity.

**Comment by Vladimir-Purple** [comment]
I think this is related to this issue, there's something strange going in .clone():
http://jsfiddle.net/vladimir_ze/docz3fuz/

Some properties being reset to default values after using .clone().

**Comment by grabbou** [comment]
Sometimes it's set to undefined. To be refactored + unit tests should be done.
