### ISSUE TITLE
setRequestSuffix does not add suffix to requests without params

### ISSUE THREAD

**Issue by devm33** [mgonto/restangular#947]
Here is a plnkr demonstrating the issue http://plnkr.co/edit/zte2On?p=preview

This was an issue previously #489 and was fixed then, but it was reintroduced at some point by this line https://github.com/mgonto/restangular/blob/master/src/restangular.js#L723

**Comment by grabbou** [comment]
Thanks for the PR. Would you mind adding one or two test cases for it? It not - we will do it :)

**Comment by devm33** [comment]
Absolutely, will do. Thanks for working on the issues here!

**Comment by grabbou** [comment]
Great. This time with tests we will be pretty sure this particular feature is not going to be removed! No worries, I am glad you support Restangular as well :)

**Comment by devm33** [comment]
Alright I added some tests for the behavior as prescribed in #489. Let me know if anything else is needed here, thanks!

**Comment by grabbou** [comment]
Cool, merging. I will add one extra test with route params to cover the old behaviour as well.
