### ISSUE TITLE
Is there any way to restore Restangular object from json string?

### ISSUE THREAD

**Issue by kaiqigong** [mgonto/restangular#950]
Hi, 
Restangular is very cool. Thank you guys.  
I am using localStorage to store Restangular object in string. However, when I create object from the json string, the functions of Restangular object are gone. Is there any way to restore that?
This kind of methods will make me happy.
```
users.getList()
.then (data)->
  str = Restangular.toJson(data)
  restoredData = Restangular.fromJson(str)
  restoredData.post {name: 'new'}
```

**Comment by grabbou** [comment]
Hey,
You can serialise plain object (.$object) property, then do JSON.parse when you want to restore and use restangularizeElement :)
