### ISSUE TITLE
unexpected behavior when getting nested resources from a response object

### ISSUE THREAD

**Issue by dbuezas** [mgonto/restangular#951]
As the restangularized response object has all Restangular functions (like one(), all(), etc), I would expect it to treat fetching nested resources from that response object in the exact same manner as it does it when nested resources are fetched from the pointer object.

Example:
```javascript
restUser = Restangular.one('users', 5);
restUser.get().then(function(response){
   friends1 = restUser.all('friends').getList() // generates request to: users/5/friends
   friends2 = response.all('friends').getList() // generates request to: users/friends
});
```
Somehow the userId got lost in the way.
Is it so by design or a bug?

--
btw:  awesome library!

**Comment by nhutle** [comment]
Thanks, you make my day :)

**Comment by grabbou** [comment]
@dbuezas the correct way is `Restangular.all('users').get(5)`. Using one('5') is likely to throw an error in the future.

**Comment by dbuezas** [comment]
Oh, thanks for the heads up

**Comment by dbuezas** [comment]
The documentation is wrong then:
e.g. https://github.com/mgonto/restangular#creating-main-restangular-object

```
// Stating main object
Restangular.one('accounts', 1234)
```

**Comment by grabbou** [comment]
I gave you an alternative for the line below:
```js
Restangular.all('users').one('5').get()
```
which is not present in the docs and is invalid. The rest is good.

```js
Restangular.one('accounts', 1234).get()
Restangular.all('users').get(1234)
```
It all depends what you want to do. I usually use `one` when either chaining other methods or when dealing with single resources. In this particular case, i would've gone with `all().get()` as the /users/ returns a list. But this is just my personal preference ;)

**Comment by dbuezas** [comment]
oh, I see. Now THAT is weird, it is the only one which works as expected :)
