### ISSUE TITLE
X-HTTP-Method-Override passes method as lowercase

### ISSUE THREAD

**Issue by kevin-brown** [mgonto/restangular#955]
When the method in passed in through the `X-HTTP-Method-Override` header (added in https://github.com/mgonto/restangular/issues/52), they are passed in as lowercase instead of uppercase. The issue was reported a while back with Django REST Framework, and we fixed it by just [forcing all overridden methods to be uppercase](https://github.com/tomchristie/django-rest-framework/pull/1771).

While most servers can _probably_ handle this, it [doesn't follow the spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1.1) and [servers sometimes do strange things](http://stackoverflow.com/q/9645037/359284)

> The Method token indicates the method to be performed on the resource identified by the Request-URI. The method is case-sensitive.

As far as I can tell, this shouldn't be too difficult to fix in the override code.

Related DRF ticket: https://github.com/tomchristie/django-rest-framework/issues/1718

**Comment by grabbou** [comment]
True, to be fixed.

**Comment by grabbou** [comment]
Fix in development branch with tests. Will be merged into master soon and when this happens, this issue will be closed automatically.
