### ISSUE TITLE
How To Prevent $variables In Restangular Post Request

### ISSUE THREAD

**Issue by kuroro21** [mgonto/restangular#956]
Typescript:

```js
interface IFoo {
    description: string;
    id: string;
    name: string;
}

interface Foo extends IFoo {
    $myId: string;
    $type: string;
}
Restangular Call:

public myFoo: Foo;    
//after setting the value of this.myFoo
this.restangular.all("api/foo").post(this.myFoo);
Server Side (.net):

public class Foo
{
    public string Description { get; set; }
    public string Id { get; set; }
    public string Name { get; set; }
}

//Controller
[HttpPost]
[Route("")]
public IHttpActionResult Post(Foo foo)
{
    var updatedFoo = this._fooService.SaveFoo(foo);
    return this.Ok(updatedFoo);
}

```

QUESTION:

My variable (this.foo) in the typescript restangular call contains all the information needed. But inside the controller the variable "foo" is undefined or null. I tried changing the type of "this.myFoo" in my typescript to interface "IFoo" and it works. Correct me if I'm wrong but I think previously this is not a problem with restangular as they don't include other variables with $ symbol in the post request. I recently updated my restangular so maybe this is one of the cause? Is this configurable?

**Comment by grabbou** [comment]
Any TypeScript user on board? For now - I'd suggest SO. If you want to manipulate data that's being send to your server (to e.g. strip unneeded properties, please use request interceptors mentioned in the docs).
