### ISSUE TITLE
Field name conflict

### ISSUE THREAD

**Issue by apellizzn** [mgonto/restangular#957]
I am trying to return this data from my apis
```
[{ id: 1, head: 12, chest: 120},{ id: 2, head: 13, chest: 120},....]
```
but Restangular is replacing the head field with this function
```javascript
function bound() {__bindData__: Array[6]arguments: nullcaller: nulllength: 0name: "bound"}
```
I know this is a particular case the Resangular head function should be called something like _(name)

**Comment by grabbou** [comment]
Closing. 
https://github.com/mgonto/restangular#my-response-is-actually-wrapped-with-some-metadata-how-do-i-get-the-data-in-that-case

Similar #413 that can help you if you have different properties per endpoint.
