### ISSUE TITLE
Cannot use API with trailing slashes

### ISSUE THREAD

**Issue by qwiglydee** [mgonto/restangular#958]
My API designed in the way, that collections has trailing slashes, and objects has not.

Hardcoded path-urlCreator can not add trailing slash, and seems it cannot distinguish fetchUrl for list or single object.

Adding suffix applies globally for all urls.

No way?

**Comment by chao787** [comment]
you can configure it by

    RestangularProvider.setRequestSuffix('/');

**Comment by qwiglydee** [comment]
This will apply suffix globally, not only for collections.

**Comment by grabbou** [comment]
Generally, your REST API should not have problems with trailing slashes and this might be the first signal of bad implementation decision that were made in the past. What's the purpose of having such a difference between collections and single views?
