### ISSUE TITLE
Allow to setFullResponse per request

### ISSUE THREAD

**Issue by fracz** [mgonto/restangular#972]
I generally like extracting the `data` field of my API responses. However, sometimes (only) I need to access headers of a particular request. Currently, I'm doing it like:

```js
Restangular.setFullResponse(true).all('user').getList()
.then(function(response){
  Restangular.setFullResponse(false);
  totalUsers = response.headers('X-Total-Count');
  currentPageUsers = response.data;
});
```

But if there are other simultaneous Restangular requests, they may fail as they expect no full response. Ability to set the full response per request would solve the problem.

**Comment by grabbou** [comment]
True, that should work. Please let us know if you will have any further problems with above solution and we will reopen.

**Comment by gottfrois** [comment]
Hey guys, I'm in a similar situation where I want to access request headers for some request but should not be the "default" behavior on my application.

I am not sure how @Andrewiski response can be applied. Code example would be appreciated.

Thanks

**Comment by poppahorse** [comment]
@gottfrois, a while ago but just in case, in your config block, something like this?

```
angular.module('app')
	.config(function(RestangularProvider) {
		RestangularProvider.addFullRequestInterceptor(
			function(headers, params, element, httpConfig) {
				if(element == 'specific/api/endpoint') {
					RestangularProvider.setFullResponse(true);
				}
				else {
					RestangularProvider.setFullResponse(false);
				}
			}
		);
	})
```

**Comment by tvStatic** [comment]
@poppahorse a follow up to this. The above code results in the same problem as the OPs - the global setFullResponse is set as each request goes out, so the value may not be correct depending on the timing of the responses.

The solution, as far as I can see is use addResponseInterceptor instead, as the response is parsed straight afterwards. For the original case:

```
RestangularProvider.addResponseInterceptor(
    function (data, operation, what) {
        if (operation === "getList" && what === "user") {
            RestangularProvider.setFullResponse(true);
        } else {
            RestangularProvider.setFullResponse(false);
        }
   
        return data;
    }
);
```

**Comment by chandrewz** [comment]
In case someone stumbles on this thread, you can do something like this now for a single request using `setFullResponse`:

```typescript
Restangular.withConfig((RestangularConfigurer) => {
    RestangularConfigurer.setFullResponse(true);
}).all(url);
```
