### ISSUE TITLE
Extender Service Source Code

### ISSUE THREAD

**Issue by TheHandsomeCoder** [mgonto/restangular#973]
In several of the slides that I've read online there is mention of an Extender Service. I was wondering if the source code for this was available anywhere?

**Comment by grabbou** [comment]
Hey, there's a `extendModel` method that should work for you - https://github.com/mgonto/restangular#creating-new-restangular-methods

**Comment by TheHandsomeCoder** [comment]
@grabbou Cheers, I was able to cobble together code that worked for me using the extendModel.

```javascript
angular.module('RankingsApp')
    .factory('Result', function( Restangular) {

        function Result(model) {

            angular.extend(this, model);           
        };

        Result.prototype = {           
           
            CalculatePoints: function() {
               return 10;
            }

        };

        return Result;
    });
```

And then in the extend model I used the following code

```javascript
Restangular.extendModel('results', function(model) {
            var result = new Result(model);
            return result;
        });
```

Hope this helps other people looking to do something similar :)

**Comment by grabbou** [comment]
Nice representative example of how to use extend model :) I am pretty sure this issue will be linked many times in the future.
