### ISSUE TITLE
addFullRequestInterceptor function should be able to return a Promise to resolves the object

### ISSUE THREAD

**Issue by Andrewiski** [mgonto/restangular#974]
It would be helpful for retrieving additional headers for authorization from the server if addFullRequestInterceptor could use a returned promise to resolve the object. That way if the authorization token was known to be expired the user could be prompted for username and password, auth token resolved, and then the promise returned causing Restangular to then continue its original request.  Currently I find my self having to throw a custom error message on the server and handle that error in the Restangular Error interceptor to do prompt the user then issue a retry of the original request.  I am sure there are other scenarios where being able to delay the request until other information is gathered.  Awsome Provider, keep up the good work.

**Comment by grabbou** [comment]
Hey, closing in favour of #891 which is all about promise based request interceptors. Thanks for your ideas and long explanations!
