### ISSUE TITLE
Restangular Getlist is not working 

### ISSUE THREAD

**Issue by binson143** [mgonto/restangular#979]
Dear All,
I am using getList() methode, but its not working , the code is given bewlow

Servce.js

 var userService = function (restangular) {
        var resourceBase = restangular.all("account");

      
        this.getUsers = function () {
            return resourceBase.getList();
        };

        this.addUser = function(user) {
           return resourceBase.post(user);
        };

        this.getUserById = function (id) {
            
         return resourceBase.get(id);
         
        };
        this.updateUser = function (user) {
            user.singleOne = true;
            return user.put();
         
          
        };
    };

and controller 

 function ($scope, userService, modal,$location) {
     
        $scope.users = userService.getUsers(); /// calling service  i also tried  userService.getList().then(function(d){$scope.users=d});
         
   
       
        $scope.activeUser = undefined;
     
        $scope.editUser = function (id) {
            $location.path('/users/edit/'+id);
           
        };
}

my api response is array , sample is given below 

[{"id":"7fdfc4f4-fc84-e411-828e-a0481ca19571","firstname":"Binson","lastname":"Eldhose","username":"binson143","email":"binsoneldhose@outlook.com","mobile":"9846369298","userkey":"EMP-001","notes":"This employee selected from india,He is a programmer","password":null,"image":"noimage.jpg","createdDate":"2014-12-16T11:24:30.627","status":"Active"}]

**Comment by grabbou** [comment]
What exactly does not work? What error message do you get?
