### ISSUE TITLE
[HELP] I have some question in 'put' and 'getList'

### ISSUE THREAD

**Issue by huyinghuan** [mgonto/restangular#980]
There is only one router, for example  ```/session```,  and this api just return a JSON object ```{name: "xx", ...}```

what should  i do coding ?
if I write like the bottom 
```
Restangular.all('session').getList()

#Errors:
#Response for getList SHOULD be an array and not an object or something else

#or 
Restangular.all('session').get()
#Errors
#TypeError: Cannot read property 'toString' of undefined

# I cant  write  Restangular.one('seesion' , id) , because there is no id 
```

and the ```put``` function have the same question.

for example:

I get a json object from other way,  not from ```Restangular.all``` or ```Restangular.one```, 

```
{
  id: "xxx"
  name: "xxx"
}
```

and there is  a api ```/template/:id```   for this object ,

how can i  put this object to ```/template/:id``` ?

yes, I know, if I do this i can put the data to server:

```
var templateHasExist = {id: "xxx", name: "xxx"} //the  data is from other way.
Restangular.one('template', templateHasExist.id).then(function(data){
   template = data
   template.name = templateHasExist.name
  template.put()
})
```

but I don't want to do this. because It  send a needless requestion to server.(data is know, but not is a Restangular object) 

What can i do ?

**Comment by grabbou** [comment]
Please try `Restangular.all('session').customGET` for the first problem.

For the second one:
In order to create ->  `Restangular.all('template').post(elementToPost)`. 
In order to put/update -> `Restangular.one('template', elementToPut.id).put(elementToPut)`.
