### ISSUE TITLE
[bug?] .restangularizeElement() changes route url

### ISSUE THREAD

**Issue by vilsbole** [mgonto/restangular#982]
I'm adding a save method to a collection.
Since the services is used in different parts of the code, it most be able to restangularize the elem if it's not done already.

```
    var Resouces = Restangular.service('myresources');
    Restangular.extendCollection('myresources', function(collection){
      collection.save = function(elem){
        if( !elem.hasOwnProperty('save') ){
          Restangular.restangularizeElement(null, elem, 'myresources');
        }
        console.log(elem);
        return elem
          .save()
          .then(function(res){
            collection.push(res);
            return(res);
          })
      }
      return collection;
    })
```

This works fine for post(), but if i try to delete the newly created object with remove() I see that the api receives a call to: '/api/myresources/undefined/{:id}'

How do i get rid of the 'undefined' in the route? (the elements fetched by the collection work fine).
Looking at the difference between the restangularized element and the other collection elements, I see that the first 
``` 
.parentResource == Object {route: 'myresources', parentResource: null}
 ```

while the second 
```
.parentResouce == null
```

I tried setting it to null after the call but without success.
```
 Restangular.restangularizeElement(null, elem, 'myresources');
 elem.parentResource = null
```

Is this a bug or am I doing something wrong?

**Comment by iamsalnikov** [comment]
I have same issue.

**Comment by grabbou** [comment]
Confirmed with plunkr http://jsfiddle.net/b9n8h9xa/3/

**Comment by tachang** [comment]
Is there any workaround for this?

**Comment by tachang** [comment]
If anyone else encounters this I had success just using .plain() then calling restangularizeElement manually with the route. Also setting fromServer attribute to true.

      scope.example.save().then(function(data) {
        var e = restangular.restangularizeElement('', data.plain(), 'widgets');
        e.fromServer = true;
      });

**Comment by iamsalnikov** [comment]
Thank you! :+1:
