### ISSUE TITLE
Download pdf file from JAX-RS web service

### ISSUE THREAD

**Issue by palacios335** [mgonto/restangular#987]
Hi!, I'm new in Angular and Restangular, when I write this path ( http://localhost:8080/project/webapi/entity/{id}/document ) on my browser I can access to my Restful api and get a PDF file and download it if I do this:

`
<form action="http://localhost:8080/project/webapi/entity/{id}/document" method="GET">
                <button type="submit" >Download </button>  
</form>`

I want to download the file with a Restangular method like Restangular.one("url").get();

I would like you to help me, thank you and excuse my little experience.

**Comment by grabbou** [comment]
Please provide code examples of what you have done or log from developers console. This error typically is not related to angular but to the configuration problem (CORS)
