### ISSUE TITLE
setting a request header when using ALL GET

### ISSUE THREAD

**Issue by c0debreaker** [mgonto/restangular#988]
Hi,

Without using setDefaultHeaders, how can we set a request header when using GET?

Right now, I'm using this code but I want to try a different code without using setDefaultHeaders

```
RestFactory.setDefaultHeaders({ 'Range' : 'bytes=0-100' });
RestFactory.all('export/gw').get('rate', {
    reportresourceid : $scope.reportResourceID
}).then(function(data) {
...
...
...
})
```

**Comment by grabbou** [comment]
Hi,
> get([queryParams, headers]): Gets the element. Query params and headers are optionals
That should do the trick.

You are misusing get() method as you cannot pass path to it, paths should be constructed with restangular methods like `one` or `getList` (full list available in Readme). 

If you modify your code to this one:

`RestFactory.all('export/gw').one('rate').get(null, { 'Range': 'bytes=0-100' });

It should work as expected ;)

**Comment by c0debreaker** [comment]
Thanks!
