### ISSUE TITLE
Best way to compare restangular objects

### ISSUE THREAD

**Issue by emmaguo** [mgonto/restangular#992]
Hello! I am trying to support restangular in my [angular-poller](https://github.com/emmaguo/angular-poller) library where I need to figure out whether two restangular objects are the same or not. `angular.equals` works fine when comparing two `Restangular.one(...)` objects, but not for `Restangular.all(...)`.

```javascript
var users = Restangular.all('users'),
    admins = Restangular.all('admins'),
    user1 = Restangular.one('users', 1),
    user2 = Restangular.one('users', 2);

angular.equals(user1, user1); // True
angular.equals(user1, user2); // False
angular.equals(users, admins); // Returns true, expects false
```

What is the best way to compare two restangular objects? Maybe there could be a `Restangular.equals` method?

**Comment by grabbou** [comment]
Have you tried comparing user1.$object with user2.$object?

**Comment by emmaguo** [comment]
`angular.equals(user1, user2)` works just fine.
The problem is `angular.equals(users, admins)` returns true even though it should be false:-/

**Comment by grabbou** [comment]
Ok, I'll take a look at. If you can provide a working plunkr example, that'd be awesome, although not a requirement.

**Comment by emmaguo** [comment]
Thanks for the quick reply!
Here is a jsfiddle [example](http://jsfiddle.net/emmaguo/b9n8h9xa/).

**Comment by grabbou** [comment]
The issue here is because `Restangular.all` creates a collection element which is an array and the check against it is actually:
```js
if ([] === []) {

}
```
Doing:
```js
if (Restangular.all('admins').route === Restangular.all('users').route)
```
 should give you correct results.

This won't work for single elements, as 
```js
Restangular.one('users', 1)
Restangular.one('users', 2)
```
have the same route value, which is `users`.

The solution would be to write a method:
```js
function isEqual(firstObj, secondObj) {
   return firstObj.route === secondObj.route && (firstObj.id && firstObj.id === secondObj.id);   
}
```
Yours modified JSFiddle http://jsfiddle.net/b9n8h9xa/4/
