### ISSUE TITLE
Restangular makes an extra get request to server!

### ISSUE THREAD

**Issue by ajayak731** [mgonto/restangular#998]
When I make any get request on server, Restangular makes 2 request on API. Below is the code through which I am making request.

function getLevel1Codes() {
               var level1Codes = Restangular.all(levelCodeUrl).getList();
               return level1Codes;
            }
        }

**Comment by grabbou** [comment]
Your code is pretty ok. Please provide a plunkr replicating this issue as AFAIK this looks more like implementation error.

**Comment by mchicote** [comment]
In my case this was due to a mistake on my angular app. I had the controller executed twice, once because of a ng-controller tag on the html and once because of routing. I'm just leaving this here in case someone ends up on this issue report (like me)
